//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: ADX_and_DI
// ID_model: CRSR_1Day_1ADX_9f6ea0d1 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_CRSR_1Day_1ADX_9f6ea0d1", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_CRSR_1Day_9f6ea0d1(smoothedDirectionalMovementMinus, directionalMovementMinus, diMinus, dx, directionalMovementPlus, smoothedDirectionalMovementPlus, adx, trueRange, smoothedTrueRange, diPlus)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=5, max_features=0.5,max_leaf_nodes=30, min_samples_split=10,random_state=843828734)
	if( dx <= 12.3066 )
		if( adx <= 52.5766 )
			if( smoothedTrueRange <= 0.638989 )
				if( smoothedDirectionalMovementMinus <= 0.129259 )
					if( diMinus <= 18.5795 )
						ret := 0.846154 // buy
					if( diMinus > 18.5795 )
						ret := 0.000000
				if( smoothedDirectionalMovementMinus > 0.129259 )
					if( smoothedDirectionalMovementMinus <= 0.154489 )
						ret := -0.666667
					if( smoothedDirectionalMovementMinus > 0.154489 )
						ret := -0.100000
			if( smoothedTrueRange > 0.638989 )
				if( smoothedDirectionalMovementPlus <= 0.248519 )
					if( smoothedDirectionalMovementPlus <= 0.13596 )
						ret := 1.000000 // buy
					if( smoothedDirectionalMovementPlus > 0.13596 )
						ret := -0.626087
				if( smoothedDirectionalMovementPlus > 0.248519 )
					if( diMinus <= 23.5189 )
						ret := -0.488372
					if( diMinus > 23.5189 )
						ret := 0.259259
		if( adx > 52.5766 )
			if( adx <= 57.9682 )
				ret := 1.000000 // buy
			if( adx > 57.9682 )
				ret := 0.000000
	if( dx > 12.3066 )
		if( dx <= 43.6423 )
			if( diMinus <= 18.4576 )
				if( trueRange <= 1.22367 )
					if( directionalMovementMinus <= 0.006053 )
						ret := -0.136986
					if( directionalMovementMinus > 0.006053 )
						ret := 0.567568
				if( trueRange > 1.22367 )
					if( adx <= 22.1083 )
						ret := -0.142857
					if( adx > 22.1083 )
						ret := 0.746988 // buy
			if( diMinus > 18.4576 )
				if( diPlus <= 18.9786 )
					if( trueRange <= 0.561593 )
						ret := 0.061224
					if( trueRange > 0.561593 )
						ret := 0.364286

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
