//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: Ultimate_MA_MTF_V2
// ID_model: BABA_1Day_1ULT_fde01571 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_BABA_1Day_1ULT_fde01571", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_BABA_1Day_fde01571(cr_up2Int, cr_downInt, avg2, avg, ma_downInt, cr_down2Int, cr_upInt, ma_upInt)=>
	var float ret = 0  // # DecisionTreeRegressor(max_depth=5, max_features=0.75, max_leaf_nodes=12,min_samples_leaf=4, min_samples_split=10,random_state=843828734)
	if( avg <= 91.6701 )
		if( avg <= 86.2007 )
			if( avg <= 77.8923 )
				ret := 0.406977
			if( avg > 77.8923 )
				if( avg2 <= 83.2666 )
					if( avg2 <= 78.6995 )
						ret := -0.344538
					if( avg2 > 78.6995 )
						ret := 0.695652
				if( avg2 > 83.2666 )
					if( avg2 <= 98.7109 )
						ret := -0.632479
					if( avg2 > 98.7109 )
						ret := 1.000000 // buy
		if( avg > 86.2007 )
			ret := 0.626609
	if( avg > 91.6701 )
		if( avg2 <= 124.432 )
			if( avg2 <= 92.4089 )
				ret := 0.358696
			if( avg2 > 92.4089 )
				ret := -0.450000
		if( avg2 > 124.432 )
			if( avg2 <= 148.492 )
				if( avg2 <= 137.523 )
					ret := 0.065574
				if( avg2 > 137.523 )
					ret := 0.776596 // buy
			if( avg2 > 148.492 )
				if( avg2 <= 279.847 )
					ret := -0.012363
				if( avg2 > 279.847 )
					ret := -0.681818
	
    ret //return
// Define expected timeframe based on the selected interval: 1Day pine_value: D   Trigger an alert and show a label if the timeframe is incorrect
alert_message_time_wrong = "The current candle TIMEframe is WRONG: "+ str.tostring(timeframe.period) + ", CHANGE it to the CORRECT one:  1DAY !!"
if (str.tostring(timeframe.period) != "D")
    alert(alert_message_time_wrong, alert.freq_once_per_bar_close)
    label.new(bar_index -300, high+30, text = alert_message_time_wrong, style = label.style_label_down,size = size.large, color = color.red, textcolor = color.white)
    log.error(alert_message_time_wrong)

//CODE associated with the technical indicator Ultimate_MA_MTF_V2 
//@version=5
//indicator title="CM_Ultimate_MA_MTF_V2", shorttitle="CM_Ultimate_MA_MTF_V2", overlay=true)

// Inputs

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
