//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: Candlestick_Patterns
// ID_model: AMZN_1Day_1CAN_9f52ba8f Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_AMZN_1Day_1CAN_9f52ba8f", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_AMZN_1Day_9f52ba8f(Piercing_LineInt, Bearish_HaramiInt, Shooting_StarInt, Bullish_HaramiInt, HammerInt, Evening_StarInt, Morning_StarInt, Bullish_KickerInt, DojiInt, Bullish_EngulfingInt, Bearish_KickerInt, Inverted_HammerInt, Dark_Cloud_CoverInt, Bearish_EngulfingInt, Bullish_BeltInt, Hanging_ManInt)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=5, max_features=0.9,max_leaf_nodes=12, min_samples_split=5,random_state=843828734)
	if( DojiInt <= 0.5 )
		if( Bearish_KickerInt <= 0.5 )
			if( Bearish_HaramiInt <= 0.5 )
				if( Bearish_EngulfingInt <= 0.5 )
					if( Morning_StarInt <= 0.5 )
						ret := -0.027037
					if( Morning_StarInt > 0.5 )
						ret := 0.290323
				if( Bearish_EngulfingInt > 0.5 )
					ret := 0.263158
			if( Bearish_HaramiInt > 0.5 )
				if( HammerInt <= 0.5 )
					ret := 0.393443
				if( HammerInt > 0.5 )
					ret := 0.000000
		if( Bearish_KickerInt > 0.5 )
			ret := -0.443038
	if( DojiInt > 0.5 )
		if( Bearish_HaramiInt <= 0.5 )
			if( Bullish_KickerInt <= 0.5 )
				if( Bullish_HaramiInt <= 0.5 )
					if( Evening_StarInt <= 0.5 )
						ret := 0.613924
					if( Evening_StarInt > 0.5 )
						ret := 0.000000
				if( Bullish_HaramiInt > 0.5 )
					ret := 0.083333
			if( Bullish_KickerInt > 0.5 )
				ret := 0.000000
		if( Bearish_HaramiInt > 0.5 )
			if( HammerInt <= 0.5 )
				ret := -0.833333 // sell
			if( HammerInt > 0.5 )
				ret := 0.000000
	
    ret //return
// Define expected timeframe based on the selected interval: 1Day pine_value: D   Trigger an alert and show a label if the timeframe is incorrect
alert_message_time_wrong = "The current candle TIMEframe is WRONG: "+ str.tostring(timeframe.period) + ", CHANGE it to the CORRECT one:  1DAY !!"
if (str.tostring(timeframe.period) != "D")
    alert(alert_message_time_wrong, alert.freq_once_per_bar_close)
    label.new(bar_index -300, high+30, text = alert_message_time_wrong, style = label.style_label_down,size = size.large, color = color.red, textcolor = color.white)
    log.error(alert_message_time_wrong)

//CODE associated with the technical indicator Candlestick_Patterns 
//@version=5
//indicator title="Candles", overlay=true)

DojiSize = input.float(0.05, minval=0.01, title="Doji size")

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
