//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: ADX_and_DI
// ID_model: AMD_5Min_1ADX_18ef87ac Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_AMD_5Min_1ADX_18ef87ac", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_AMD_5Min_18ef87ac(smoothedDirectionalMovementMinus, directionalMovementMinus, diMinus, dx, directionalMovementPlus, smoothedDirectionalMovementPlus, adx, trueRange, smoothedTrueRange, diPlus)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=8, max_features=0.7,min_samples_leaf=4, min_samples_split=5,random_state=843828734)
	if( smoothedDirectionalMovementMinus <= 0.360827 )
		if( smoothedTrueRange <= 0.463746 )
			if( directionalMovementMinus <= 3e-06 )
				if( smoothedDirectionalMovementPlus <= 0.037496 )
					if( trueRange <= 1.01 )
						if( smoothedTrueRange <= 0.430104 )
							if( adx <= 17.6181 )
								if( diPlus <= 28.1316 )
									ret := 0.095178
								if( diPlus > 28.1316 )
									ret := 0.009524
							if( adx > 17.6181 )
								if( diMinus <= 77.7354 )
									ret := -0.001394
								if( diMinus > 77.7354 )
									ret := -0.600000
						if( smoothedTrueRange > 0.430104 )
							if( adx <= 37.2406 )
								if( trueRange <= 0.405942 )
									ret := 0.550000
								if( trueRange > 0.405942 )
									ret := 1.000000 // buy
							if( adx > 37.2406 )
								if( directionalMovementPlus <= 0.169339 )
									ret := -0.025000
								if( directionalMovementPlus > 0.169339 )
									ret := 0.812500 // buy
					if( trueRange > 1.01 )
						if( diMinus <= 38.6159 )
							ret := -0.750000 // sell
						if( diMinus > 38.6159 )
							ret := -1.000000 // sell
				if( smoothedDirectionalMovementPlus > 0.037496 )
					if( directionalMovementPlus <= 0.219137 )
						if( smoothedTrueRange <= 0.428036 )
							if( adx <= 72.1079 )
								if( dx <= 92.2667 )
									ret := 0.078600
								if( dx > 92.2667 )
									ret := 0.310881
							if( adx > 72.1079 )
								if( diPlus <= 57.9311 )
									ret := -0.115108
								if( diPlus > 57.9311 )
									ret := 0.200000
						if( smoothedTrueRange > 0.428036 )
							if( adx <= 71.5113 )
								if( diPlus <= 26.7637 )

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
