//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: MACD_ULT_MTF
// ID_model: AMD_1Day_1MAC_a4a68b46 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_AMD_1Day_1MAC_a4a68b46", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_AMD_1Day_a4a68b46(macd_IsAboveInt, histB_IsDownInt, histA_IsDownInt, histB_IsUpInt, signal, histA_IsUpInt, hist, macd_IsBelowInt, macd)=>
	var float ret = 0  // # DecisionTreeRegressor(max_depth=5, max_features=0.7, max_leaf_nodes=12,min_samples_leaf=4, random_state=843828734)
	if( signal <= 6.58861 )
		if( hist <= -0.057098 )
			if( signal <= 5.28567 )
				if( macd <= -7.39915 )
					ret := 0.842105 // buy
				if( macd > -7.39915 )
					if( histB_IsUpInt <= 0.5 )
						ret := -0.275040
					if( histB_IsUpInt > 0.5 )
						ret := -0.013158
			if( signal > 5.28567 )
				ret := 0.790698 // buy
		if( hist > -0.057098 )
			if( macd_IsBelowInt <= 0.5 )
				if( hist <= 1.83833 )
					if( signal <= 0.123538 )
						ret := 0.231417
					if( signal > 0.123538 )
						ret := 0.024362
				if( hist > 1.83833 )
					if( macd <= 4.64302 )
						ret := -0.180851
					if( macd > 4.64302 )
						ret := -0.702128 // sell
			if( macd_IsBelowInt > 0.5 )
				if( signal <= 0.293408 )
					ret := 0.711957 // buy
				if( signal > 0.293408 )
					if( signal <= 0.496699 )
						ret := -0.180328
					if( signal > 0.496699 )
						ret := 0.600000
	if( signal > 6.58861 )
		ret := -0.671141
	
    ret //return
// Define expected timeframe based on the selected interval: 1Day pine_value: D   Trigger an alert and show a label if the timeframe is incorrect
alert_message_time_wrong = "The current candle TIMEframe is WRONG: "+ str.tostring(timeframe.period) + ", CHANGE it to the CORRECT one:  1DAY !!"
if (str.tostring(timeframe.period) != "D")
    alert(alert_message_time_wrong, alert.freq_once_per_bar_close)
    label.new(bar_index -300, high+30, text = alert_message_time_wrong, style = label.style_label_down,size = size.large, color = color.red, textcolor = color.white)
    log.error(alert_message_time_wrong)

//CODE associated with the technical indicator MACD_ULT_MTF 
//@version=5
//indicator title="CM_MacD_Ult_MTF", shorttitle="CM_Ult_MacD_MTF", overlay=false)

source = close

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
