//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: L_Bull_Bear_Power, L_Vortex_Indicator
// ID_model: ADBE_1Day_2BV0_001b795d Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_ADBE_1Day_2BV0_001b795d", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_ADBE_1Day_001b795d(bullPower, bbp, bearPower, bbm, BBPower_Color, VIP, VIM, VIP_VIM)=>
	var float ret = 0  // # DecisionTreeRegressor(max_depth=5, max_features=0.4, max_leaf_nodes=12,min_samples_split=10, random_state=843828734)
	if( bbm <= 20.2314 )
		if( bearPower <= -22.574 )
			if( bullPower <= -10.4579 )
				if( bullPower <= -20.3888 )
					ret := 0.197674
				if( bullPower > -20.3888 )
					ret := 0.825243 // buy
			if( bullPower > -10.4579 )
				ret := -0.400000
		if( bearPower > -22.574 )
			if( bbp <= -23.2485 )
				if( VIP <= 0.878699 )
					ret := 0.170213
				if( VIP > 0.878699 )
					ret := -0.681818
			if( bbp > -23.2485 )
				if( bearPower <= -4.50333 )
					if( bullPower <= 5.17719 )
						ret := 0.078125
					if( bullPower > 5.17719 )
						ret := 0.673077
				if( bearPower > -4.50333 )
					if( VIP <= 0.891189 )
						ret := -0.457627
					if( VIP > 0.891189 )
						ret := 0.034891
	if( bbm > 20.2314 )
		if( bullPower <= -17.0785 )
			ret := 0.708333 // buy
		if( bullPower > -17.0785 )
			if( VIP <= 1.13761 )
				ret := -0.620155
			if( VIP > 1.13761 )
				ret := 0.136364
	
    ret //return
// Define expected timeframe based on the selected interval: 1Day pine_value: D   Trigger an alert and show a label if the timeframe is incorrect
alert_message_time_wrong = "The current candle TIMEframe is WRONG: "+ str.tostring(timeframe.period) + ", CHANGE it to the CORRECT one:  1DAY !!"
if (str.tostring(timeframe.period) != "D")
    alert(alert_message_time_wrong, alert.freq_once_per_bar_close)
    label.new(bar_index -300, high+30, text = alert_message_time_wrong, style = label.style_label_down,size = size.large, color = color.red, textcolor = color.white)
    log.error(alert_message_time_wrong)

//CODE associated with the technical indicator L_Bull_Bear_Power 
//@version=5
//indicator "Bull Bear Power", shorttitle="BBP")
lengthInput = input.int(13, title="Length")
bullPower = high - ta.ema(close, lengthInput)

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
