//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: ADX_and_DI
// ID_model: ADBE_1Day_1ADX_d828a271 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_ADBE_1Day_1ADX_d828a271", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_ADBE_1Day_d828a271(smoothedDirectionalMovementMinus, directionalMovementMinus, diMinus, dx, directionalMovementPlus, smoothedDirectionalMovementPlus, adx, trueRange, smoothedTrueRange, diPlus)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=5, max_features=0.65,min_samples_leaf=4, min_samples_split=5,random_state=843828734)
	if( diMinus <= 32.9981 )
		if( smoothedDirectionalMovementMinus <= 4.0186 )
			if( smoothedTrueRange <= 15.6538 )
				if( diPlus <= 16.8626 )
					if( smoothedDirectionalMovementPlus <= 0.371862 )
						ret := 0.382353
					if( smoothedDirectionalMovementPlus > 0.371862 )
						ret := -0.625984
				if( diPlus > 16.8626 )
					if( adx <= 43.829 )
						ret := 0.120026
					if( adx > 43.829 )
						ret := -0.179310
			if( smoothedTrueRange > 15.6538 )
				if( trueRange <= 27.6693 )
					if( diPlus <= 25.7537 )
						ret := 0.920635 // buy
					if( diPlus > 25.7537 )
						ret := 0.266667
				if( trueRange > 27.6693 )
					ret := -1.000000 // sell
		if( smoothedDirectionalMovementMinus > 4.0186 )
			if( dx <= 37.9957 )
				if( trueRange <= 19.6845 )
					if( smoothedTrueRange <= 13.725 )
						ret := 0.500000
					if( smoothedTrueRange > 13.725 )
						ret := -0.500000
				if( trueRange > 19.6845 )
					if( adx <= 35.6473 )
						ret := -0.931034 // sell
					if( adx > 35.6473 )
						ret := -0.619048
			if( dx > 37.9957 )
				if( smoothedDirectionalMovementPlus <= 2.08785 )
					if( smoothedDirectionalMovementPlus <= 1.86063 )
						ret := 0.333333
					if( smoothedDirectionalMovementPlus > 1.86063 )
						ret := 1.000000 // buy
				if( smoothedDirectionalMovementPlus > 2.08785 )
					if( diMinus <= 32.293 )
						ret := 0.000000
					if( diMinus > 32.293 )
						ret := -1.000000 // sell
	if( diMinus > 32.9981 )
		if( smoothedDirectionalMovementPlus <= 2.05757 )
			if( directionalMovementPlus <= 7.57378 )
				if( directionalMovementMinus <= 7.05 )

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
