//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: L_Stochastic_RSI
// ID_model: ADBE_1Day_1S00_9691d457 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_ADBE_1Day_1S00_9691d457", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_ADBE_1Day_9691d457(rsi1, smoothK_k, d_k, k, d, smoothD_d)=>
	var float ret = 0  // # DecisionTreeRegressor(max_depth=5, max_features=0.6, max_leaf_nodes=12,min_samples_split=5, random_state=843828734)
	if( rsi1 <= 25.7288 )
		if( smoothK_k <= 48.0745 )
			ret := 0.722222 // buy
		if( smoothK_k > 48.0745 )
			ret := -0.909091 // sell
	if( rsi1 > 25.7288 )
		if( smoothD_d <= 84.3383 )
			if( rsi1 <= 63.9609 )
				if( k <= 58.705 )
					if( rsi1 <= 50.9535 )
						ret := -0.175595
					if( rsi1 > 50.9535 )
						ret := 0.050481
				if( k > 58.705 )
					if( smoothD_d <= 79.1909 )
						ret := 0.373967
					if( smoothD_d > 79.1909 )
						ret := -0.138614
			if( rsi1 > 63.9609 )
				if( k <= 85.8689 )
					ret := -0.225243
				if( k > 85.8689 )
					ret := -0.614754
		if( smoothD_d > 84.3383 )
			if( d_k <= 10.5263 )
				if( smoothD_d <= 89.0099 )
					if( rsi1 <= 79.0961 )
						ret := 0.683824
					if( rsi1 > 79.0961 )
						ret := -0.160000
				if( smoothD_d > 89.0099 )
					ret := 0.250633
			if( d_k > 10.5263 )
				ret := -0.750000 // sell
	
    ret //return
// Define expected timeframe based on the selected interval: 1Day pine_value: D   Trigger an alert and show a label if the timeframe is incorrect
alert_message_time_wrong = "The current candle TIMEframe is WRONG: "+ str.tostring(timeframe.period) + ", CHANGE it to the CORRECT one:  1DAY !!"
if (str.tostring(timeframe.period) != "D")
    alert(alert_message_time_wrong, alert.freq_once_per_bar_close)
    label.new(bar_index -300, high+30, text = alert_message_time_wrong, style = label.style_label_down,size = size.large, color = color.red, textcolor = color.white)
    log.error(alert_message_time_wrong)

//CODE associated with the technical indicator L_Stochastic_RSI 
//@version=5
//indicator title="Stochastic RSI", shorttitle="Stoch RSI", format=format.price, precision=2, timeframe="", timeframe_gaps=true)
smoothK = input.int(3, "K", minval=1)
smoothD = input.int(3, "D", minval=1)

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
