//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: SuperTrend
// ID_model: ADSK_15Min_1SUP_0cdf0328 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_ADSK_15Min_1SUP_0cdf0328", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_ADSK_15Min_0cdf0328(atr, up, dn1, sellSignalInt, buySignalInt, atr2, dn, trend, up1)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=8, max_features=0.7,min_samples_leaf=4, min_samples_split=5,random_state=843828734)
	if( dn <= 199.401 )
		if( atr <= 0.510632 )
			if( up1 <= 83.594 )
				if( atr2 <= 0.348237 )
					if( dn1 <= 82.2358 )
						if( dn <= 81.4722 )
							if( atr <= 0.383065 )
								if( atr2 <= 0.16047 )
									ret := -0.288660
								if( atr2 > 0.16047 )
									ret := 0.022293
							if( atr > 0.383065 )
								if( up1 <= 73.5304 )
									ret := -1.000000 // sell
								if( up1 > 73.5304 )
									ret := 0.250000
						if( dn > 81.4722 )
							if( up1 <= 80.5923 )
								if( up1 <= 80.0351 )
									ret := -0.652174
								if( up1 > 80.0351 )
									ret := -0.094340
							if( up1 > 80.5923 )
								if( up1 <= 80.7902 )
									ret := -0.789474 // sell
								if( up1 > 80.7902 )
									ret := -0.441860
					if( dn1 > 82.2358 )
						if( dn <= 85.4545 )
							if( atr2 <= 0.1275 )
								ret := -1.000000 // sell
							if( atr2 > 0.1275 )
								if( atr2 <= 0.239101 )
									ret := 0.356481
								if( atr2 > 0.239101 )
									ret := 0.150442
						if( dn > 85.4545 )
							ret := -0.666667
				if( atr2 > 0.348237 )
					if( dn1 <= 77.7855 )
						if( dn1 <= 70.543 )
							if( up <= 67.6552 )
								ret := 1.000000 // buy
							if( up > 67.6552 )
								if( atr2 <= 0.424962 )
									ret := 0.750000 // buy
								if( atr2 > 0.424962 )
									ret := 0.800000 // buy

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
