//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: Ultimate_MA_MTF_V2
// ID_model: ADSK_1Day_1ULT_7d5b9d39 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_ADSK_1Day_1ULT_7d5b9d39", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_ADSK_1Day_7d5b9d39(cr_up2Int, cr_downInt, avg2, avg, ma_downInt, cr_down2Int, cr_upInt, ma_upInt)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=5, max_features=0.9,max_leaf_nodes=12, min_samples_split=5,random_state=843828734)
	if( avg <= 194.261 )
		if( avg2 <= 168.029 )
			if( avg2 <= 165.992 )
				if( avg2 <= 146.231 )
					if( avg <= 113.955 )
						ret := 0.240143
					if( avg > 113.955 )
						ret := -0.180662
				if( avg2 > 146.231 )
					ret := 0.369099
			if( avg2 > 165.992 )
				if( avg <= 182.606 )
					ret := -0.644737
				if( avg > 182.606 )
					ret := 1.000000 // buy
		if( avg2 > 168.029 )
			ret := 0.648276
	if( avg > 194.261 )
		if( avg2 <= 197.102 )
			if( avg2 <= 192.434 )
				ret := 0.375000
			if( avg2 > 192.434 )
				ret := -0.863636 // sell
		if( avg2 > 197.102 )
			if( avg2 <= 200.729 )
				ret := 0.366667
			if( avg2 > 200.729 )
				if( avg2 <= 206.138 )
					ret := -0.465116
				if( avg2 > 206.138 )
					if( avg <= 305.719 )
						ret := -0.030576
					if( avg > 305.719 )
						ret := -0.615385
	
    ret //return
// Define expected timeframe based on the selected interval: 1Day pine_value: D   Trigger an alert and show a label if the timeframe is incorrect
alert_message_time_wrong = "The current candle TIMEframe is WRONG: "+ str.tostring(timeframe.period) + ", CHANGE it to the CORRECT one:  1DAY !!"
if (str.tostring(timeframe.period) != "D")
    alert(alert_message_time_wrong, alert.freq_once_per_bar_close)
    label.new(bar_index -300, high+30, text = alert_message_time_wrong, style = label.style_label_down,size = size.large, color = color.red, textcolor = color.white)
    log.error(alert_message_time_wrong)

//CODE associated with the technical indicator Ultimate_MA_MTF_V2 
//@version=5
//indicator title="CM_Ultimate_MA_MTF_V2", shorttitle="CM_Ultimate_MA_MTF_V2", overlay=true)

// Inputs

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
