//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: L_Bull_Bear_Power, L_Stochastic_RSI
// ID_model: ADSK_1Day_2BS0_908bf5af Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_ADSK_1Day_2BS0_908bf5af", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_ADSK_1Day_908bf5af(bullPower, bbp, bearPower, bbm, BBPower_Color, rsi1, smoothK_k, d_k, k, d, smoothD_d)=>
	var float ret = 0  // # DecisionTreeRegressor(max_depth=5, max_features=0.65, random_state=843828734)
	if( bullPower <= 0.129094 )
		if( k <= 0.978339 )
			if( bullPower <= -5.95042 )
				if( bearPower <= -29.5614 )
					ret := 0.000000
				if( bearPower > -29.5614 )
					if( bbm <= 3.555 )
						ret := 0.000000
					if( bbm > 3.555 )
						ret := 0.910448 // buy
			if( bullPower > -5.95042 )
				if( smoothD_d <= 1.1185 )
					if( rsi1 <= 33.5044 )
						ret := 0.375000
					if( rsi1 > 33.5044 )
						ret := -0.700000 // sell
				if( smoothD_d > 1.1185 )
					if( bbm <= 1.562 )
						ret := 0.000000
					if( bbm > 1.562 )
						ret := 0.731707 // buy
		if( k > 0.978339 )
			if( bbm <= 5.49962 )
				if( smoothK_k <= 33.9936 )
					if( rsi1 <= 40.9375 )
						ret := 0.438849
					if( rsi1 > 40.9375 )
						ret := -0.159420
				if( smoothK_k > 33.9936 )
					if( rsi1 <= 34.617 )
						ret := -0.090909
					if( rsi1 > 34.617 )
						ret := 0.703448 // buy
			if( bbm > 5.49962 )
				if( smoothK_k <= 45.7155 )
					if( smoothD_d <= 1.37858 )
						ret := 0.611111
					if( smoothD_d > 1.37858 )
						ret := -0.426877
				if( smoothK_k > 45.7155 )
					if( bbp <= -14.1591 )
						ret := 0.672414
					if( bbp > -14.1591 )
						ret := -0.103448
	if( bullPower > 0.129094 )
		if( smoothK_k <= 80.2185 )
			if( bbm <= 5.03022 )
				if( k <= 50.3343 )

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
