//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: Bollinger_RSI_Double_Strategy
// ID_model: ASAN_1Hour_1BOL_960a637a Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_ASAN_1Hour_1BOL_960a637a", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_ASAN_1Hour_960a637a(BBupper, crossunder_rsi_bbupperInt, dif_source_BBlower, BBlower, vrsi, dif_source_BBupper, crossover_rsi_bblowerInt)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=6, max_features=0.7,max_leaf_nodes=30, min_samples_leaf=7,random_state=843828734)
	if( dif_source_BBlower <= -0.52506 )
		if( BBupper <= 113.391 )
			if( BBlower <= 16.9451 )
				ret := 0.974359 // buy
			if( BBlower > 16.9451 )
				if( dif_source_BBupper <= -13.568 )
					if( dif_source_BBlower <= -1.63591 )
						if( BBlower <= 62.1121 )
							ret := 0.821429 // buy
						if( BBlower > 62.1121 )
							ret := 0.384615
					if( dif_source_BBlower > -1.63591 )
						if( BBupper <= 74.3814 )
							ret := 1.000000 // buy
						if( BBupper > 74.3814 )
							ret := 0.875000 // buy
				if( dif_source_BBupper > -13.568 )
					if( vrsi <= 29.08 )
						if( dif_source_BBupper <= -4.04384 )
							ret := 0.615385
						if( dif_source_BBupper > -4.04384 )
							ret := 0.000000
					if( vrsi > 29.08 )
						if( vrsi <= 45.9079 )
							ret := -0.457143
						if( vrsi > 45.9079 )
							ret := 0.692308
		if( BBupper > 113.391 )
			if( vrsi <= 35.4871 )
				if( dif_source_BBupper <= -38.9256 )
					if( dif_source_BBupper <= -58.7671 )
						ret := -0.350000
					if( dif_source_BBupper > -58.7671 )
						ret := 0.533333
				if( dif_source_BBupper > -38.9256 )
					ret := -1.000000 // sell
			if( vrsi > 35.4871 )
				if( dif_source_BBupper <= -88.0606 )
					ret := -0.666667
				if( dif_source_BBupper > -88.0606 )
					ret := -0.958333 // sell
	if( dif_source_BBlower > -0.52506 )
		if( dif_source_BBupper <= -70.9038 )
			if( BBlower <= 63.8528 )
				if( dif_source_BBlower <= 17.4339 )
					ret := 1.000000 // buy
				if( dif_source_BBlower > 17.4339 )
					if( dif_source_BBupper <= -74.1703 )

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
