//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: Bollinger_RSI_Double_Strategy
// ID_model: AVAXUSDT_1Day_1BOL_f6cf10aa Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_AVAXUSDT_1Day_1BOL_f6cf10aa", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_AVAXUSDT_1Day_f6cf10aa(BBupper, crossunder_rsi_bbupperInt, dif_source_BBlower, BBlower, vrsi, dif_source_BBupper, crossover_rsi_bblowerInt)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=5, max_features=0.5,max_leaf_nodes=30, min_samples_leaf=4,min_samples_split=10, random_state=843828734)
	if( vrsi <= 95.9796 )
		if( dif_source_BBlower <= -0.300307 )
			if( BBlower <= 46.8286 )
				if( dif_source_BBlower <= -11.2053 )
					if( BBupper <= 125.912 )
						ret := 0.428571
					if( BBupper > 125.912 )
						ret := 0.750000 // buy
				if( dif_source_BBlower > -11.2053 )
					if( dif_source_BBupper <= -105.369 )
						ret := 0.000000
					if( dif_source_BBupper > -105.369 )
						ret := -0.951613 // sell
			if( BBlower > 46.8286 )
				ret := 0.000000
		if( dif_source_BBlower > -0.300307 )
			if( BBlower <= 19.5323 )
				if( BBlower <= 1.72556 )
					if( dif_source_BBupper <= -13.9758 )
						ret := -0.337438
					if( dif_source_BBupper > -13.9758 )
						ret := 0.090465
				if( BBlower > 1.72556 )
					if( dif_source_BBupper <= -26.8436 )
						ret := 0.625000
					if( dif_source_BBupper > -26.8436 )
						ret := 0.113281
			if( BBlower > 19.5323 )
				if( BBlower <= 23.9353 )
					if( dif_source_BBlower <= 2.16268 )
						ret := 0.833333 // buy
					if( dif_source_BBlower > 2.16268 )
						ret := -0.647059
				if( BBlower > 23.9353 )
					if( BBlower <= 41.6883 )
						ret := 0.423077
					if( BBlower > 41.6883 )
						ret := -0.600000
	if( vrsi > 95.9796 )
		if( BBupper <= 53.2696 )
			if( dif_source_BBlower <= 41.9786 )
				if( BBlower <= 2.84068 )
					if( BBupper <= 43.1962 )
						ret := 0.500000
					if( BBupper > 43.1962 )
						ret := 0.833333 // buy
				if( BBlower > 2.84068 )
					if( dif_source_BBlower <= 10.1236 )

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
