//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: L_Bull_Bear_Power, L_Triple_EMA
// ID_model: AVAXUSDT_1Day_2BT0_a5ad20cd Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_AVAXUSDT_1Day_2BT0_a5ad20cd", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_AVAXUSDT_1Day_a5ad20cd(bullPower, bbp, bearPower, bbm, BBPower_Color, ema3, tema, ema2, ema12, ema13, ema1)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=5, max_features=0.7,max_leaf_nodes=12, min_samples_leaf=4,random_state=843828734)
	if( ema1 <= 27.1854 )
		if( ema12 <= 0.597949 )
			if( ema12 <= -1.63778 )
				ret := 0.643678
			if( ema12 > -1.63778 )
				if( ema3 <= 3.29903 )
					ret := 0.928571 // buy
				if( ema3 > 3.29903 )
					ret := 0.028694
		if( ema12 > 0.597949 )
			if( ema1 <= 22.803 )
				ret := 0.629630
			if( ema1 > 22.803 )
				ret := -0.108108
	if( ema1 > 27.1854 )
		if( ema1 <= 28.4615 )
			if( ema2 <= 28.5974 )
				ret := -0.821429 // sell
			if( ema2 > 28.5974 )
				ret := 0.545455
		if( ema1 > 28.4615 )
			if( ema3 <= 106.665 )
				if( tema <= 61.7008 )
					if( tema <= 45.0577 )
						ret := -0.077151
					if( tema > 45.0577 )
						ret := -0.536000
				if( tema > 61.7008 )
					if( ema3 <= 78.0864 )
						ret := 0.484375
					if( ema3 > 78.0864 )
						ret := -0.152174
			if( ema3 > 106.665 )
				ret := -0.837209 // sell
	
    ret //return
// Define expected timeframe based on the selected interval: 1Day pine_value: D   Trigger an alert and show a label if the timeframe is incorrect
alert_message_time_wrong = "The current candle TIMEframe is WRONG: "+ str.tostring(timeframe.period) + ", CHANGE it to the CORRECT one:  1DAY !!"
if (str.tostring(timeframe.period) != "D")
    alert(alert_message_time_wrong, alert.freq_once_per_bar_close)
    label.new(bar_index -300, high+30, text = alert_message_time_wrong, style = label.style_label_down,size = size.large, color = color.red, textcolor = color.white)
    log.error(alert_message_time_wrong)

//CODE associated with the technical indicator L_Bull_Bear_Power 
//@version=5
//indicator "Bull Bear Power", shorttitle="BBP")
lengthInput = input.int(13, title="Length")
bullPower = high - ta.ema(close, lengthInput)

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
