//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: Bollinger_RSI_Double_Strategy
// ID_model: GTLB_1Hour_1BOL_20c618bb Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_GTLB_1Hour_1BOL_20c618bb", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_GTLB_1Hour_20c618bb(crossunder_rsi_bbupperInt, BBlower, dif_source_BBupper, crossover_rsi_bblowerInt, vrsi, BBupper, dif_source_BBlower)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=6, max_features=0.9,min_samples_leaf=7, random_state=843828734)
	if( BBlower <= 41.4193 )
		if( dif_source_BBlower <= 6.37228 )
			if( BBupper <= 41.9516 )
				if( BBlower <= 29.0175 )
					if( dif_source_BBupper <= -4.87706 )
						if( BBlower <= 28.5641 )
							ret := 0.807692 // buy
						if( BBlower > 28.5641 )
							ret := 0.062500
					if( dif_source_BBupper > -4.87706 )
						if( BBupper <= 33.7079 )
							ret := 0.418919
						if( BBupper > 33.7079 )
							ret := -0.142857
				if( BBlower > 29.0175 )
					if( BBlower <= 29.367 )
						ret := -0.714286 // sell
					if( BBlower > 29.367 )
						if( vrsi <= 54.4153 )
							ret := 0.122699
						if( vrsi > 54.4153 )
							ret := -0.235955
			if( BBupper > 41.9516 )
				if( BBlower <= 34.424 )
					if( BBupper <= 81.8804 )
						if( dif_source_BBlower <= 6.12132 )
							ret := 0.790210 // buy
						if( dif_source_BBlower > 6.12132 )
							ret := 0.400000
					if( BBupper > 81.8804 )
						if( dif_source_BBupper <= -46.9836 )
							ret := 0.500000
						if( dif_source_BBupper > -46.9836 )
							ret := -0.727273 // sell
				if( BBlower > 34.424 )
					if( BBupper <= 83.2934 )
						if( BBlower <= 40.4747 )
							ret := 0.384718
						if( BBlower > 40.4747 )
							ret := 0.030534
					if( BBupper > 83.2934 )
						if( dif_source_BBupper <= -44.8637 )
							ret := 0.555556
						if( dif_source_BBupper > -44.8637 )
							ret := -0.800000 // sell
		if( dif_source_BBlower > 6.37228 )
			if( BBlower <= 26.1209 )
				if( dif_source_BBupper <= -29.3775 )

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
