//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: L_Stochastic_RSI, L_Vortex_Indicator
// ID_model: DOTUSDT_1Day_2SV0_2d5e365e Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_DOTUSDT_1Day_2SV0_2d5e365e", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_DOTUSDT_1Day_2d5e365e(d, d_k, smoothK_k, k, rsi1, smoothD_d, VIP, VIP_VIM, VIM)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=5, max_features=0.7,max_leaf_nodes=12, min_samples_leaf=4,min_samples_split=5, random_state=843828734)
	if( smoothK_k <= 12.543 )
		if( rsi1 <= 48.9789 )
			if( d_k <= -3.24817 )
				ret := 0.625000
			if( d_k > -3.24817 )
				ret := -0.029508
		if( rsi1 > 48.9789 )
			ret := 0.598425
	if( smoothK_k > 12.543 )
		if( smoothD_d <= 79.1655 )
			if( smoothD_d <= 35.0807 )
				if( smoothD_d <= 19.3207 )
					if( VIM <= 0.915856 )
						ret := 0.620690
					if( VIM > 0.915856 )
						ret := -0.325153
				if( smoothD_d > 19.3207 )
					if( smoothD_d <= 20.7375 )
						ret := 0.714286 // buy
					if( smoothD_d > 20.7375 )
						ret := 0.062500
			if( smoothD_d > 35.0807 )
				if( d <= 55.5759 )
					if( smoothK_k <= 55.5386 )
						ret := -0.603509
					if( smoothK_k > 55.5386 )
						ret := 0.360000
				if( d > 55.5759 )
					if( d <= 66.2965 )
						ret := 0.225131
					if( d > 66.2965 )
						ret := -0.269896
		if( smoothD_d > 79.1655 )
			ret := 0.162835
	
    ret //return
// Define expected timeframe based on the selected interval: 1Day pine_value: D   Trigger an alert and show a label if the timeframe is incorrect
alert_message_time_wrong = "The current candle TIMEframe is WRONG: "+ str.tostring(timeframe.period) + ", CHANGE it to the CORRECT one:  1DAY !!"
if (str.tostring(timeframe.period) != "D")
    alert(alert_message_time_wrong, alert.freq_once_per_bar_close)
    label.new(bar_index -300, high+30, text = alert_message_time_wrong, style = label.style_label_down,size = size.large, color = color.red, textcolor = color.white)
    log.error(alert_message_time_wrong)

//CODE associated with the technical indicator L_Stochastic_RSI 
//@version=5
//indicator title="Stochastic RSI", shorttitle="Stoch RSI", format=format.price, precision=2, timeframe="", timeframe_gaps=true)
smoothK = input.int(3, "K", minval=1)
smoothD = input.int(3, "D", minval=1)

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
