//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: SuperTrend
// ID_model: DOTUSDT_1Day_1SUP_3607b73a Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_DOTUSDT_1Day_1SUP_3607b73a", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_DOTUSDT_1Day_3607b73a(dn1, trend, atr, atr2, buySignalInt, sellSignalInt, up1, up, dn)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=5, max_features=0.7,max_leaf_nodes=12, min_samples_leaf=4,min_samples_split=5, random_state=843828734)
	if( up1 <= 5.28554 )
		if( dn1 <= 5.22034 )
			ret := 0.397906
		if( dn1 > 5.22034 )
			if( atr <= 0.265294 )
				ret := -0.261628
			if( atr > 0.265294 )
				if( up1 <= 3.73626 )
					if( up <= 3.10479 )
						ret := 0.368421
					if( up > 3.10479 )
						ret := -0.493506
				if( up1 > 3.73626 )
					ret := 0.347938
	if( up1 > 5.28554 )
		if( atr2 <= 1.66205 )
			ret := -0.266667
		if( atr2 > 1.66205 )
			if( up <= 19.496 )
				if( up <= 15.693 )
					if( atr <= 2.26851 )
						ret := 0.511111
					if( atr > 2.26851 )
						ret := -0.212121
				if( up > 15.693 )
					ret := 0.674847
			if( up > 19.496 )
				if( atr <= 2.40573 )
					ret := -0.933333 // sell
				if( atr > 2.40573 )
					if( dn1 <= 44.2701 )
						ret := 0.686047
					if( dn1 > 44.2701 )
						ret := -0.350962
	
    ret //return
// Define expected timeframe based on the selected interval: 1Day pine_value: D   Trigger an alert and show a label if the timeframe is incorrect
alert_message_time_wrong = "The current candle TIMEframe is WRONG: "+ str.tostring(timeframe.period) + ", CHANGE it to the CORRECT one:  1DAY !!"
if (str.tostring(timeframe.period) != "D")
    alert(alert_message_time_wrong, alert.freq_once_per_bar_close)
    label.new(bar_index -300, high+30, text = alert_message_time_wrong, style = label.style_label_down,size = size.large, color = color.red, textcolor = color.white)
    log.error(alert_message_time_wrong)

//CODE associated with the technical indicator SuperTrend 
//@version=5
//indicator title="Supertrend", overlay=true, format=format.price, precision=2, timeframe="")

Periods = input.int(title="ATR Period", defval=10)

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
