//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: ADX_and_DI
// ID_model: DBX_15Min_1ADX_1801595f Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_DBX_15Min_1ADX_1801595f", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_DBX_15Min_1801595f(dx, directionalMovementMinus, diPlus, smoothedDirectionalMovementMinus, trueRange, smoothedDirectionalMovementPlus, smoothedTrueRange, directionalMovementPlus, diMinus, adx)=>
	var float ret = 0  // # DecisionTreeRegressor(max_depth=6, max_features=0.7, min_samples_split=10,random_state=843828734)
	if( directionalMovementMinus <= 0.101625 )
		if( directionalMovementPlus <= 0.101687 )
			if( diPlus <= 31.8304 )
				if( diMinus <= 41.8834 )
					if( directionalMovementPlus <= 0.024998 )
						if( directionalMovementMinus <= 0.043182 )
							ret := 0.006449
						if( directionalMovementMinus > 0.043182 )
							ret := 0.076684
					if( directionalMovementPlus > 0.024998 )
						if( dx <= 22.584 )
							ret := -0.006959
						if( dx > 22.584 )
							ret := -0.114171
				if( diMinus > 41.8834 )
					if( diPlus <= 25.9998 )
						if( adx <= 58.3431 )
							ret := 0.058604
						if( adx > 58.3431 )
							ret := 0.287402
					if( diPlus > 25.9998 )
						if( smoothedDirectionalMovementMinus <= 0.035125 )
							ret := -0.071429
						if( smoothedDirectionalMovementMinus > 0.035125 )
							ret := 0.371841
			if( diPlus > 31.8304 )
				if( adx <= 38.9532 )
					if( diMinus <= 39.52 )
						if( adx <= 11.5941 )
							ret := 0.220812
						if( adx > 11.5941 )
							ret := -0.048036
					if( diMinus > 39.52 )
						if( diPlus <= 42.03 )
							ret := 0.216157
						if( diPlus > 42.03 )
							ret := -0.212389
				if( adx > 38.9532 )
					if( smoothedDirectionalMovementPlus <= 0.041437 )
						if( smoothedDirectionalMovementMinus <= 0.032143 )
							ret := -0.057641
						if( smoothedDirectionalMovementMinus > 0.032143 )
							ret := -0.635294
					if( smoothedDirectionalMovementPlus > 0.041437 )
						if( directionalMovementPlus <= 0.096478 )
							ret := -0.224029
						if( directionalMovementPlus > 0.096478 )
							ret := 0.378788

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
