//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: L_Vortex_Indicator
// ID_model: DBX_1Day_1V00_597be5a2 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_DBX_1Day_1V00_597be5a2", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_DBX_1Day_597be5a2(VIP, VIP_VIM, VIM)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=5, max_features=0.9,max_leaf_nodes=12, min_samples_split=5,random_state=843828734)
	if( VIP <= 0.964878 )
		if( VIP <= 0.733232 )
			if( VIM <= 1.31445 )
				ret := -0.827586 // sell
			if( VIM > 1.31445 )
				ret := -0.305882
		if( VIP > 0.733232 )
			if( VIP <= 0.93435 )
				if( VIM <= 1.05302 )
					ret := -0.641509
				if( VIM > 1.05302 )
					if( VIM <= 1.24652 )
						ret := 0.155093
					if( VIM > 1.24652 )
						ret := 0.732143 // buy
			if( VIP > 0.93435 )
				ret := 0.512195
	if( VIP > 0.964878 )
		if( VIP_VIM <= 0.644295 )
			if( VIM <= 0.689618 )
				ret := 0.800000 // buy
			if( VIM > 0.689618 )
				if( VIM <= 1.07 )
					if( VIP_VIM <= 0.055825 )
						ret := 0.150725
					if( VIP_VIM > 0.055825 )
						ret := -0.113424
				if( VIM > 1.07 )
					ret := -0.425532
		if( VIP_VIM > 0.644295 )
			if( VIP <= 1.27977 )
				ret := 0.500000
			if( VIP > 1.27977 )
				ret := -0.764706 // sell
	
    ret //return
// Define expected timeframe based on the selected interval: 1Day pine_value: D   Trigger an alert and show a label if the timeframe is incorrect
alert_message_time_wrong = "The current candle TIMEframe is WRONG: "+ str.tostring(timeframe.period) + ", CHANGE it to the CORRECT one:  1DAY !!"
if (str.tostring(timeframe.period) != "D")
    alert(alert_message_time_wrong, alert.freq_once_per_bar_close)
    label.new(bar_index -300, high+30, text = alert_message_time_wrong, style = label.style_label_down,size = size.large, color = color.red, textcolor = color.white)
    log.error(alert_message_time_wrong)

//CODE associated with the technical indicator L_Vortex_Indicator 
//@version=5
//indicator title = "Vortex Indicator", shorttitle="VI", format=format.price, precision=4, timeframe="", timeframe_gaps=true)
period_ = input.int(14, title="Length", minval=2)
VMP = math.sum( math.abs( high - low[1]), period_ )

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
