//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: ADX_and_DI
// ID_model: DDOG_1Hour_1ADX_f8246c46 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_DDOG_1Hour_1ADX_f8246c46", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_DDOG_1Hour_f8246c46(dx, directionalMovementMinus, diPlus, smoothedDirectionalMovementMinus, trueRange, smoothedDirectionalMovementPlus, smoothedTrueRange, directionalMovementPlus, diMinus, adx)=>
	var float ret = 0  // # DecisionTreeRegressor(max_depth=6, max_features=0.7, min_samples_split=10,random_state=843828734)
	if( smoothedDirectionalMovementMinus <= 0.537919 )
		if( smoothedTrueRange <= 1.50348 )
			if( directionalMovementMinus <= 0.068431 )
				if( diPlus <= 30.0205 )
					if( adx <= 32.9307 )
						if( smoothedDirectionalMovementMinus <= 0.119609 )
							ret := 0.355372
						if( smoothedDirectionalMovementMinus > 0.119609 )
							ret := 0.058095
					if( adx > 32.9307 )
						if( trueRange <= 0.568426 )
							ret := -0.126538
						if( trueRange > 0.568426 )
							ret := 0.061763
				if( diPlus > 30.0205 )
					if( adx <= 56.1097 )
						if( smoothedTrueRange <= 0.675729 )
							ret := -0.332432
						if( smoothedTrueRange > 0.675729 )
							ret := -0.072857
					if( adx > 56.1097 )
						if( diPlus <= 36.7509 )
							ret := -0.246269
						if( diPlus > 36.7509 )
							ret := 0.236364
			if( directionalMovementMinus > 0.068431 )
				if( diMinus <= 40.0553 )
					if( directionalMovementPlus <= 0.580243 )
						if( smoothedTrueRange <= 0.587625 )
							ret := -0.135338
						if( smoothedTrueRange > 0.587625 )
							ret := 0.169051
					if( directionalMovementPlus > 0.580243 )
						if( smoothedDirectionalMovementMinus <= 0.370647 )
							ret := -0.314286
						if( smoothedDirectionalMovementMinus > 0.370647 )
							ret := 0.365854
				if( diMinus > 40.0553 )
					if( dx <= 33.4718 )
						if( smoothedDirectionalMovementMinus <= 0.369239 )
							ret := -0.133333
						if( smoothedDirectionalMovementMinus > 0.369239 )
							ret := -0.777778 // sell
					if( dx > 33.4718 )
						if( diPlus <= 16.6298 )
							ret := -0.065836
						if( diPlus > 16.6298 )
							ret := 0.481013

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
