//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: ADX_and_DI
// ID_model: DDOG_30Min_1ADX_50eade15 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_DDOG_30Min_1ADX_50eade15", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_DDOG_30Min_50eade15(dx, directionalMovementMinus, diPlus, smoothedDirectionalMovementMinus, trueRange, smoothedDirectionalMovementPlus, smoothedTrueRange, directionalMovementPlus, diMinus, adx)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=6, max_features=0.9,min_samples_leaf=7, random_state=843828734)
	if( directionalMovementPlus <= 0.192422 )
		if( smoothedDirectionalMovementMinus <= 0.543774 )
			if( smoothedTrueRange <= 3.2148 )
				if( adx <= 44.8325 )
					if( directionalMovementMinus <= 3.3017 )
						if( smoothedDirectionalMovementPlus <= 0.037515 )
							ret := 0.298883
						if( smoothedDirectionalMovementPlus > 0.037515 )
							ret := 0.044815
					if( directionalMovementMinus > 3.3017 )
						if( diPlus <= 21.885 )
							ret := -0.038462
						if( diPlus > 21.885 )
							ret := -0.875000 // sell
				if( adx > 44.8325 )
					if( diMinus <= 46.6355 )
						if( diMinus <= 9.25156 )
							ret := 0.073171
						if( diMinus > 9.25156 )
							ret := -0.093082
					if( diMinus > 46.6355 )
						if( smoothedTrueRange <= 0.922201 )
							ret := 0.143216
						if( smoothedTrueRange > 0.922201 )
							ret := 0.671875
			if( smoothedTrueRange > 3.2148 )
				if( trueRange <= 3.78091 )
					if( diMinus <= 7.6513 )
						ret := 0.800000 // buy
					if( diMinus > 7.6513 )
						ret := 1.000000 // buy
				if( trueRange > 3.78091 )
					ret := 0.300000
		if( smoothedDirectionalMovementMinus > 0.543774 )
			if( adx <= 51.2278 )
				if( directionalMovementMinus <= 1.72052 )
					if( diPlus <= 5.86683 )
						if( adx <= 29.8893 )
							ret := -0.384615
						if( adx > 29.8893 )
							ret := 0.683168
					if( diPlus > 5.86683 )
						if( diMinus <= 30.9531 )
							ret := 0.268041
						if( diMinus > 30.9531 )
							ret := -0.140933
				if( directionalMovementMinus > 1.72052 )
					if( smoothedTrueRange <= 1.74248 )

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
