//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: L_Bull_Bear_Power
// ID_model: DDOG_1Day_1B00_c86c7fcb Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_DDOG_1Day_1B00_c86c7fcb", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_DDOG_1Day_c86c7fcb(bearPower, bbm, bbp, bullPower, BBPower_Color)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=5,max_features=sqrt, max_leaf_nodes=12,min_samples_leaf=4, min_samples_split=5,random_state=843828734)
	if( bbp <= -11.7099 )
		if( bullPower <= -5.15883 )
			ret := 0.638095
		if( bullPower > -5.15883 )
			if( bullPower <= -3.34322 )
				if( bbm <= 5.70232 )
					ret := 0.676471
				if( bbm > 5.70232 )
					ret := -0.515152
			if( bullPower > -3.34322 )
				ret := -0.392857
	if( bbp > -11.7099 )
		if( bearPower <= -7.22275 )
			ret := -0.639344
		if( bearPower > -7.22275 )
			if( bbp <= -3.977 )
				if( bbp <= -10.2161 )
					ret := -0.357143
				if( bbp > -10.2161 )
					if( bearPower <= -4.78879 )
						ret := 0.489362
					if( bearPower > -4.78879 )
						ret := 0.092308
			if( bbp > -3.977 )
				if( bbm <= 1.85995 )
					if( bearPower <= -1.80791 )
						ret := -0.260870
					if( bearPower > -1.80791 )
						ret := 0.387500
				if( bbm > 1.85995 )
					if( bullPower <= 9.76913 )
						ret := -0.013575
					if( bullPower > 9.76913 )
						ret := -0.234375
	
    ret //return
// Define expected timeframe based on the selected interval: 1Day pine_value: D   Trigger an alert and show a label if the timeframe is incorrect
alert_message_time_wrong = "The current candle TIMEframe is WRONG: "+ str.tostring(timeframe.period) + ", CHANGE it to the CORRECT one:  1DAY !!"
if (str.tostring(timeframe.period) != "D")
    alert(alert_message_time_wrong, alert.freq_once_per_bar_close)
    label.new(bar_index -300, high+30, text = alert_message_time_wrong, style = label.style_label_down,size = size.large, color = color.red, textcolor = color.white)
    log.error(alert_message_time_wrong)

//CODE associated with the technical indicator L_Bull_Bear_Power 
//@version=5
//indicator "Bull Bear Power", shorttitle="BBP")
lengthInput = input.int(13, title="Length")
bullPower = high - ta.ema(close, lengthInput)

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
