//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: ADX_and_DI
// ID_model: FFIV_1Day_1ADX_e4d80ae0 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_FFIV_1Day_1ADX_e4d80ae0", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_FFIV_1Day_e4d80ae0(dx, directionalMovementMinus, diPlus, smoothedDirectionalMovementMinus, trueRange, smoothedDirectionalMovementPlus, smoothedTrueRange, directionalMovementPlus, diMinus, adx)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=5, max_features=0.65,min_samples_leaf=4, min_samples_split=5,random_state=843828734)
	if( smoothedDirectionalMovementMinus <= 2.05544 )
		if( diPlus <= 19.9695 )
			if( smoothedDirectionalMovementPlus <= 0.738307 )
				if( directionalMovementPlus <= 1.30191 )
					if( smoothedDirectionalMovementPlus <= 0.281188 )
						ret := -0.108434
					if( smoothedDirectionalMovementPlus > 0.281188 )
						ret := 0.275714
				if( directionalMovementPlus > 1.30191 )
					if( trueRange <= 3.59552 )
						ret := -0.559633
					if( trueRange > 3.59552 )
						ret := -0.050847
			if( smoothedDirectionalMovementPlus > 0.738307 )
				if( dx <= 17.5755 )
					if( adx <= 49.16 )
						ret := 0.210526
					if( adx > 49.16 )
						ret := -1.000000 // sell
				if( dx > 17.5755 )
					if( trueRange <= 8.775 )
						ret := 0.733813 // buy
					if( trueRange > 8.775 )
						ret := -0.428571
		if( diPlus > 19.9695 )
			if( smoothedDirectionalMovementPlus <= 1.33634 )
				if( smoothedDirectionalMovementPlus <= 0.594544 )
					if( smoothedDirectionalMovementMinus <= 0.294883 )
						ret := 0.591837
					if( smoothedDirectionalMovementMinus > 0.294883 )
						ret := 0.061947
				if( smoothedDirectionalMovementPlus > 0.594544 )
					if( smoothedTrueRange <= 4.71309 )
						ret := -0.131926
					if( smoothedTrueRange > 4.71309 )
						ret := -0.637931
			if( smoothedDirectionalMovementPlus > 1.33634 )
				if( smoothedDirectionalMovementPlus <= 2.68946 )
					if( diMinus <= 18.0435 )
						ret := 0.189944
					if( diMinus > 18.0435 )
						ret := 0.612069
				if( smoothedDirectionalMovementPlus > 2.68946 )
					if( diPlus <= 57.3678 )
						ret := -0.513514
					if( diPlus > 57.3678 )
						ret := -1.000000 // sell
	if( smoothedDirectionalMovementMinus > 2.05544 )

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
