//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: MACD_ULT_MTF
// ID_model: ETHUSDT_1Day_1MAC_b12d3ff9 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_ETHUSDT_1Day_1MAC_b12d3ff9", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_ETHUSDT_1Day_b12d3ff9(macd, macd_IsBelowInt, signal, histB_IsUpInt, macd_IsAboveInt, histB_IsDownInt, histA_IsUpInt, hist, histA_IsDownInt)=>
	var float ret = 0  // # DecisionTreeRegressor(max_depth=5, max_features=sqrt, max_leaf_nodes=12,min_samples_leaf=4, min_samples_split=5,random_state=843828734)
	if( macd <= 0.692198 )
		if( hist <= -22.4048 )
			ret := 0.167382
		if( hist > -22.4048 )
			if( hist <= -15.5141 )
				ret := -0.663717
			if( hist > -15.5141 )
				if( histA_IsUpInt <= 0.5 )
					if( macd <= -3.1952 )
						ret := -0.151251
					if( macd > -3.1952 )
						ret := -0.513369
				if( histA_IsUpInt > 0.5 )
					ret := 0.012320
	if( macd > 0.692198 )
		if( macd <= 5.82489 )
			if( hist <= -1.43487 )
				if( signal <= 7.18627 )
					ret := -0.324324
				if( signal > 7.18627 )
					ret := 0.436364
			if( hist > -1.43487 )
				if( hist <= 3.65919 )
					ret := 0.709845 // buy
				if( hist > 3.65919 )
					ret := -0.088235
		if( macd > 5.82489 )
			if( signal <= 276.909 )
				if( hist <= -6.57665 )
					ret := 0.225653
				if( hist > -6.57665 )
					ret := 0.028478
			if( signal > 276.909 )
				ret := -0.800000 // sell
	
    ret //return
// Define expected timeframe based on the selected interval: 1Day pine_value: D   Trigger an alert and show a label if the timeframe is incorrect
alert_message_time_wrong = "The current candle TIMEframe is WRONG: "+ str.tostring(timeframe.period) + ", CHANGE it to the CORRECT one:  1DAY !!"
if (str.tostring(timeframe.period) != "D")
    alert(alert_message_time_wrong, alert.freq_once_per_bar_close)
    label.new(bar_index -300, high+30, text = alert_message_time_wrong, style = label.style_label_down,size = size.large, color = color.red, textcolor = color.white)
    log.error(alert_message_time_wrong)

//CODE associated with the technical indicator MACD_ULT_MTF 
//@version=5
//indicator title="CM_MacD_Ult_MTF", shorttitle="CM_Ult_MacD_MTF", overlay=false)

source = close

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
