//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: ADX_and_DI
// ID_model: ETSY_1Hour_1ADX_3f6f0640 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_ETSY_1Hour_1ADX_3f6f0640", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_ETSY_1Hour_3f6f0640(dx, directionalMovementMinus, diPlus, smoothedDirectionalMovementMinus, trueRange, smoothedDirectionalMovementPlus, smoothedTrueRange, directionalMovementPlus, diMinus, adx)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=6, max_features=0.82,max_leaf_nodes=30, random_state=843828734)
	if( dx <= 4.16951 )
		if( smoothedDirectionalMovementPlus <= 0.246139 )
			if( adx <= 9.38357 )
				ret := -0.875000 // sell
			if( adx > 9.38357 )
				if( dx <= 0.07549 )
					ret := -0.894737 // sell
				if( dx > 0.07549 )
					ret := -0.005457
		if( smoothedDirectionalMovementPlus > 0.246139 )
			if( trueRange <= 3.3863 )
				if( adx <= 17.4985 )
					if( diMinus <= 24.5884 )
						ret := 0.387097
					if( diMinus > 24.5884 )
						if( diMinus <= 30.3701 )
							ret := -0.636364
						if( diMinus > 30.3701 )
							ret := 0.277778
				if( adx > 17.4985 )
					if( diPlus <= 32.5394 )
						ret := 0.513793
					if( diPlus > 32.5394 )
						ret := -0.571429
			if( trueRange > 3.3863 )
				ret := -0.170370
	if( dx > 4.16951 )
		if( smoothedDirectionalMovementPlus <= 0.130753 )
			if( diMinus <= 24.0066 )
				ret := 0.274510
			if( diMinus > 24.0066 )
				if( directionalMovementMinus <= 0.620524 )
					if( dx <= 95.8217 )
						if( adx <= 72.8852 )
							ret := -0.018913
						if( adx > 72.8852 )
							ret := 0.395973
					if( dx > 95.8217 )
						ret := -0.623377
				if( directionalMovementMinus > 0.620524 )
					if( diPlus <= 7.25322 )
						if( dx <= 85.7562 )
							ret := -0.199187
						if( dx > 85.7562 )
							ret := 0.433962
					if( diPlus > 7.25322 )
						if( dx <= 59.105 )
							ret := 0.284946

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
