//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: ADX_and_DI
// ID_model: HUBS_1Hour_1ADX_b464a63b Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_HUBS_1Hour_1ADX_b464a63b", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_HUBS_1Hour_b464a63b(dx, directionalMovementMinus, diPlus, smoothedDirectionalMovementMinus, trueRange, smoothedDirectionalMovementPlus, smoothedTrueRange, directionalMovementPlus, diMinus, adx)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=6, max_features=0.7,max_leaf_nodes=30, min_samples_leaf=7,random_state=843828734)
	if( smoothedDirectionalMovementPlus <= 3.50905 )
		if( smoothedTrueRange <= 6.66728 )
			if( adx <= 19.7585 )
				if( smoothedDirectionalMovementPlus <= 0.408545 )
					ret := 0.225664
				if( smoothedDirectionalMovementPlus > 0.408545 )
					if( smoothedTrueRange <= 2.96116 )
						if( adx <= 10.9479 )
							ret := 0.230769
						if( adx > 10.9479 )
							ret := -0.404762
					if( smoothedTrueRange > 2.96116 )
						if( trueRange <= 3.325 )
							ret := 0.129353
						if( trueRange > 3.325 )
							ret := -0.144022
			if( adx > 19.7585 )
				if( dx <= 15.0296 )
					if( dx <= 3.32339 )
						if( diMinus <= 30.932 )
							ret := 0.114428
						if( diMinus > 30.932 )
							ret := 0.658537
					if( dx > 3.32339 )
						if( trueRange <= 1.21775 )
							ret := 0.135802
						if( trueRange > 1.21775 )
							ret := -0.149265
				if( dx > 15.0296 )
					if( directionalMovementMinus <= 7.64729 )
						if( diMinus <= 44.1079 )
							ret := 0.076009
						if( diMinus > 44.1079 )
							ret := -0.083158
					if( directionalMovementMinus > 7.64729 )
						if( smoothedDirectionalMovementPlus <= 0.948071 )
							ret := 0.542857
						if( smoothedDirectionalMovementPlus > 0.948071 )
							ret := -0.017094
		if( smoothedTrueRange > 6.66728 )
			if( adx <= 17.0746 )
				if( diPlus <= 22.5259 )
					ret := 0.620968
				if( diPlus > 22.5259 )
					if( trueRange <= 5.25629 )
						ret := 0.560976
					if( trueRange > 5.25629 )
						ret := -0.250000

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
