//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: L_Triple_EMA
// ID_model: NIO_1Day_1T00_61486a53 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_NIO_1Day_1T00_61486a53", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_NIO_1Day_61486a53(ema12, ema3, ema13, tema, ema1, ema2)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=5, max_features=0.9,max_leaf_nodes=30, min_samples_leaf=4,min_samples_split=5, random_state=843828734)
	if( ema3 <= 3.00939 )
		if( tema <= 3.71105 )
			if( ema13 <= -0.327885 )
				if( ema2 <= 2.30307 )
					ret := 0.000000
				if( ema2 > 2.30307 )
					ret := -0.166667
			if( ema13 > -0.327885 )
				if( ema12 <= 0.062393 )
					if( ema12 <= -0.125471 )
						ret := 0.666667
					if( ema12 > -0.125471 )
						ret := 0.966292 // buy
				if( ema12 > 0.062393 )
					if( ema13 <= 0.458346 )
						ret := 0.175439
					if( ema13 > 0.458346 )
						ret := 1.000000 // buy
		if( tema > 3.71105 )
			ret := -0.888889 // sell
	if( ema3 > 3.00939 )
		if( ema13 <= -0.065869 )
			if( ema2 <= 4.7905 )
				if( ema3 <= 3.03836 )
					ret := 1.000000 // buy
				if( ema3 > 3.03836 )
					if( ema12 <= -0.136952 )
						ret := -0.733766 // sell
					if( ema12 > -0.136952 )
						ret := -0.234568
			if( ema2 > 4.7905 )
				if( ema3 <= 7.17942 )
					if( ema1 <= 5.62078 )
						ret := -0.022727
					if( ema1 > 5.62078 )
						ret := 0.425926
				if( ema3 > 7.17942 )
					if( ema2 <= 7.39635 )
						ret := -0.830189 // sell
					if( ema2 > 7.39635 )
						ret := -0.141141
		if( ema13 > -0.065869 )
			if( ema2 <= 3.10918 )
				ret := -1.000000 // sell
			if( ema2 > 3.10918 )
				if( ema2 <= 4.03375 )
					if( ema13 <= 0.754399 )
						ret := 0.818182 // buy

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
