//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: Bollinger_RSI_Double_Strategy
// ID_model: NIO_1Day_1BOL_eb5904d1 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_NIO_1Day_1BOL_eb5904d1", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_NIO_1Day_eb5904d1(crossunder_rsi_bbupperInt, BBlower, dif_source_BBupper, crossover_rsi_bblowerInt, vrsi, BBupper, dif_source_BBlower)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=5, max_features=0.82,max_leaf_nodes=30, random_state=843828734)
	if( dif_source_BBupper <= -4.48913 )
		if( dif_source_BBupper <= -32.212 )
			if( dif_source_BBupper <= -33.8888 )
				if( BBlower <= 19.9023 )
					if( BBupper <= 48.9205 )
						ret := 0.800000 // buy
					if( BBupper > 48.9205 )
						ret := 1.000000 // buy
				if( BBlower > 19.9023 )
					ret := 0.000000
			if( dif_source_BBupper > -33.8888 )
				if( BBlower <= 12.9126 )
					if( dif_source_BBlower <= 4.19209 )
						ret := 1.000000 // buy
					if( dif_source_BBlower > 4.19209 )
						ret := 0.600000
				if( BBlower > 12.9126 )
					if( BBlower <= 14.157 )
						ret := -1.000000 // sell
					if( BBlower > 14.157 )
						ret := 0.538462
		if( dif_source_BBupper > -32.212 )
			if( dif_source_BBlower <= 42.6621 )
				if( BBlower <= 11.6835 )
					if( BBupper <= 14.8238 )
						ret := -0.195652
					if( BBupper > 14.8238 )
						ret := 0.185930
				if( BBlower > 11.6835 )
					if( dif_source_BBlower <= 6.98587 )
						ret := -0.621495
					if( dif_source_BBlower > 6.98587 )
						ret := -0.090226
			if( dif_source_BBlower > 42.6621 )
				if( BBlower <= -11.9211 )
					if( BBupper <= 55.3092 )
						ret := 1.000000 // buy
					if( BBupper > 55.3092 )
						ret := 0.000000
				if( BBlower > -11.9211 )
					if( vrsi <= 6.92092 )
						ret := 0.000000
					if( vrsi > 6.92092 )
						ret := -0.819444 // sell
	if( dif_source_BBupper > -4.48913 )
		if( BBlower <= 0.944078 )
			if( vrsi <= 51.1502 )
				if( dif_source_BBupper <= 1.7149 )

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
