//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: L_Bollinger_Bands, L_Bull_Bear_Power
// ID_model: NIO_1Day_2BB0_ba799c0a Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_NIO_1Day_2BB0_ba799c0a", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_NIO_1Day_ba799c0a(basis, Upper_Band, Lower_Band, bearPower, bbm, bbp, bullPower, BBPower_Color)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=5, max_features=0.9,max_leaf_nodes=12, min_samples_split=5,random_state=843828734)
	if( basis <= 3.75992 )
		if( bullPower <= 0.604674 )
			if( basis <= 2.95662 )
				ret := 0.660714
			if( basis > 2.95662 )
				ret := 0.219858
		if( bullPower > 0.604674 )
			ret := -0.727273 // sell
	if( basis > 3.75992 )
		if( bearPower <= 0.041985 )
			if( Upper_Band <= 6.22148 )
				if( bbm <= 0.180771 )
					ret := 0.361702
				if( bbm > 0.180771 )
					if( Upper_Band <= 4.3959 )
						ret := 1.000000 // buy
					if( Upper_Band > 4.3959 )
						ret := -0.600840
			if( Upper_Band > 6.22148 )
				if( basis <= 20.1187 )
					if( bbm <= 1.25311 )
						ret := -0.014684
					if( bbm > 1.25311 )
						ret := 0.705128 // buy
				if( basis > 20.1187 )
					if( bearPower <= -4.75851 )
						ret := 0.473684
					if( bearPower > -4.75851 )
						ret := -0.468750
		if( bearPower > 0.041985 )
			if( Upper_Band <= 5.2553 )
				ret := 0.852941 // buy
			if( Upper_Band > 5.2553 )
				ret := 0.084362
	
    ret //return
// Define expected timeframe based on the selected interval: 1Day pine_value: D   Trigger an alert and show a label if the timeframe is incorrect
alert_message_time_wrong = "The current candle TIMEframe is WRONG: "+ str.tostring(timeframe.period) + ", CHANGE it to the CORRECT one:  1DAY !!"
if (str.tostring(timeframe.period) != "D")
    alert(alert_message_time_wrong, alert.freq_once_per_bar_close)
    label.new(bar_index -300, high+30, text = alert_message_time_wrong, style = label.style_label_down,size = size.large, color = color.red, textcolor = color.white)
    log.error(alert_message_time_wrong)

//CODE associated with the technical indicator L_Bollinger_Bands 
//@version=5
//indicator shorttitle="BB", title="Bollinger Bands", overlay=true, timeframe="", timeframe_gaps=true)
length_BB = input.int(20, minval=1)
maType = input.string("SMA", "Basis MA Type", options = ["SMA", "EMA", "SMMA (RMA)", "WMA", "VWMA"])

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
