//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: MACD_ULT_MTF
// ID_model: NIO_1Hour_1MAC_9b05abdf Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_NIO_1Hour_1MAC_9b05abdf", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_NIO_1Hour_9b05abdf(macd, macd_IsBelowInt, signal, histB_IsUpInt, macd_IsAboveInt, histB_IsDownInt, histA_IsUpInt, hist, histA_IsDownInt)=>
	var float ret = 0  // # DecisionTreeRegressor(max_depth=6, max_features=0.7, min_samples_split=10,random_state=843828734)
	if( macd <= 0.013266 )
		if( macd <= -1.23485 )
			if( signal <= -1.06861 )
				if( hist <= -0.392205 )
					ret := 0.125000
				if( hist > -0.392205 )
					if( macd <= -1.30613 )
						if( macd <= -1.38832 )
							ret := 0.954545 // buy
						if( macd > -1.38832 )
							ret := 0.750000 // buy
					if( macd > -1.30613 )
						if( signal <= -1.1014 )
							ret := 0.181818
						if( signal > -1.1014 )
							ret := -1.000000 // sell
			if( signal > -1.06861 )
				if( hist <= -0.350803 )
					if( hist <= -0.408358 )
						if( macd <= -1.41057 )
							ret := -1.000000 // sell
						if( macd > -1.41057 )
							ret := -0.250000
					if( hist > -0.408358 )
						ret := 0.000000
				if( hist > -0.350803 )
					ret := 1.000000 // buy
		if( macd > -1.23485 )
			if( histA_IsDownInt <= 0.5 )
				if( hist <= -0.002746 )
					if( signal <= -0.935506 )
						if( histB_IsDownInt <= 0.5 )
							ret := 0.538462
						if( histB_IsDownInt > 0.5 )
							ret := 1.000000 // buy
					if( signal > -0.935506 )
						if( signal <= -0.725014 )
							ret := -0.559633
						if( signal > -0.725014 )
							ret := -0.022949
				if( hist > -0.002746 )
					if( hist <= 0.142742 )
						if( signal <= -0.50735 )
							ret := 0.111554
						if( signal > -0.50735 )
							ret := -0.184100
					if( hist > 0.142742 )
						if( signal <= -1.09306 )

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
