//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: ADX_and_DI
// ID_model: NIO_1Day_1ADX_091b4c9e Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_NIO_1Day_1ADX_091b4c9e", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_NIO_1Day_091b4c9e(dx, directionalMovementMinus, diPlus, smoothedDirectionalMovementMinus, trueRange, smoothedDirectionalMovementPlus, smoothedTrueRange, directionalMovementPlus, diMinus, adx)=>
	var float ret = 0  // # DecisionTreeRegressor(max_depth=5, max_features=0.82, min_samples_leaf=7,min_samples_split=5, random_state=843828734)
	if( smoothedDirectionalMovementMinus <= 0.111636 )
		if( dx <= 45.5064 )
			if( smoothedDirectionalMovementPlus <= 0.0575 )
				if( adx <= 16.9386 )
					if( diPlus <= 25.7658 )
						ret := -0.625000
					if( diPlus > 25.7658 )
						ret := -0.071429
				if( adx > 16.9386 )
					if( smoothedDirectionalMovementPlus <= 0.039017 )
						ret := 0.043956
					if( smoothedDirectionalMovementPlus > 0.039017 )
						ret := 0.447059
			if( smoothedDirectionalMovementPlus > 0.0575 )
				if( adx <= 22.5354 )
					if( adx <= 20.2628 )
						ret := 0.518519
					if( adx > 20.2628 )
						ret := -0.310345
				if( adx > 22.5354 )
					if( dx <= 38.6526 )
						ret := 0.514423
					if( dx > 38.6526 )
						ret := 0.847059 // buy
		if( dx > 45.5064 )
			if( directionalMovementPlus <= 0.781875 )
				if( diPlus <= 49.312 )
					if( adx <= 48.9072 )
						ret := -0.425000
					if( adx > 48.9072 )
						ret := 0.083333
				if( diPlus > 49.312 )
					if( dx <= 69.1996 )
						ret := 1.000000 // buy
					if( dx > 69.1996 )
						ret := 0.000000
			if( directionalMovementPlus > 0.781875 )
				if( adx <= 45.1855 )
					ret := 0.461538
				if( adx > 45.1855 )
					ret := 0.900000 // buy
	if( smoothedDirectionalMovementMinus > 0.111636 )
		if( dx <= 36.8786 )
			if( adx <= 51.9692 )
				if( directionalMovementPlus <= 0.595 )
					if( diPlus <= 26.5925 )
						ret := -0.262467
					if( diPlus > 26.5925 )

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
