//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: Candlestick_Patterns
// ID_model: NVDA_1Day_1CAN_31847b8e Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_NVDA_1Day_1CAN_31847b8e", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_NVDA_1Day_31847b8e(Bullish_EngulfingInt, HammerInt, Evening_StarInt, Dark_Cloud_CoverInt, DojiInt, Morning_StarInt, Bearish_HaramiInt, Bullish_HaramiInt, Bullish_BeltInt, Hanging_ManInt, Bearish_EngulfingInt, Bearish_KickerInt, Piercing_LineInt, Bullish_KickerInt, Shooting_StarInt, Inverted_HammerInt)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=5, max_features=0.4,max_leaf_nodes=30, min_samples_leaf=4,random_state=843828734)
	if( Bearish_EngulfingInt <= 0.5 )
		if( Inverted_HammerInt <= 0.5 )
			if( Dark_Cloud_CoverInt <= 0.5 )
				if( Hanging_ManInt <= 0.5 )
					if( Evening_StarInt <= 0.5 )
						ret := 0.014487
					if( Evening_StarInt > 0.5 )
						ret := -0.428571
				if( Hanging_ManInt > 0.5 )
					ret := 0.111111
			if( Dark_Cloud_CoverInt > 0.5 )
				ret := 0.720000 // buy
		if( Inverted_HammerInt > 0.5 )
			if( DojiInt <= 0.5 )
				if( Bearish_HaramiInt <= 0.5 )
					if( Shooting_StarInt <= 0.5 )
						ret := 0.490385
					if( Shooting_StarInt > 0.5 )
						ret := 0.523810
				if( Bearish_HaramiInt > 0.5 )
					ret := 0.250000
			if( DojiInt > 0.5 )
				if( Bearish_HaramiInt <= 0.5 )
					ret := 0.000000
				if( Bearish_HaramiInt > 0.5 )
					ret := 0.250000
	if( Bearish_EngulfingInt > 0.5 )
		ret := 0.481481
	
    ret //return
// Define expected timeframe based on the selected interval: 1Day pine_value: D   Trigger an alert and show a label if the timeframe is incorrect
alert_message_time_wrong = "The current candle TIMEframe is WRONG: "+ str.tostring(timeframe.period) + ", CHANGE it to the CORRECT one:  1DAY !!"
if (str.tostring(timeframe.period) != "D")
    alert(alert_message_time_wrong, alert.freq_once_per_bar_close)
    label.new(bar_index -300, high+30, text = alert_message_time_wrong, style = label.style_label_down,size = size.large, color = color.red, textcolor = color.white)
    log.error(alert_message_time_wrong)

//CODE associated with the technical indicator Candlestick_Patterns 
//@version=5
//indicator title="Candles", overlay=true)

DojiSize = input.float(0.05, minval=0.01, title="Doji size")
Doji = math.abs(open - close) <= (high - low) * DojiSize
plotshape(Doji, title="Doji", color=color.white, text='Doji', style=shape.labeldown)

Evening_Star = close[2] > open[2] and math.min(open[1], close[1]) > close[2] and open < math.min(open[1], close[1]) and close < open
plotshape(Evening_Star, title="Evening_Star", color=color.red, style=shape.arrowdown, text="Evening\nStar")


	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
