//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: SuperTrend
// ID_model: NVST_1Day_1SUP_01d73985 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_NVST_1Day_1SUP_01d73985", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_NVST_1Day_01d73985(dn1, trend, atr, atr2, buySignalInt, sellSignalInt, up1, up, dn)=>
	var float ret = 0  // # DecisionTreeRegressor(max_depth=5, max_features=0.6, min_samples_leaf=4,min_samples_split=5, random_state=843828734)
	if( up1 <= 14.4948 )
		if( dn1 <= 22.2088 )
			if( atr2 <= 1.53779 )
				if( up <= 14.4755 )
					if( up <= 12.7921 )
						ret := 0.814815 // buy
					if( up > 12.7921 )
						ret := 0.947368 // buy
				if( up > 14.4755 )
					if( dn1 <= 18.8718 )
						ret := 0.000000
					if( dn1 > 18.8718 )
						ret := 0.750000 // buy
			if( atr2 > 1.53779 )
				if( atr <= 1.54152 )
					ret := -0.800000 // sell
				if( atr > 1.54152 )
					if( dn <= 19.2869 )
						ret := 1.000000 // buy
					if( dn > 19.2869 )
						ret := 0.222222
		if( dn1 > 22.2088 )
			if( atr2 <= 1.60872 )
				ret := 0.400000
			if( atr2 > 1.60872 )
				ret := -1.000000 // sell
	if( up1 > 14.4948 )
		if( atr2 <= 0.86727 )
			if( atr <= 0.755343 )
				if( atr2 <= 0.684865 )
					if( dn1 <= 22.7745 )
						ret := -0.516667
					if( dn1 > 22.7745 )
						ret := -0.153846
				if( atr2 > 0.684865 )
					if( dn <= 25.3942 )
						ret := 0.428571
					if( dn > 25.3942 )
						ret := -0.043478
			if( atr > 0.755343 )
				if( up1 <= 30.6914 )
					if( dn1 <= 27.4869 )
						ret := -0.275862
					if( dn1 > 27.4869 )
						ret := -0.701031 // sell
				if( up1 > 30.6914 )
					if( atr <= 0.899504 )
						ret := -0.258065

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
