//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: ADX_and_DI
// ID_model: MDB_1Hour_1ADX_8b618d0c Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_MDB_1Hour_1ADX_8b618d0c", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_MDB_1Hour_8b618d0c(dx, directionalMovementMinus, diPlus, smoothedDirectionalMovementMinus, trueRange, smoothedDirectionalMovementPlus, smoothedTrueRange, directionalMovementPlus, diMinus, adx)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=6, max_features=0.7,max_leaf_nodes=30, min_samples_leaf=7,random_state=843828734)
	if( smoothedDirectionalMovementPlus <= 4.22622 )
		if( directionalMovementPlus <= 0.13528 )
			if( diPlus <= 26.8353 )
				if( smoothedDirectionalMovementPlus <= 1.17694 )
					if( smoothedDirectionalMovementMinus <= 4.31135 )
						if( trueRange <= 1.53895 )
							ret := -0.064394
						if( trueRange > 1.53895 )
							ret := 0.073031
					if( smoothedDirectionalMovementMinus > 4.31135 )
						if( diMinus <= 62.419 )
							ret := -0.603960
						if( diMinus > 62.419 )
							ret := 0.476190
				if( smoothedDirectionalMovementPlus > 1.17694 )
					if( trueRange <= 13.1491 )
						ret := -0.161468
					if( trueRange > 13.1491 )
						ret := -0.752475 // sell
			if( diPlus > 26.8353 )
				if( smoothedDirectionalMovementPlus <= 0.590794 )
					if( diPlus <= 44.4585 )
						if( adx <= 20.7425 )
							ret := 0.015152
						if( adx > 20.7425 )
							ret := 0.417219
					if( diPlus > 44.4585 )
						ret := -0.588235
				if( smoothedDirectionalMovementPlus > 0.590794 )
					if( smoothedTrueRange <= 3.10357 )
						if( diMinus <= 21.6481 )
							ret := 0.062447
						if( diMinus > 21.6481 )
							ret := -0.232941
					if( smoothedTrueRange > 3.10357 )
						if( dx <= 2.06582 )
							ret := 0.709302 // buy
						if( dx > 2.06582 )
							ret := 0.106613
		if( directionalMovementPlus > 0.13528 )
			if( smoothedDirectionalMovementPlus <= 0.885328 )
				if( dx <= 10.9515 )
					if( diMinus <= 22.1949 )
						if( adx <= 22.9617 )
							ret := -0.493333
						if( adx > 22.9617 )
							ret := 0.209150
					if( diMinus > 22.1949 )

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
