//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: Bollinger_RSI_Double_Strategy
// ID_model: MDB_30Min_1BOL_c0a346a9 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_MDB_30Min_1BOL_c0a346a9", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_MDB_30Min_c0a346a9(crossunder_rsi_bbupperInt, BBlower, dif_source_BBupper, crossover_rsi_bblowerInt, vrsi, BBupper, dif_source_BBlower)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=6, max_features=0.9,min_samples_leaf=7, random_state=843828734)
	if( BBlower <= 362.81 )
		if( BBlower <= 70.8001 )
			if( dif_source_BBlower <= 16.633 )
				if( dif_source_BBlower <= 1.75142 )
					if( BBlower <= 25.3653 )
						if( BBupper <= 29.3762 )
							ret := 0.727273 // buy
						if( BBupper > 29.3762 )
							ret := 1.000000 // buy
					if( BBlower > 25.3653 )
						if( vrsi <= 3.72967 )
							ret := 0.507937
						if( vrsi > 3.72967 )
							ret := -0.163280
				if( dif_source_BBlower > 1.75142 )
					if( dif_source_BBupper <= -13.2099 )
						if( dif_source_BBlower <= 3.36178 )
							ret := 0.073529
						if( dif_source_BBlower > 3.36178 )
							ret := 0.687500
					if( dif_source_BBupper > -13.2099 )
						if( vrsi <= 62.0001 )
							ret := 0.255039
						if( vrsi > 62.0001 )
							ret := 0.073593
			if( dif_source_BBlower > 16.633 )
				if( BBupper <= 88.8347 )
					if( dif_source_BBupper <= 0.109652 )
						if( BBupper <= 83.0776 )
							ret := -0.095238
						if( BBupper > 83.0776 )
							ret := -0.919192 // sell
					if( dif_source_BBupper > 0.109652 )
						if( BBlower <= 62.9761 )
							ret := -1.000000 // sell
						if( BBlower > 62.9761 )
							ret := -0.139535
				if( BBupper > 88.8347 )
					if( dif_source_BBlower <= 18.6446 )
						if( BBlower <= 69.6778 )
							ret := -0.400000
						if( BBlower > 69.6778 )
							ret := 0.586207
					if( dif_source_BBlower > 18.6446 )
						if( BBlower <= 69.7913 )
							ret := 0.000000
						if( BBlower > 69.7913 )
							ret := -0.772727 // sell

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
