//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: Ichimoku_Cloud
// ID_model: MELI_1Day_1ICH_6dca67b2 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_MELI_1Day_1ICH_6dca67b2", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_MELI_1Day_6dca67b2(senkou_span_a, basis_minus, chinkou_span, senkou_span_a_displaced, kinjun_sen, senkou_span_b_displaced, cross_up_tenkan_kinjunInt, senkou_span_b, cross_dn_tenkan_kinjunInt, tenkan_sen, basis_max)=>
	var float ret = 0  // # DecisionTreeRegressor(max_depth=5, max_features=0.9, random_state=843828734)
	if( senkou_span_b <= 1576.87 )
		if( kinjun_sen <= 1267.54 )
			if( senkou_span_b <= 325.296 )
				if( senkou_span_a_displaced <= 271.539 )
					if( kinjun_sen <= 161.881 )
						ret := 0.423423
					if( kinjun_sen > 161.881 )
						ret := -0.120735
				if( senkou_span_a_displaced > 271.539 )
					if( senkou_span_b_displaced <= 327.626 )
						ret := 0.897260 // buy
					if( senkou_span_b_displaced > 327.626 )
						ret := 0.278689
			if( senkou_span_b > 325.296 )
				if( kinjun_sen <= 354.602 )
					if( senkou_span_a <= 316.56 )
						ret := 0.659091
					if( senkou_span_a > 316.56 )
						ret := -0.800885 // sell
				if( kinjun_sen > 354.602 )
					if( senkou_span_a <= 885.583 )
						ret := 0.211618
					if( senkou_span_a > 885.583 )
						ret := -0.178261
		if( kinjun_sen > 1267.54 )
			if( basis_max <= -20.8429 )
				if( chinkou_span <= 1360.99 )
					if( kinjun_sen <= 1313.7 )
						ret := -1.000000 // sell
					if( kinjun_sen > 1313.7 )
						ret := -0.500000
				if( chinkou_span > 1360.99 )
					if( kinjun_sen <= 1350.34 )
						ret := 0.800000 // buy
					if( kinjun_sen > 1350.34 )
						ret := 0.041667
			if( basis_max > -20.8429 )
				if( chinkou_span <= 1559.32 )
					if( tenkan_sen <= 1361.79 )
						ret := 0.375000
					if( tenkan_sen > 1361.79 )
						ret := -0.538462
				if( chinkou_span > 1559.32 )
					if( kinjun_sen <= 1668.42 )
						ret := 0.858696 // buy
					if( kinjun_sen > 1668.42 )
						ret := 0.071429
	if( senkou_span_b > 1576.87 )

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
