//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: Madrid_Moving_Average_Ribbon
// ID_model: MELI_1Hour_1MAD_a91c22fa Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_MELI_1Hour_1MAD_a91c22fa", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_MELI_1Hour_a91c22fa(ma15, ma70_colorInt, ma75_colorInt, ma70, ma40_colorInt, ma80_colorInt, ma20, ma20_colorInt, ma60, ma50, ma65_colorInt, ma45, ma55, ma05_colorInt, ma35_colorInt, ma10_colorInt, ma30, ma25_colorInt, ma100, ma65, ma85, ma80, ma60_colorInt, ma85_colorInt, ma90, ma90_colorInt, ma25, ma40, ma50_colorInt, ma35, ma30_colorInt, ma45_colorInt, ma05, ma75, ma55_colorInt, ma10, ma15_colorInt)=>
	var float ret = 0  // # DecisionTreeRegressor(max_depth=6, max_features=0.7, min_samples_split=10,random_state=843828734)
	if( ma70 <= 881.745 )
		if( ma100 <= 303.138 )
			if( ma05_colorInt <= 3.5 )
				if( ma80 <= 301.197 )
					ret := 1.000000 // buy
				if( ma80 > 301.197 )
					if( ma75 <= 300.944 )
						ret := 0.000000
					if( ma75 > 300.944 )
						ret := 1.000000 // buy
			if( ma05_colorInt > 3.5 )
				if( ma55 <= 294.199 )
					ret := 0.000000
				if( ma55 > 294.199 )
					ret := 0.833333 // buy
		if( ma100 > 303.138 )
			if( ma75 <= 841.755 )
				if( ma60_colorInt <= 3.5 )
					if( ma15 <= 320.94 )
						if( ma20 <= 288 )
							ret := 0.714286 // buy
						if( ma20 > 288 )
							ret := -0.429907
					if( ma15 > 320.94 )
						if( ma20 <= 327.39 )
							ret := 0.829787 // buy
						if( ma20 > 327.39 )
							ret := 0.068972
				if( ma60_colorInt > 3.5 )
					if( ma20 <= 786.31 )
						if( ma35 <= 643.489 )
							ret := -0.193548
						if( ma35 > 643.489 )
							ret := 0.349515
					if( ma20 > 786.31 )
						if( ma90 <= 837.773 )
							ret := -0.867769 // sell
						if( ma90 > 837.773 )
							ret := -0.254237
			if( ma75 > 841.755 )
				if( ma05_colorInt <= 3.5 )
					if( ma45 <= 873.565 )
						if( ma100 <= 899.944 )
							ret := 0.626598
						if( ma100 > 899.944 )
							ret := -1.000000 // sell
					if( ma45 > 873.565 )
						if( ma60 <= 880.294 )

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
