//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: ADX_and_DI
// ID_model: MELI_5Min_1ADX_99a946a5 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_MELI_5Min_1ADX_99a946a5", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_MELI_5Min_99a946a5(dx, directionalMovementMinus, diPlus, smoothedDirectionalMovementMinus, trueRange, smoothedDirectionalMovementPlus, smoothedTrueRange, directionalMovementPlus, diMinus, adx)=>
	var float ret = 0  // # DecisionTreeRegressor(max_depth=6, max_features=0.7, min_samples_split=10,random_state=843828734)
	if( adx <= 56.6997 )
		if( smoothedTrueRange <= 8.79575 )
			if( smoothedTrueRange <= 3.30922 )
				if( diMinus <= 52.1668 )
					if( smoothedDirectionalMovementMinus <= 0.468508 )
						if( smoothedTrueRange <= 2.86432 )
							ret := -0.082035
						if( smoothedTrueRange > 2.86432 )
							ret := 0.156118
					if( smoothedDirectionalMovementMinus > 0.468508 )
						if( dx <= 1.48798 )
							ret := 0.263158
						if( dx > 1.48798 )
							ret := 0.042495
				if( diMinus > 52.1668 )
					if( smoothedDirectionalMovementPlus <= 0.188017 )
						if( smoothedTrueRange <= 1.95611 )
							ret := 0.204545
						if( smoothedTrueRange > 1.95611 )
							ret := 0.701754 // buy
					if( smoothedDirectionalMovementPlus > 0.188017 )
						if( trueRange <= 2.66034 )
							ret := 0.329545
						if( trueRange > 2.66034 )
							ret := -0.052219
			if( smoothedTrueRange > 3.30922 )
				if( diPlus <= 23.2066 )
					if( smoothedDirectionalMovementPlus <= 0.967944 )
						if( directionalMovementMinus <= 21.0684 )
							ret := -0.054276
						if( directionalMovementMinus > 21.0684 )
							ret := 0.690476
					if( smoothedDirectionalMovementPlus > 0.967944 )
						if( dx <= 52.1169 )
							ret := -0.256022
						if( dx > 52.1169 )
							ret := 0.473684
				if( diPlus > 23.2066 )
					if( smoothedDirectionalMovementMinus <= 0.155282 )
						if( trueRange <= 19.544 )
							ret := -0.592000
						if( trueRange > 19.544 )
							ret := 1.000000 // buy
					if( smoothedDirectionalMovementMinus > 0.155282 )
						if( diMinus <= 40.8285 )
							ret := -0.004902
						if( diMinus > 40.8285 )
							ret := 0.209730

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
