//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: ADX_and_DI
// ID_model: MELI_1Day_1ADX_c13e4eb4 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_MELI_1Day_1ADX_c13e4eb4", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_MELI_1Day_c13e4eb4(dx, directionalMovementMinus, diPlus, smoothedDirectionalMovementMinus, trueRange, smoothedDirectionalMovementPlus, smoothedTrueRange, directionalMovementPlus, diMinus, adx)=>
	var float ret = 0  // # DecisionTreeRegressor(max_depth=5, max_features=0.5, min_samples_leaf=7,min_samples_split=10, random_state=843828734)
	if( diPlus <= 22.8078 )
		if( diMinus <= 19.6827 )
			if( smoothedDirectionalMovementPlus <= 12.1867 )
				if( diPlus <= 17.2259 )
					if( smoothedDirectionalMovementPlus <= 8.29306 )
						ret := -0.342466
					if( smoothedDirectionalMovementPlus > 8.29306 )
						ret := -0.933333 // sell
				if( diPlus > 17.2259 )
					if( smoothedTrueRange <= 47.8137 )
						ret := 0.149606
					if( smoothedTrueRange > 47.8137 )
						ret := -0.636364
			if( smoothedDirectionalMovementPlus > 12.1867 )
				ret := 0.636364
		if( diMinus > 19.6827 )
			if( dx <= 13.1928 )
				if( directionalMovementMinus <= 0.254051 )
					if( smoothedTrueRange <= 47.4079 )
						ret := 0.620253
					if( smoothedTrueRange > 47.4079 )
						ret := -0.241379
				if( directionalMovementMinus > 0.254051 )
					if( smoothedDirectionalMovementPlus <= 1.94464 )
						ret := -0.111111
					if( smoothedDirectionalMovementPlus > 1.94464 )
						ret := 0.870000 // buy
			if( dx > 13.1928 )
				if( smoothedDirectionalMovementMinus <= 25.5329 )
					if( smoothedDirectionalMovementMinus <= 21.8384 )
						ret := 0.146884
					if( smoothedDirectionalMovementMinus > 21.8384 )
						ret := 0.728814 // buy
				if( smoothedDirectionalMovementMinus > 25.5329 )
					if( dx <= 71.1504 )
						ret := -0.358696
					if( dx > 71.1504 )
						ret := 0.523810
	if( diPlus > 22.8078 )
		if( smoothedTrueRange <= 50.4609 )
			if( smoothedDirectionalMovementPlus <= 0.658071 )
				ret := 1.000000 // buy
			if( smoothedDirectionalMovementPlus > 0.658071 )
				if( directionalMovementPlus <= 7.34664 )
					if( trueRange <= 7.5145 )
						ret := 0.183036
					if( trueRange > 7.5145 )
						ret := -0.166031

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
