//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: Madrid_Moving_Average_Ribbon
// ID_model: MELI_1Day_1MAD_a6a1d417 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_MELI_1Day_1MAD_a6a1d417", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_MELI_1Day_a6a1d417(ma15, ma70_colorInt, ma75_colorInt, ma70, ma40_colorInt, ma80_colorInt, ma20, ma20_colorInt, ma60, ma50, ma65_colorInt, ma45, ma55, ma05_colorInt, ma35_colorInt, ma10_colorInt, ma30, ma25_colorInt, ma100, ma65, ma85, ma80, ma60_colorInt, ma85_colorInt, ma90, ma90_colorInt, ma25, ma40, ma50_colorInt, ma35, ma30_colorInt, ma45_colorInt, ma05, ma75, ma55_colorInt, ma10, ma15_colorInt)=>
	var float ret = 0  // # DecisionTreeRegressor(max_depth=5, max_features=0.9, random_state=843828734)
	if( ma90 <= 1623.63 )
		if( ma100 <= 889.046 )
			if( ma25_colorInt <= 2.5 )
				if( ma35 <= 761.742 )
					if( ma25 <= 268.594 )
						ret := 0.235135
					if( ma25 > 268.594 )
						ret := -0.191041
				if( ma35 > 761.742 )
					if( ma05 <= 1155.22 )
						ret := 0.731707 // buy
					if( ma05 > 1155.22 )
						ret := -1.000000 // sell
			if( ma25_colorInt > 2.5 )
				if( ma10 <= 156.261 )
					if( ma25 <= 98.6863 )
						ret := 0.920000 // buy
					if( ma25 > 98.6863 )
						ret := -0.615385
				if( ma10 > 156.261 )
					if( ma90_colorInt <= 2.5 )
						ret := 0.388889
					if( ma90_colorInt > 2.5 )
						ret := 0.738971 // buy
		if( ma100 > 889.046 )
			if( ma90_colorInt <= 2.5 )
				if( ma10 <= 1133.37 )
					if( ma20 <= 1069.45 )
						ret := 0.621622
					if( ma20 > 1069.45 )
						ret := 0.944444 // buy
				if( ma10 > 1133.37 )
					if( ma70 <= 1073.79 )
						ret := -0.676056
					if( ma70 > 1073.79 )
						ret := 0.169890
			if( ma90_colorInt > 2.5 )
				if( ma05 <= 698.921 )
					if( ma10_colorInt <= 3.5 )
						ret := 0.941176 // buy
					if( ma10_colorInt > 3.5 )
						ret := 0.000000
				if( ma05 > 698.921 )
					if( ma65 <= 1115.15 )
						ret := -0.651568
					if( ma65 > 1115.15 )
						ret := -0.139860
	if( ma90 > 1623.63 )

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
