//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: L_Bull_Bear_Power, L_Vortex_Indicator
// ID_model: SOLUSDT_1Day_2BV0_330c8967 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_SOLUSDT_1Day_2BV0_330c8967", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_SOLUSDT_1Day_330c8967(bbm, bearPower, bbp, bullPower, BBPower_Color, VIP_VIM, VIM, VIP)=>
	var float ret = 0  // # DecisionTreeRegressor(max_depth=5, max_features=0.7, max_leaf_nodes=12,min_samples_leaf=7, min_samples_split=5,random_state=843828734)
	if( VIM <= 0.841204 )
		if( VIM <= 0.760406 )
			if( bearPower <= 2.07024 )
				ret := 0.910448 // buy
			if( bearPower > 2.07024 )
				ret := 0.551515
		if( VIM > 0.760406 )
			ret := 0.369048
	if( VIM > 0.841204 )
		if( bearPower <= -10.7764 )
			if( bullPower <= -10.7568 )
				ret := 0.531250
			if( bullPower > -10.7568 )
				if( bullPower <= -6.4638 )
					ret := -0.858696 // sell
				if( bullPower > -6.4638 )
					if( VIP_VIM <= -0.382453 )
						ret := 0.368421
					if( VIP_VIM > -0.382453 )
						ret := -0.510949
		if( bearPower > -10.7764 )
			if( bearPower <= 1.64629 )
				if( bearPower <= 0.23917 )
					if( VIP_VIM <= 0.011149 )
						ret := -0.051044
					if( VIP_VIM > 0.011149 )
						ret := -0.314978
				if( bearPower > 0.23917 )
					ret := 0.315789
			if( bearPower > 1.64629 )
				if( bearPower <= 5.30581 )
					ret := -0.876923 // sell
				if( bearPower > 5.30581 )
					ret := 0.187500
	
    ret //return
// Define expected timeframe based on the selected interval: 1Day pine_value: D   Trigger an alert and show a label if the timeframe is incorrect
alert_message_time_wrong = "The current candle TIMEframe is WRONG: "+ str.tostring(timeframe.period) + ", CHANGE it to the CORRECT one:  1DAY !!"
if (str.tostring(timeframe.period) != "D")
    alert(alert_message_time_wrong, alert.freq_once_per_bar_close)
    label.new(bar_index -300, high+30, text = alert_message_time_wrong, style = label.style_label_down,size = size.large, color = color.red, textcolor = color.white)
    log.error(alert_message_time_wrong)

//CODE associated with the technical indicator L_Bull_Bear_Power 
//@version=5
//indicator "Bull Bear Power", shorttitle="BBP")
lengthInput = input.int(13, title="Length")
bullPower = high - ta.ema(close, lengthInput)

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
