//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: L_Vortex_Indicator
// ID_model: SOLUSDT_1Day_1V00_8f5ae599 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_SOLUSDT_1Day_1V00_8f5ae599", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_SOLUSDT_1Day_8f5ae599(VIP_VIM, VIM, VIP)=>
	var float ret = 0  // # DecisionTreeRegressor(max_depth=5, max_features=0.6, max_leaf_nodes=12,min_samples_split=5, random_state=843828734)
	if( VIP_VIM <= 0.337929 )
		if( VIM <= 1.2638 )
			if( VIP_VIM <= -0.448108 )
				if( VIM <= 1.24419 )
					ret := -0.753086 // sell
				if( VIM > 1.24419 )
					if( VIP_VIM <= -0.489825 )
						ret := 0.142857
					if( VIP_VIM > -0.489825 )
						ret := -0.615385
			if( VIP_VIM > -0.448108 )
				if( VIP_VIM <= -0.407179 )
					if( VIP <= 0.804233 )
						ret := 0.175000
					if( VIP > 0.804233 )
						ret := 0.800000 // buy
				if( VIP_VIM > -0.407179 )
					if( VIP_VIM <= 0.334347 )
						ret := -0.144219
					if( VIP_VIM > 0.334347 )
						ret := -1.000000 // sell
		if( VIM > 1.2638 )
			ret := 0.470588
	if( VIP_VIM > 0.337929 )
		if( VIP <= 1.26573 )
			if( VIM <= 0.843294 )
				if( VIM <= 0.769377 )
					ret := 0.626168
				if( VIM > 0.769377 )
					ret := 0.403226
			if( VIM > 0.843294 )
				ret := -0.333333
		if( VIP > 1.26573 )
			ret := 0.706897 // buy
	
    ret //return
// Define expected timeframe based on the selected interval: 1Day pine_value: D   Trigger an alert and show a label if the timeframe is incorrect
alert_message_time_wrong = "The current candle TIMEframe is WRONG: "+ str.tostring(timeframe.period) + ", CHANGE it to the CORRECT one:  1DAY !!"
if (str.tostring(timeframe.period) != "D")
    alert(alert_message_time_wrong, alert.freq_once_per_bar_close)
    label.new(bar_index -300, high+30, text = alert_message_time_wrong, style = label.style_label_down,size = size.large, color = color.red, textcolor = color.white)
    log.error(alert_message_time_wrong)

//CODE associated with the technical indicator L_Vortex_Indicator 
//@version=5
//indicator title = "Vortex Indicator", shorttitle="VI", format=format.price, precision=4, timeframe="", timeframe_gaps=true)
period_ = input.int(14, title="Length", minval=2)
VMP = math.sum( math.abs( high - low[1]), period_ )

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
