//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: L_Bull_Bear_Power, L_Stochastic_RSI
// ID_model: SHOP_1Hour_2BS0_51c426d4 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_SHOP_1Hour_2BS0_51c426d4", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_SHOP_1Hour_51c426d4(bbm, bearPower, bbp, bullPower, BBPower_Color, d_k, d, rsi1, k, smoothD_d, smoothK_k)=>
	var float ret = 0  // # DecisionTreeRegressor(max_depth=6, max_features=0.7, min_samples_split=10,random_state=843828734)
	if( rsi1 <= 39.2769 )
		if( smoothD_d <= -1.86739 )
			if( bearPower <= -6.00616 )
				if( bbp <= -48.9017 )
					if( bbm <= 30.1595 )
						if( bbp <= -58.4824 )
							ret := -0.563380
						if( bbp > -58.4824 )
							ret := 0.440000
					if( bbm > 30.1595 )
						ret := 0.857143 // buy
				if( bbp > -48.9017 )
					if( bbm <= 0.08 )
						ret := 0.307692
					if( bbm > 0.08 )
						if( smoothD_d <= -1.91368 )
							ret := -0.712177 // sell
						if( smoothD_d > -1.91368 )
							ret := 0.000000
			if( bearPower > -6.00616 )
				if( rsi1 <= 25.7053 )
					if( rsi1 <= 6.33583 )
						ret := 0.733333 // buy
					if( rsi1 > 6.33583 )
						if( bbm <= 0.281287 )
							ret := -0.138462
						if( bbm > 0.281287 )
							ret := -0.496124
				if( rsi1 > 25.7053 )
					if( bearPower <= -4.39453 )
						ret := -0.428571
					if( bearPower > -4.39453 )
						if( rsi1 <= 34.3308 )
							ret := 0.620000
						if( rsi1 > 34.3308 )
							ret := 0.037037
		if( smoothD_d > -1.86739 )
			if( bbp <= 1.1414 )
				if( bullPower <= 8.62531 )
					if( bbm <= 21.2009 )
						if( bearPower <= -13.2467 )
							ret := -0.199326
						if( bearPower > -13.2467 )
							ret := -0.031220
					if( bbm > 21.2009 )
						if( d <= 34.9151 )
							ret := 0.266355
						if( d > 34.9151 )

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
