//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: L_Bull_Bear_Power, L_Money_Flow_Index
// ID_model: PINS_1Day_2BM0_9991e4e8 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_PINS_1Day_2BM0_9991e4e8", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_PINS_1Day_9991e4e8(bearPower, bbm, bbp, bullPower, BBPower_Color, Positive_Money_Flow_Sum, Raw_Money_Flow, MFI_Low, Negative_Money_Flow, Negative_Money_Flow_Sum, Positive_Money_Flow, Money_Flow_Ratio, MFI, MFI_High, Typical_Price)=>
	var float ret = 0  // # DecisionTreeRegressor(max_depth=5, max_features=0.75, max_leaf_nodes=12,min_samples_leaf=4, random_state=843828734)
	if( Negative_Money_Flow_Sum <= 7.71176e+08 )
		ret := 0.692308
	if( Negative_Money_Flow_Sum > 7.71176e+08 )
		if( bbp <= 0.15546 )
			if( Negative_Money_Flow_Sum <= 2.57059e+09 )
				if( Negative_Money_Flow_Sum <= 1.62772e+09 )
					ret := -0.386139
				if( Negative_Money_Flow_Sum > 1.62772e+09 )
					if( Typical_Price <= 24.8757 )
						ret := 0.888199 // buy
					if( Typical_Price > 24.8757 )
						ret := 0.307087
			if( Negative_Money_Flow_Sum > 2.57059e+09 )
				if( Positive_Money_Flow_Sum <= 1.23396e+09 )
					if( bullPower <= -3.24146 )
						ret := 0.700000 // buy
					if( bullPower > -3.24146 )
						ret := -0.768293 // sell
				if( Positive_Money_Flow_Sum > 1.23396e+09 )
					if( Typical_Price <= 72.0994 )
						ret := 0.085450
					if( Typical_Price > 72.0994 )
						ret := -0.840000 // sell
		if( bbp > 0.15546 )
			if( Money_Flow_Ratio <= 1.07968 )
				ret := -0.489796
			if( Money_Flow_Ratio > 1.07968 )
				if( Negative_Money_Flow_Sum <= 2.91133e+09 )
					if( Raw_Money_Flow <= 2.36483e+08 )
						ret := 0.253165
					if( Raw_Money_Flow > 2.36483e+08 )
						ret := -0.325688
				if( Negative_Money_Flow_Sum > 2.91133e+09 )
					ret := 0.289655
	
    ret //return
// Define expected timeframe based on the selected interval: 1Day pine_value: D   Trigger an alert and show a label if the timeframe is incorrect
alert_message_time_wrong = "The current candle TIMEframe is WRONG: "+ str.tostring(timeframe.period) + ", CHANGE it to the CORRECT one:  1DAY !!"
if (str.tostring(timeframe.period) != "D")
    alert(alert_message_time_wrong, alert.freq_once_per_bar_close)
    label.new(bar_index -300, high+30, text = alert_message_time_wrong, style = label.style_label_down,size = size.large, color = color.red, textcolor = color.white)
    log.error(alert_message_time_wrong)

//CODE associated with the technical indicator L_Bull_Bear_Power 
//@version=5
//indicator "Bull Bear Power", shorttitle="BBP")
lengthInput = input.int(13, title="Length")
bullPower = high - ta.ema(close, lengthInput)

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
