//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: SuperTrend
// ID_model: PINS_5Min_1SUP_d4da161e Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_PINS_5Min_1SUP_d4da161e", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_PINS_5Min_d4da161e(dn1, trend, atr, atr2, buySignalInt, sellSignalInt, up1, up, dn)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=5, max_features=0.7,max_leaf_nodes=12, random_state=843828734)
	if( sellSignalInt <= 0.5 )
		if( dn1 <= 45.0173 )
			if( dn <= 21.5424 )
				if( atr2 <= 0.046657 )
					ret := 0.672316
				if( atr2 > 0.046657 )
					if( dn <= 21.2294 )
						ret := -0.131818
					if( dn > 21.2294 )
						ret := 0.299169
			if( dn > 21.5424 )
				if( up <= 21.2025 )
					if( atr2 <= 0.110657 )
						ret := -0.192308
					if( atr2 > 0.110657 )
						ret := -0.680412
				if( up > 21.2025 )
					if( atr <= 0.532932 )
						ret := -0.003074
					if( atr > 0.532932 )
						ret := -0.418060
		if( dn1 > 45.0173 )
			if( up1 <= 44.3939 )
				ret := -0.955882 // sell
			if( up1 > 44.3939 )
				ret := -0.448980
	if( sellSignalInt > 0.5 )
		if( dn1 <= 26.5875 )
			if( up1 <= 21.9692 )
				ret := 0.857143 // buy
			if( up1 > 21.9692 )
				ret := -0.318841
		if( dn1 > 26.5875 )
			ret := 0.687702
	
    ret //return
// Define expected timeframe based on the selected interval: 5Min pine_value: 5   Trigger an alert and show a label if the timeframe is incorrect
alert_message_time_wrong = "The current candle TIMEframe is WRONG: "+ str.tostring(timeframe.period) + ", CHANGE it to the CORRECT one:  5MIN !!"
if (str.tostring(timeframe.period) != "5")
    alert(alert_message_time_wrong, alert.freq_once_per_bar_close)
    label.new(bar_index -300, high+30, text = alert_message_time_wrong, style = label.style_label_down,size = size.large, color = color.red, textcolor = color.white)
    log.error(alert_message_time_wrong)

//CODE associated with the technical indicator SuperTrend 
//@version=5
//indicator title="Supertrend", overlay=true, format=format.price, precision=2, timeframe="")

Periods = input.int(title="ATR Period", defval=10)

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
