//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: Bollinger_RSI_Double_Strategy
// ID_model: PTON_1Day_1BOL_f8d30663 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_PTON_1Day_1BOL_f8d30663", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_PTON_1Day_f8d30663(crossunder_rsi_bbupperInt, BBlower, dif_source_BBupper, crossover_rsi_bblowerInt, vrsi, BBupper, dif_source_BBlower)=>
	var float ret = 0  // # DecisionTreeRegressor(max_depth=5, max_features=0.65, random_state=843828734)
	if( dif_source_BBupper <= -28.7602 )
		if( dif_source_BBupper <= -122.709 )
			if( BBupper <= 149.187 )
				if( BBupper <= 148.787 )
					ret := 1.000000 // buy
				if( BBupper > 148.787 )
					if( dif_source_BBlower <= 19.5646 )
						ret := 0.875000 // buy
					if( dif_source_BBlower > 19.5646 )
						ret := 0.000000
			if( BBupper > 149.187 )
				if( dif_source_BBupper <= -125.326 )
					ret := 0.000000
				if( dif_source_BBupper > -125.326 )
					ret := -1.000000 // sell
		if( dif_source_BBupper > -122.709 )
			if( vrsi <= 25.4824 )
				if( BBlower <= -12.0867 )
					if( dif_source_BBlower <= 27.38 )
						ret := 0.894737 // buy
					if( dif_source_BBlower > 27.38 )
						ret := -0.777778 // sell
				if( BBlower > -12.0867 )
					if( dif_source_BBlower <= 20.4964 )
						ret := -0.369565
					if( dif_source_BBlower > 20.4964 )
						ret := 0.368421
			if( vrsi > 25.4824 )
				if( BBupper <= 82.9182 )
					if( BBupper <= 62.0803 )
						ret := -0.436364
					if( BBupper > 62.0803 )
						ret := 0.615385
				if( BBupper > 82.9182 )
					if( dif_source_BBupper <= -73.1458 )
						ret := -0.663212
					if( dif_source_BBupper > -73.1458 )
						ret := -0.322148
	if( dif_source_BBupper > -28.7602 )
		if( BBlower <= 2.52894 )
			if( dif_source_BBlower <= 128.651 )
				if( BBlower <= 1.59797 )
					if( dif_source_BBupper <= -15.5942 )
						ret := 0.584270
					if( dif_source_BBupper > -15.5942 )
						ret := -0.558824
				if( BBlower > 1.59797 )
					if( BBupper <= 6.45593 )

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
