//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: Madrid_Moving_Average_Ribbon
// ID_model: RUN_1Day_1MAD_771583d3 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_RUN_1Day_1MAD_771583d3", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_RUN_1Day_771583d3(ma05, ma50_colorInt, ma90, ma35_colorInt, ma90_colorInt, ma55_colorInt, ma20, ma15_colorInt, ma40_colorInt, ma45_colorInt, ma65_colorInt, ma75_colorInt, ma35, ma30, ma60, ma75, ma05_colorInt, ma45, ma40, ma30_colorInt, ma25, ma100, ma50, ma70_colorInt, ma10_colorInt, ma20_colorInt, ma60_colorInt, ma25_colorInt, ma10, ma15, ma80, ma65, ma85_colorInt, ma55, ma70, ma85, ma80_colorInt)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=5, max_features=0.7,max_leaf_nodes=12, min_samples_leaf=4,min_samples_split=5, random_state=843828734)
	if( ma35 <= 18.4012 )
		if( ma15 <= 8.95097 )
			if( ma15 <= 5.91598 )
				ret := 0.261484
			if( ma15 > 5.91598 )
				ret := -0.327027
		if( ma15 > 8.95097 )
			if( ma90_colorInt <= 3.5 )
				if( ma10 <= 11.3433 )
					ret := 0.634855
				if( ma10 > 11.3433 )
					if( ma25 <= 15.9902 )
						ret := 0.098720
					if( ma25 > 15.9902 )
						ret := 0.574380
			if( ma90_colorInt > 3.5 )
				if( ma45_colorInt <= 3 )
					ret := -0.741573 // sell
				if( ma45_colorInt > 3 )
					ret := 0.352941
	if( ma35 > 18.4012 )
		if( ma10 <= 20.7072 )
			ret := -0.614286
		if( ma10 > 20.7072 )
			if( ma05 <= 73.7882 )
				if( ma05_colorInt <= 1.5 )
					ret := 0.384328
				if( ma05_colorInt > 1.5 )
					if( ma05 <= 24.1169 )
						ret := 0.272727
					if( ma05 > 24.1169 )
						ret := -0.300429
			if( ma05 > 73.7882 )
				ret := -0.857143 // sell
	
    ret //return
// Define expected timeframe based on the selected interval: 1Day pine_value: D   Trigger an alert and show a label if the timeframe is incorrect
alert_message_time_wrong = "The current candle TIMEframe is WRONG: "+ str.tostring(timeframe.period) + ", CHANGE it to the CORRECT one:  1DAY !!"
if (str.tostring(timeframe.period) != "D")
    alert(alert_message_time_wrong, alert.freq_once_per_bar_close)
    label.new(bar_index -300, high+30, text = alert_message_time_wrong, style = label.style_label_down,size = size.large, color = color.red, textcolor = color.white)
    log.error(alert_message_time_wrong)

//CODE associated with the technical indicator Madrid_Moving_Average_Ribbon 
//@version=5
//indicator "Madrid Moving Average Ribbon", shorttitle="Madrid Ribbon", overlay=true)



	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
