//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: ADX_and_DI
// ID_model: TWLO_5Min_1ADX_f6d8bbac Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_TWLO_5Min_1ADX_f6d8bbac", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_TWLO_5Min_f6d8bbac(directionalMovementPlus, directionalMovementMinus, trueRange, smoothedDirectionalMovementPlus, smoothedDirectionalMovementMinus, diPlus, diMinus, smoothedTrueRange, adx, dx)=>
	var float ret = 0  // # DecisionTreeRegressor(max_depth=6, max_features=0.7, min_samples_split=10,random_state=843828734)
	if( directionalMovementMinus <= 0.089985 )
		if( directionalMovementPlus <= 0.233567 )
			if( directionalMovementMinus <= 0.000418 )
				if( smoothedTrueRange <= 0.675493 )
					if( diPlus <= 35.9915 )
						if( directionalMovementPlus <= 0.091464 )
							ret := -0.007775
						if( directionalMovementPlus > 0.091464 )
							ret := -0.091494
					if( diPlus > 35.9915 )
						if( trueRange <= 0.54786 )
							ret := -0.122163
						if( trueRange > 0.54786 )
							ret := 0.525253
				if( smoothedTrueRange > 0.675493 )
					if( adx <= 43.686 )
						if( dx <= 20.0529 )
							ret := -0.904762 // sell
						if( dx > 20.0529 )
							ret := -0.537037
					if( adx > 43.686 )
						if( diMinus <= 9.37456 )
							ret := -0.621622
						if( diMinus > 9.37456 )
							ret := 0.310345
			if( directionalMovementMinus > 0.000418 )
				if( smoothedDirectionalMovementMinus <= 0.035864 )
					if( adx <= 56.529 )
						if( smoothedDirectionalMovementPlus <= 0.067293 )
							ret := -0.029352
						if( smoothedDirectionalMovementPlus > 0.067293 )
							ret := -0.287611
					if( adx > 56.529 )
						if( directionalMovementPlus <= 0.070209 )
							ret := 0.242806
						if( directionalMovementPlus > 0.070209 )
							ret := -0.355932
				if( smoothedDirectionalMovementMinus > 0.035864 )
					if( diMinus <= 58.6735 )
						if( directionalMovementPlus <= 0.181532 )
							ret := 0.067266
						if( directionalMovementPlus > 0.181532 )
							ret := 0.448276
					if( diMinus > 58.6735 )
						if( directionalMovementMinus <= 0.045829 )
							ret := -0.520000
						if( directionalMovementMinus > 0.045829 )
							ret := 0.000000

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
