//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: L_Bull_Bear_Power, L_Vortex_Indicator
// ID_model: U_1Day_2BV0_860fbc9d Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_U_1Day_2BV0_860fbc9d", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_U_1Day_860fbc9d(bbp, bullPower, BBPower_Color, bearPower, bbm, VIP, VIP_VIM, VIM)=>
	var float ret = 0  // # DecisionTreeRegressor(max_depth=5, max_features=0.7, max_leaf_nodes=12,min_samples_leaf=4, random_state=843828734)
	if( VIP_VIM <= 0.621468 )
		if( bullPower <= -5.36288 )
			if( bbp <= -20.865 )
				if( bullPower <= -8.90785 )
					ret := 0.500000
				if( bullPower > -8.90785 )
					if( VIP <= 0.75379 )
						ret := -0.857143 // sell
					if( VIP > 0.75379 )
						ret := 0.000000
			if( bbp > -20.865 )
				ret := 0.925000 // buy
		if( bullPower > -5.36288 )
			if( bbm <= 2.89969 )
				if( bullPower <= -3.58332 )
					ret := 0.750000 // buy
				if( bullPower > -3.58332 )
					if( bbm <= 1.06326 )
						ret := -0.169935
					if( bbm > 1.06326 )
						ret := 0.219653
			if( bbm > 2.89969 )
				if( bbm <= 6.9272 )
					if( bullPower <= 1.45936 )
						ret := -0.497041
					if( bullPower > 1.45936 )
						ret := -0.104839
				if( bbm > 6.9272 )
					if( VIP <= 1.05428 )
						ret := -0.069767
					if( VIP > 1.05428 )
						ret := 0.424242
	if( VIP_VIM > 0.621468 )
		ret := -0.666667
	
    ret //return
// Define expected timeframe based on the selected interval: 1Day pine_value: D   Trigger an alert and show a label if the timeframe is incorrect
alert_message_time_wrong = "The current candle TIMEframe is WRONG: "+ str.tostring(timeframe.period) + ", CHANGE it to the CORRECT one:  1DAY !!"
if (str.tostring(timeframe.period) != "D")
    alert(alert_message_time_wrong, alert.freq_once_per_bar_close)
    label.new(bar_index -300, high+30, text = alert_message_time_wrong, style = label.style_label_down,size = size.large, color = color.red, textcolor = color.white)
    log.error(alert_message_time_wrong)

//CODE associated with the technical indicator L_Bull_Bear_Power 
//@version=5
//indicator "Bull Bear Power", shorttitle="BBP")
lengthInput = input.int(13, title="Length")
bullPower = high - ta.ema(close, lengthInput)

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
