//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: Madrid_Moving_Average_Ribbon
// ID_model: UBER_1Day_1MAD_ddf19c7d Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_UBER_1Day_1MAD_ddf19c7d", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_UBER_1Day_ddf19c7d(ma100, ma55_colorInt, ma60_colorInt, ma80, ma25, ma75_colorInt, ma80_colorInt, ma50_colorInt, ma30, ma40_colorInt, ma90, ma45_colorInt, ma40, ma50, ma10_colorInt, ma15_colorInt, ma85_colorInt, ma05_colorInt, ma20, ma70, ma70_colorInt, ma85, ma30_colorInt, ma60, ma45, ma55, ma65, ma90_colorInt, ma35, ma20_colorInt, ma65_colorInt, ma10, ma25_colorInt, ma75, ma15, ma05, ma35_colorInt)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=5, max_features=0.9,max_leaf_nodes=30, min_samples_leaf=4,min_samples_split=5, random_state=843828734)
	if( ma05 <= 31.2835 )
		if( ma70_colorInt <= 3.5 )
			if( ma15_colorInt <= 3.5 )
				if( ma20 <= 31.2775 )
					if( ma05_colorInt <= 3.5 )
						ret := 0.821705 // buy
					if( ma05_colorInt > 3.5 )
						ret := 0.362069
				if( ma20 > 31.2775 )
					if( ma20 <= 32.1435 )
						ret := -0.740741 // sell
					if( ma20 > 32.1435 )
						ret := 0.666667
			if( ma15_colorInt > 3.5 )
				if( ma10 <= 22.7361 )
					if( ma70 <= 26.0313 )
						ret := -0.400000
					if( ma70 > 26.0313 )
						ret := -1.000000 // sell
				if( ma10 > 22.7361 )
					if( ma80 <= 27.577 )
						ret := 0.888889 // buy
					if( ma80 > 27.577 )
						ret := -0.133333
		if( ma70_colorInt > 3.5 )
			if( ma50_colorInt <= 1.5 )
				if( ma75 <= 28.2257 )
					ret := -0.125000
				if( ma75 > 28.2257 )
					ret := -1.000000 // sell
			if( ma50_colorInt > 1.5 )
				if( ma25 <= 28.6381 )
					if( ma05 <= 29.4777 )
						ret := 0.137931
					if( ma05 > 29.4777 )
						ret := -0.538462
				if( ma25 > 28.6381 )
					if( ma50 <= 27.7448 )
						ret := 1.000000 // buy
					if( ma50 > 27.7448 )
						ret := 0.875000 // buy
	if( ma05 > 31.2835 )
		if( ma100 <= 51.7507 )
			if( ma05 <= 55.1018 )
				if( ma20 <= 50.6804 )
					if( ma20 <= 32.3792 )
						ret := -0.636364
					if( ma20 > 32.3792 )

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
