//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: L_Stochastic_RSI, L_Vortex_Indicator
// ID_model: UBER_30Min_2SV0_ef54edd5 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_UBER_30Min_2SV0_ef54edd5", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_UBER_30Min_ef54edd5(rsi1, d, k, smoothD_d, d_k, smoothK_k, VIP, VIP_VIM, VIM)=>
	var float ret = 0  // # DecisionTreeRegressor(max_depth=5, max_features=0.9, random_state=843828734)
	if( d_k <= 1.12882 )
		if( VIP <= 1.34453 )
			if( VIM <= 0.879004 )
				if( d <= 62.7218 )
					if( VIP <= 1.01917 )
						ret := 0.558333
					if( VIP > 1.01917 )
						ret := 0.161876
				if( d > 62.7218 )
					if( smoothD_d <= 84.7333 )
						ret := -0.143122
					if( smoothD_d > 84.7333 )
						ret := 0.106447
			if( VIM > 0.879004 )
				if( d_k <= -11.5485 )
					if( rsi1 <= 59.6497 )
						ret := -0.155920
					if( rsi1 > 59.6497 )
						ret := 0.033828
				if( d_k > -11.5485 )
					if( VIM <= 1.32806 )
						ret := -0.036893
					if( VIM > 1.32806 )
						ret := 0.102785
		if( VIP > 1.34453 )
			if( VIP <= 2.04482 )
				if( rsi1 <= 92.366 )
					if( smoothK_k <= -0.064672 )
						ret := 0.833333 // buy
					if( smoothK_k > -0.064672 )
						ret := -0.212264
				if( rsi1 > 92.366 )
					if( rsi1 <= 94.0373 )
						ret := 0.780000 // buy
					if( rsi1 > 94.0373 )
						ret := -0.087719
			if( VIP > 2.04482 )
				if( d_k <= -4.22975 )
					if( VIP <= 2.54898 )
						ret := 0.909091 // buy
					if( VIP > 2.54898 )
						ret := 0.000000
				if( d_k > -4.22975 )
					if( VIP <= 2.29914 )
						ret := -0.615385
					if( VIP > 2.29914 )
						ret := 0.611111
	if( d_k > 1.12882 )

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
