//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: L_Bull_Bear_Power, L_Stochastic_RSI
// ID_model: UBER_1Day_2BS0_d92f8931 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_UBER_1Day_2BS0_d92f8931", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_UBER_1Day_d92f8931(bbp, bullPower, BBPower_Color, bearPower, bbm, rsi1, d, k, smoothD_d, d_k, smoothK_k)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=5, max_features=0.65,min_samples_leaf=4, min_samples_split=5,random_state=843828734)
	if( d_k <= -0.10446 )
		if( bullPower <= 1.95863 )
			if( smoothK_k <= 73.1131 )
				if( smoothD_d <= 10.3414 )
					if( bearPower <= 0.345017 )
						ret := 0.530516
					if( bearPower > 0.345017 )
						ret := -1.000000 // sell
				if( smoothD_d > 10.3414 )
					if( d_k <= -24.7524 )
						ret := 0.896552 // buy
					if( d_k > -24.7524 )
						ret := -0.147170
			if( smoothK_k > 73.1131 )
				if( bbp <= 2.3491 )
					if( d_k <= -2.72611 )
						ret := 0.713287 // buy
					if( d_k > -2.72611 )
						ret := 0.041667
				if( bbp > 2.3491 )
					if( bbm <= 0.833542 )
						ret := -0.800000 // sell
					if( bbm > 0.833542 )
						ret := 0.000000
		if( bullPower > 1.95863 )
			if( rsi1 <= 72.9033 )
				if( smoothD_d <= 38.0143 )
					if( smoothK_k <= 53.3456 )
						ret := 0.014706
					if( smoothK_k > 53.3456 )
						ret := 1.000000 // buy
				if( smoothD_d > 38.0143 )
					if( bearPower <= 1.61723 )
						ret := -0.686441
					if( bearPower > 1.61723 )
						ret := 0.000000
			if( rsi1 > 72.9033 )
				if( smoothD_d <= 87.1363 )
					if( k <= 95.6451 )
						ret := -0.451613
					if( k > 95.6451 )
						ret := 0.900000 // buy
				if( smoothD_d > 87.1363 )
					if( d_k <= -2.4126 )
						ret := 0.875000 // buy
					if( d_k > -2.4126 )
						ret := 0.300000
	if( d_k > -0.10446 )

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
