//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: L_Stochastic_RSI, L_Triple_EMA
// ID_model: UBER_1Hour_2ST0_d5d37902 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_UBER_1Hour_2ST0_d5d37902", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_UBER_1Hour_d5d37902(rsi1, d, k, smoothD_d, d_k, smoothK_k, ema2, ema1, ema12, ema3, ema13, tema)=>
	var float ret = 0  // # DecisionTreeRegressor(max_depth=6, max_features=0.6, max_leaf_nodes=30,random_state=843828734)
	if( rsi1 <= 12.7004 )
		if( ema3 <= 33.2069 )
			if( rsi1 <= 9.52225 )
				ret := 0.960000 // buy
			if( rsi1 > 9.52225 )
				if( d_k <= -0.918739 )
					ret := 0.807692 // buy
				if( d_k > -0.918739 )
					if( smoothK_k <= -2.79023 )
						ret := 0.777778 // buy
					if( smoothK_k > -2.79023 )
						ret := 0.029412
		if( ema3 > 33.2069 )
			if( ema2 <= 37.6182 )
				if( d <= 10.3082 )
					ret := -0.083333
				if( d > 10.3082 )
					ret := -0.900000 // sell
			if( ema2 > 37.6182 )
				if( tema <= 45.2768 )
					if( d_k <= 1.22532 )
						if( ema12 <= -0.908458 )
							ret := 1.000000 // buy
						if( ema12 > -0.908458 )
							ret := 0.214286
					if( d_k > 1.22532 )
						ret := 0.896552 // buy
				if( tema > 45.2768 )
					ret := 0.151515
	if( rsi1 > 12.7004 )
		if( ema13 <= 1.67875 )
			if( ema13 <= -0.731723 )
				if( ema2 <= 36.3541 )
					if( d <= 86.8725 )
						if( d <= 58.7994 )
							ret := -0.300775
						if( d > 58.7994 )
							ret := 0.248276
					if( d > 86.8725 )
						ret := -0.750000 // sell
				if( ema2 > 36.3541 )
					if( d <= 23.6995 )
						if( d_k <= -5.31086 )
							ret := -0.469799
						if( d_k > -5.31086 )
							ret := 0.064240
					if( d > 23.6995 )
						if( rsi1 <= 37.4851 )

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
