//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: Blai5_Koncorde_v10
// ID_model: UBER_30Min_1KON_fcc53a6c Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_UBER_30Min_1KON_fcc53a6c", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_UBER_30Min_fcc53a6c(nvi, nvi_ema, marron_mean, source, azul, verde_azul, verde_mean, xmf, pvimin, stoc, media, tprice, marron, pvim, pvimax, xrsi, oscp, pvi, nvimax, nvimin, verde, verde_media, azul_mean, nvim, BollOsc, pvi_ema, media_azul)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=6, max_features=0.9,min_samples_leaf=7, random_state=843828734)
	if( azul <= -23.4945 )
		if( verde_azul <= 16.3211 )
			if( media <= 65.5894 )
				if( nvi <= 0.963981 )
					if( marron <= -0.544134 )
						if( verde_mean <= -31.5257 )
							ret := 0.456000
						if( verde_mean > -31.5257 )
							ret := 0.795107 // buy
					if( marron > -0.544134 )
						if( marron_mean <= 4.57047 )
							ret := -0.500000
						if( marron_mean > 4.57047 )
							ret := 0.444444
				if( nvi > 0.963981 )
					if( stoc <= 7.87092 )
						if( xrsi <= 15.5465 )
							ret := 0.241379
						if( xrsi > 15.5465 )
							ret := -0.791667 // sell
					if( stoc > 7.87092 )
						if( marron <= -10.8819 )
							ret := 0.064748
						if( marron > -10.8819 )
							ret := 0.581967
			if( media > 65.5894 )
				if( pvimax <= -0.253763 )
					ret := -1.000000 // sell
				if( pvimax > -0.253763 )
					ret := -0.777778 // sell
		if( verde_azul > 16.3211 )
			if( verde_media <= -80.1294 )
				if( oscp <= -25.6554 )
					ret := 0.210526
				if( oscp > -25.6554 )
					if( pvimin <= -0.404036 )
						ret := -0.411765
					if( pvimin > -0.404036 )
						ret := -1.000000 // sell
			if( verde_media > -80.1294 )
				if( verde_azul <= 201.918 )
					if( verde_azul <= 137.164 )
						if( oscp <= 11.1301 )
							ret := 0.163352
						if( oscp > 11.1301 )
							ret := -0.129950
					if( verde_azul > 137.164 )
						if( tprice <= 51.9042 )

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
