//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: L_Triple_EMA
// ID_model: UPST_30Min_1T00_152e1fe4 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_UPST_30Min_1T00_152e1fe4", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_UPST_30Min_152e1fe4(ema2, ema1, ema12, ema3, ema13, tema)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=6, max_features=0.7,max_leaf_nodes=30, min_samples_leaf=7,random_state=843828734)
	if( ema12 <= -4.78917 )
		if( ema2 <= 273.136 )
			ret := -0.708861 // sell
		if( ema2 > 273.136 )
			ret := 0.315789
	if( ema12 > -4.78917 )
		if( ema13 <= 0.097635 )
			if( ema3 <= 20.5989 )
				if( tema <= 18.6327 )
					if( tema <= 18.073 )
						if( ema2 <= 13.0481 )
							ret := 0.256684
						if( ema2 > 13.0481 )
							ret := -0.112126
					if( tema > 18.073 )
						if( tema <= 18.195 )
							ret := 0.632911
						if( tema > 18.195 )
							ret := 0.062718
				if( tema > 18.6327 )
					if( ema2 <= 19.1268 )
						ret := -0.661836
					if( ema2 > 19.1268 )
						if( ema2 <= 19.4623 )
							ret := 0.219178
						if( ema2 > 19.4623 )
							ret := -0.395833
			if( ema3 > 20.5989 )
				if( ema1 <= 21.151 )
					if( ema13 <= -0.214854 )
						if( ema1 <= 20.2076 )
							ret := 0.923077 // buy
						if( ema1 > 20.2076 )
							ret := 0.021053
					if( ema13 > -0.214854 )
						if( ema12 <= 0.004276 )
							ret := 0.702479 // buy
						if( ema12 > 0.004276 )
							ret := 0.129630
				if( ema1 > 21.151 )
					if( ema1 <= 22.3606 )
						if( tema <= 21.7696 )
							ret := -0.027638
						if( tema > 21.7696 )
							ret := -0.465318
					if( ema1 > 22.3606 )
						if( ema3 <= 24.4886 )
							ret := 0.176904

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
