//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: L_Bull_Bear_Power, L_Chaikin_Money_Flow
// ID_model: ZI_5Min_2BC0_4db7098b Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_ZI_5Min_2BC0_4db7098b", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_ZI_5Min_4db7098b(bbp, bullPower, BBPower_Color, bearPower, bbm, ad, ad_mf, mf)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=5, max_features=0.7,max_leaf_nodes=12, random_state=843828734)
	if( bearPower <= 0.163439 )
		if( ad_mf <= 0.605612 )
			if( bullPower <= -0.002779 )
				if( ad <= -1045.71 )
					ret := 0.071341
				if( ad > -1045.71 )
					if( ad_mf <= -0.285365 )
						ret := 0.635052
					if( ad_mf > -0.285365 )
						ret := 0.231534
			if( bullPower > -0.002779 )
				if( bearPower <= 0.065966 )
					if( ad <= -171171 )
						ret := 0.252236
					if( ad > -171171 )
						ret := 0.004508
				if( bearPower > 0.065966 )
					if( ad_mf <= -0.201996 )
						ret := -0.049906
					if( ad_mf > -0.201996 )
						ret := -0.503030
		if( ad_mf > 0.605612 )
			if( bbm <= 0.213296 )
				if( mf <= -0.036118 )
					ret := -0.104773
				if( mf > -0.036118 )
					ret := -0.008462
			if( bbm > 0.213296 )
				ret := -0.307087
	if( bearPower > 0.163439 )
		if( bbm <= 0.009502 )
			ret := -0.821918 // sell
		if( bbm > 0.009502 )
			ret := -0.076446
	
    ret //return
// Define expected timeframe based on the selected interval: 5Min pine_value: 5   Trigger an alert and show a label if the timeframe is incorrect
alert_message_time_wrong = "The current candle TIMEframe is WRONG: "+ str.tostring(timeframe.period) + ", CHANGE it to the CORRECT one:  5MIN !!"
if (str.tostring(timeframe.period) != "5")
    alert(alert_message_time_wrong, alert.freq_once_per_bar_close)
    label.new(bar_index -300, high+30, text = alert_message_time_wrong, style = label.style_label_down,size = size.large, color = color.red, textcolor = color.white)
    log.error(alert_message_time_wrong)

//CODE associated with the technical indicator L_Bull_Bear_Power 
//@version=5
//indicator "Bull Bear Power", shorttitle="BBP")
lengthInput = input.int(13, title="Length")
bullPower = high - ta.ema(close, lengthInput)

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
