//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: SuperTrend
// ID_model: ZI_1Day_1SUP_f62c70ea Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_ZI_1Day_1SUP_f62c70ea", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_ZI_1Day_f62c70ea(atr2, sellSignalInt, dn1, up1, dn, buySignalInt, up, trend, atr)=>
	var float ret = 0  // # DecisionTreeRegressor(max_depth=5, max_features=0.7, max_leaf_nodes=30,min_samples_leaf=7, min_samples_split=5,random_state=843828734)
	if( dn <= 50.1723 )
		if( dn1 <= 37.51 )
			if( up1 <= 24.1418 )
				if( up1 <= 8.74557 )
					if( atr <= 0.472224 )
						ret := 0.437500
					if( atr > 0.472224 )
						ret := 0.764706 // buy
				if( up1 > 8.74557 )
					if( up <= 10.8026 )
						ret := -0.491228
					if( up > 10.8026 )
						ret := 0.118497
			if( up1 > 24.1418 )
				if( dn1 <= 31.9905 )
					if( atr2 <= 1.0516 )
						ret := -0.571429
					if( atr2 > 1.0516 )
						ret := -1.000000 // sell
				if( dn1 > 31.9905 )
					if( up1 <= 25.4064 )
						ret := -0.142857
					if( up1 > 25.4064 )
						ret := -0.647059
		if( dn1 > 37.51 )
			if( dn1 <= 43.3585 )
				if( atr2 <= 3.22622 )
					if( atr <= 2.11433 )
						ret := 0.911111 // buy
					if( atr > 2.11433 )
						ret := 0.648649
				if( atr2 > 3.22622 )
					ret := -0.555556
			if( dn1 > 43.3585 )
				if( dn <= 44.3714 )
					if( dn1 <= 44.665 )
						ret := -0.500000
					if( dn1 > 44.665 )
						ret := -1.000000 // sell
				if( dn > 44.3714 )
					if( atr2 <= 2.98384 )
						ret := 0.343750
					if( atr2 > 2.98384 )
						ret := 0.838710 // buy
	if( dn > 50.1723 )
		if( dn1 <= 55.144 )
			if( atr2 <= 2.80557 )
				if( up <= 37.6278 )

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
