//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: Madrid_Moving_Average_Ribbon
// ID_model: ZI_1Hour_1MAD_612376ae Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_ZI_1Hour_1MAD_612376ae", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_ZI_1Hour_612376ae(ma25, ma40, ma85, ma05, ma45_colorInt, ma80_colorInt, ma55, ma20, ma65_colorInt, ma05_colorInt, ma10, ma40_colorInt, ma50_colorInt, ma60_colorInt, ma15, ma65, ma85_colorInt, ma45, ma35, ma10_colorInt, ma60, ma100, ma20_colorInt, ma55_colorInt, ma75_colorInt, ma90, ma30, ma15_colorInt, ma25_colorInt, ma80, ma90_colorInt, ma50, ma70_colorInt, ma30_colorInt, ma35_colorInt, ma75, ma70)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=6, max_features=0.7,max_leaf_nodes=30, min_samples_leaf=7,random_state=843828734)
	if( ma90 <= 10.1299 )
		if( ma60_colorInt <= 3.5 )
			if( ma05 <= 9.60488 )
				if( ma45 <= 8.86302 )
					ret := 0.133333
				if( ma45 > 8.86302 )
					if( ma100 <= 9.96683 )
						ret := 0.851064 // buy
					if( ma100 > 9.96683 )
						ret := 0.083333
			if( ma05 > 9.60488 )
				if( ma40_colorInt <= 1.5 )
					if( ma10 <= 10.0732 )
						ret := -0.227273
					if( ma10 > 10.0732 )
						if( ma05 <= 10.5457 )
							ret := 0.678571
						if( ma05 > 10.5457 )
							ret := -0.214286
				if( ma40_colorInt > 1.5 )
					if( ma05_colorInt <= 2.5 )
						ret := 0.825000 // buy
					if( ma05_colorInt > 2.5 )
						ret := 0.263158
		if( ma60_colorInt > 3.5 )
			if( ma65_colorInt <= 3.5 )
				ret := 0.888889 // buy
			if( ma65_colorInt > 3.5 )
				if( ma25 <= 9.07965 )
					if( ma20 <= 9.0797 )
						ret := 0.000000
					if( ma20 > 9.0797 )
						ret := -1.000000 // sell
				if( ma25 > 9.07965 )
					ret := 0.137931
	if( ma90 > 10.1299 )
		if( ma100 <= 11.4995 )
			if( ma90 <= 10.3486 )
				if( ma30 <= 10.5018 )
					ret := -0.067308
				if( ma30 > 10.5018 )
					ret := -0.800000 // sell
			if( ma90 > 10.3486 )
				ret := -0.679104
		if( ma100 > 11.4995 )
			if( ma65 <= 43.3088 )
				if( ma30 <= 39.8722 )
					if( ma35 <= 39.0803 )

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
