//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: L_Bull_Bear_Power, L_Stochastic_RSI
// ID_model: ZI_1Day_2BS0_e05e5654 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_ZI_1Day_2BS0_e05e5654", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_ZI_1Day_e05e5654(bbp, bullPower, BBPower_Color, bearPower, bbm, smoothK_k, d_k, k, smoothD_d, rsi1, d)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=5, max_features=0.82,max_leaf_nodes=30, random_state=843828734)
	if( rsi1 <= 38.9272 )
		if( d_k <= -2.65583 )
			if( k <= 27.3223 )
				if( k <= 26.2827 )
					if( smoothD_d <= 12.9375 )
						ret := -0.305556
					if( smoothD_d > 12.9375 )
						ret := 0.666667
				if( k > 26.2827 )
					ret := -1.000000 // sell
			if( k > 27.3223 )
				if( rsi1 <= 36.448 )
					if( bbm <= 2.015 )
						ret := 0.208333
					if( bbm > 2.015 )
						ret := 0.812500 // buy
				if( rsi1 > 36.448 )
					if( bullPower <= 0.413178 )
						ret := 0.100000
					if( bullPower > 0.413178 )
						ret := -0.714286 // sell
		if( d_k > -2.65583 )
			if( bbm <= 0.7675 )
				if( d_k <= 0.508755 )
					if( k <= 41.4322 )
						ret := 0.000000
					if( k > 41.4322 )
						ret := 1.000000 // buy
				if( d_k > 0.508755 )
					if( d_k <= 1.01081 )
						ret := -0.666667
					if( d_k > 1.01081 )
						ret := -0.153846
			if( bbm > 0.7675 )
				if( bearPower <= -5.04228 )
					if( bullPower <= -3.22138 )
						ret := 0.564103
					if( bullPower > -3.22138 )
						ret := -0.380952
				if( bearPower > -5.04228 )
					if( d_k <= 15.7598 )
						ret := 0.746988 // buy
					if( d_k > 15.7598 )
						ret := 0.000000
	if( rsi1 > 38.9272 )
		if( d <= 48.668 )
			if( smoothK_k <= 4.81251 )
				if( rsi1 <= 55.6091 )

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
