//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: ADX_and_DI
// ID_model: CRWD_1Hour_1ADX_6244e265 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_CRWD_1Hour_1ADX_6244e265", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_CRWD_1Hour_6244e265(dx, directionalMovementMinus, diPlus, smoothedDirectionalMovementMinus, trueRange, smoothedDirectionalMovementPlus, smoothedTrueRange, directionalMovementPlus, diMinus, adx)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=6, max_features=0.5,max_leaf_nodes=30, min_samples_leaf=4,min_samples_split=10, random_state=843828734)
	if( smoothedDirectionalMovementMinus <= 0.212197 )
		if( diPlus <= 48.0432 )
			if( dx <= 83.7461 )
				if( smoothedTrueRange <= 2.27568 )
					if( adx <= 42.8588 )
						if( diMinus <= 4.61836 )
							ret := 0.666667
						if( diMinus > 4.61836 )
							ret := 0.156054
					if( adx > 42.8588 )
						if( directionalMovementPlus <= 1.23263 )
							ret := 0.040470
						if( directionalMovementPlus > 1.23263 )
							ret := -0.423611
				if( smoothedTrueRange > 2.27568 )
					if( diPlus <= 38.807 )
						ret := -0.386076
					if( diPlus > 38.807 )
						if( adx <= 82.6075 )
							ret := -0.113208
						if( adx > 82.6075 )
							ret := 0.952381 // buy
			if( dx > 83.7461 )
				ret := -0.185501
		if( diPlus > 48.0432 )
			if( smoothedTrueRange <= 1.51369 )
				if( adx <= 57.3627 )
					ret := -0.030303
				if( adx > 57.3627 )
					ret := -0.800000 // sell
			if( smoothedTrueRange > 1.51369 )
				if( smoothedTrueRange <= 2.30339 )
					if( adx <= 37.094 )
						ret := -0.375000
					if( adx > 37.094 )
						ret := 0.753425 // buy
				if( smoothedTrueRange > 2.30339 )
					if( trueRange <= 3.52611 )
						ret := -0.109890
					if( trueRange > 3.52611 )
						ret := 0.780488 // buy
	if( smoothedDirectionalMovementMinus > 0.212197 )
		if( smoothedDirectionalMovementPlus <= 1.13464 )
			if( directionalMovementMinus <= 0.187894 )
				if( diMinus <= 20.9759 )
					if( dx <= 12.0669 )
						if( adx <= 51.568 )
							ret := 0.319008

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
