//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: Bollinger_RSI_Double_Strategy
// ID_model: CRWD_1Day_1BOL_4ebcae31 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_CRWD_1Day_1BOL_4ebcae31", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_CRWD_1Day_4ebcae31(crossunder_rsi_bbupperInt, BBlower, dif_source_BBupper, crossover_rsi_bblowerInt, vrsi, BBupper, dif_source_BBlower)=>
	var float ret = 0  // # DecisionTreeRegressor(max_depth=5, max_features=0.6, min_samples_leaf=7,min_samples_split=5, random_state=843828734)
	if( BBlower <= 104.62 )
		if( BBlower <= 27.3741 )
			if( dif_source_BBupper <= 0.01321 )
				if( BBupper <= 134.205 )
					if( vrsi <= 44.5576 )
						ret := 0.000000
					if( vrsi > 44.5576 )
						ret := 0.533333
				if( BBupper > 134.205 )
					ret := -0.300000
			if( dif_source_BBupper > 0.01321 )
				if( dif_source_BBupper <= 4.92422 )
					if( BBupper <= 121.021 )
						ret := -0.800000 // sell
					if( BBupper > 121.021 )
						ret := -0.125000
				if( dif_source_BBupper > 4.92422 )
					ret := -1.000000 // sell
		if( BBlower > 27.3741 )
			if( dif_source_BBlower <= 130.347 )
				if( vrsi <= 75.7707 )
					if( dif_source_BBupper <= -127.913 )
						ret := -0.333333
					if( dif_source_BBupper > -127.913 )
						ret := 0.555288
				if( vrsi > 75.7707 )
					if( dif_source_BBupper <= 13.3576 )
						ret := 0.393701
					if( dif_source_BBupper > 13.3576 )
						ret := -0.785714 // sell
			if( dif_source_BBlower > 130.347 )
				if( dif_source_BBupper <= -12.6859 )
					if( vrsi <= 34.1018 )
						ret := 0.318182
					if( vrsi > 34.1018 )
						ret := -0.611111
				if( dif_source_BBupper > -12.6859 )
					if( dif_source_BBupper <= 16.9277 )
						ret := 0.625000
					if( dif_source_BBupper > 16.9277 )
						ret := -0.068966
	if( BBlower > 104.62 )
		if( BBlower <= 176.226 )
			if( dif_source_BBupper <= -122.997 )
				if( vrsi <= 18.221 )
					if( dif_source_BBlower <= -2.78447 )
						ret := 0.285714
					if( dif_source_BBlower > -2.78447 )

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
