//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: Ultimate_MA_MTF_V2
// ID_model: CRWD_1Day_1ULT_0418f69a Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_CRWD_1Day_1ULT_0418f69a", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_CRWD_1Day_0418f69a(ma_downInt, cr_upInt, avg2, cr_down2Int, cr_up2Int, cr_downInt, ma_upInt, avg)=>
	var float ret = 0  // # DecisionTreeRegressor(max_depth=5, max_features=0.7, max_leaf_nodes=12,min_samples_leaf=4, random_state=843828734)
	if( avg2 <= 349.183 )
		if( avg2 <= 83.7614 )
			if( avg <= 52.2801 )
				if( ma_upInt <= 0.5 )
					ret := 0.837500 // buy
				if( ma_upInt > 0.5 )
					ret := 0.272727
			if( avg > 52.2801 )
				if( avg2 <= 74.2007 )
					if( ma_downInt <= 0.5 )
						ret := -0.198473
					if( ma_downInt > 0.5 )
						ret := -0.716667 // sell
				if( avg2 > 74.2007 )
					ret := -0.818182 // sell
		if( avg2 > 83.7614 )
			if( avg <= 107.676 )
				if( avg2 <= 87.5066 )
					ret := 0.900000 // buy
				if( avg2 > 87.5066 )
					if( avg2 <= 96.5799 )
						ret := -0.428571
					if( avg2 > 96.5799 )
						ret := 0.578947
			if( avg > 107.676 )
				if( avg2 <= 105.566 )
					ret := -1.000000 // sell
				if( avg2 > 105.566 )
					if( avg2 <= 107.456 )
						ret := 0.925926 // buy
					if( avg2 > 107.456 )
						ret := 0.033657
	if( avg2 > 349.183 )
		ret := -0.941176 // sell
	
    ret //return
// Define expected timeframe based on the selected interval: 1Day pine_value: D   Trigger an alert and show a label if the timeframe is incorrect
alert_message_time_wrong = "The current candle TIMEframe is WRONG: "+ str.tostring(timeframe.period) + ", CHANGE it to the CORRECT one:  1DAY !!"
if (str.tostring(timeframe.period) != "D")
    alert(alert_message_time_wrong, alert.freq_once_per_bar_close)
    label.new(bar_index -300, high+30, text = alert_message_time_wrong, style = label.style_label_down,size = size.large, color = color.red, textcolor = color.white)
    log.error(alert_message_time_wrong)

//CODE associated with the technical indicator Ultimate_MA_MTF_V2 
//@version=5
//indicator title="CM_Ultimate_MA_MTF_V2", shorttitle="CM_Ultimate_MA_MTF_V2", overlay=true)

// Inputs

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
