//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: ADX_and_DI
// ID_model: AMD_30Min_1ADX_80692a12 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_AMD_30Min_1ADX_80692a12", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_AMD_30Min_80692a12(smoothedDirectionalMovementMinus, directionalMovementMinus, diMinus, dx, directionalMovementPlus, smoothedDirectionalMovementPlus, adx, trueRange, smoothedTrueRange, diPlus)=>
	var float ret = 0  // # DecisionTreeRegressor(max_depth=8, max_features=sqrt, min_samples_leaf=7,min_samples_split=5, random_state=843828734)
	if( smoothedDirectionalMovementMinus <= 0.08422 )
		if( smoothedTrueRange <= 0.03031 )
			if( smoothedDirectionalMovementMinus <= 0.007149 )
				if( dx <= 51.6757 )
					if( diMinus <= 21.4738 )
						if( smoothedDirectionalMovementMinus <= 0.001817 )
							ret := -0.545455
						if( smoothedDirectionalMovementMinus > 0.001817 )
							if( diPlus <= 32.9901 )
								if( dx <= 12.0378 )
									ret := 0.481481
								if( dx > 12.0378 )
									ret := 0.233618
							if( diPlus > 32.9901 )
								if( smoothedDirectionalMovementPlus <= 0.009575 )
									ret := -0.424242
								if( smoothedDirectionalMovementPlus > 0.009575 )
									ret := 0.214286
					if( diMinus > 21.4738 )
						if( diMinus <= 24.5122 )
							if( diPlus <= 24.8224 )
								if( directionalMovementMinus <= 0.004716 )
									ret := 0.044444
								if( directionalMovementMinus > 0.004716 )
									ret := -0.333333
							if( diPlus > 24.8224 )
								if( adx <= 18.7639 )
									ret := -0.869565 // sell
								if( adx > 18.7639 )
									ret := -0.212766
						if( diMinus > 24.5122 )
							if( adx <= 48.7038 )
								if( smoothedDirectionalMovementPlus <= 0.005455 )
									ret := 0.380952
								if( smoothedDirectionalMovementPlus > 0.005455 )
									ret := -0.137255
							if( adx > 48.7038 )
								ret := 0.818182 // buy
				if( dx > 51.6757 )
					if( smoothedDirectionalMovementMinus <= 0.001656 )
						if( diPlus <= 22.4627 )
							ret := -0.944444 // sell
						if( diPlus > 22.4627 )
							if( diMinus <= 5.36937 )
								if( dx <= 83.8427 )
									ret := 0.000000
								if( dx > 83.8427 )
									ret := 0.882353 // buy

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
