//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: ADX_and_DI
// ID_model: AMD_1Day_1ADX_86a6854b Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_AMD_1Day_1ADX_86a6854b", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_AMD_1Day_86a6854b(smoothedDirectionalMovementMinus, directionalMovementMinus, diMinus, dx, directionalMovementPlus, smoothedDirectionalMovementPlus, adx, trueRange, smoothedTrueRange, diPlus)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=5, max_features=0.7,max_leaf_nodes=30, min_samples_leaf=7,random_state=843828734)
	if( smoothedDirectionalMovementPlus <= 1.90036 )
		if( adx <= 46.9426 )
			if( smoothedDirectionalMovementMinus <= 0.760619 )
				if( diPlus <= 17.3106 )
					if( adx <= 20.5067 )
						ret := -0.068182
					if( adx > 20.5067 )
						ret := 0.675556
				if( diPlus > 17.3106 )
					if( adx <= 13.7928 )
						ret := -0.429907
					if( adx > 13.7928 )
						ret := 0.173596
			if( smoothedDirectionalMovementMinus > 0.760619 )
				if( directionalMovementPlus <= 0.229015 )
					if( smoothedDirectionalMovementPlus <= 0.356573 )
						ret := 0.842105 // buy
					if( smoothedDirectionalMovementPlus > 0.356573 )
						ret := -0.047478
				if( directionalMovementPlus > 0.229015 )
					if( diMinus <= 36.8329 )
						ret := -0.240000
					if( diMinus > 36.8329 )
						ret := -0.839286 // sell
		if( adx > 46.9426 )
			if( dx <= 56.1664 )
				if( smoothedTrueRange <= 6.47211 )
					if( diMinus <= 31.5538 )
						ret := -0.362179
					if( diMinus > 31.5538 )
						ret := -0.854545 // sell
				if( smoothedTrueRange > 6.47211 )
					if( directionalMovementPlus <= 1.36956 )
						ret := 0.428571
					if( directionalMovementPlus > 1.36956 )
						ret := 0.866667 // buy
			if( dx > 56.1664 )
				if( diPlus <= 39.4475 )
					if( adx <= 69.3458 )
						ret := 0.421687
					if( adx > 69.3458 )
						ret := -0.693548
				if( diPlus > 39.4475 )
					if( dx <= 79.0012 )
						ret := 0.402597
					if( dx > 79.0012 )
						ret := 0.803571 // buy
	if( smoothedDirectionalMovementPlus > 1.90036 )

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
