//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: L_Stochastic_RSI, L_Triple_EMA
// ID_model: AAVEUSDT_15Min_2ST0_d312f13a Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_AAVEUSDT_15Min_2ST0_d312f13a", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_AAVEUSDT_15Min_d312f13a(rsi1, smoothK_k, d_k, k, d, smoothD_d, ema3, tema, ema2, ema12, ema13, ema1)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=8, max_features=0.7,min_samples_leaf=4, min_samples_split=5,random_state=843828734)
	if( smoothK_k <= 47.1045 )
		if( k <= 15.4378 )
			if( tema <= 91.0294 )
				if( rsi1 <= 34.4815 )
					if( ema12 <= -0.257459 )
						if( d_k <= 0.254621 )
							if( tema <= 58.0329 )
								if( ema3 <= 57.0586 )
									ret := -0.187500
								if( ema3 > 57.0586 )
									ret := 0.486239
							if( tema > 58.0329 )
								if( rsi1 <= 24.1027 )
									ret := -0.358760
								if( rsi1 > 24.1027 )
									ret := -0.047945
						if( d_k > 0.254621 )
							if( rsi1 <= 23.2649 )
								if( ema13 <= -1.03271 )
									ret := 0.171254
								if( ema13 > -1.03271 )
									ret := -0.308483
							if( rsi1 > 23.2649 )
								if( rsi1 <= 28.9365 )
									ret := 0.229412
								if( rsi1 > 28.9365 )
									ret := -0.018868
					if( ema12 > -0.257459 )
						if( rsi1 <= 22.2136 )
							if( ema1 <= 55.7105 )
								if( ema1 <= 51.8024 )
									ret := -0.666667
								if( ema1 > 51.8024 )
									ret := -0.083333
							if( ema1 > 55.7105 )
								if( ema1 <= 76.4751 )
									ret := -0.631902
								if( ema1 > 76.4751 )
									ret := -0.789700 // sell
						if( rsi1 > 22.2136 )
							if( ema13 <= 0.00324 )
								if( smoothK_k <= -2.98338 )
									ret := -0.140845
								if( smoothK_k > -2.98338 )
									ret := -0.380865
							if( ema13 > 0.00324 )
								if( ema12 <= -0.125677 )
									ret := 0.444444

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
