//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: ADX_and_DI
// ID_model: ABNB_1Hour_1ADX_8333d9a1 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_ABNB_1Hour_1ADX_8333d9a1", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_ABNB_1Hour_8333d9a1(smoothedDirectionalMovementMinus, directionalMovementMinus, diMinus, dx, directionalMovementPlus, smoothedDirectionalMovementPlus, adx, trueRange, smoothedTrueRange, diPlus)=>
	var float ret = 0  // # DecisionTreeRegressor(max_depth=6, max_features=0.7, min_samples_split=10,random_state=843828734)
	if( directionalMovementMinus <= 0.072692 )
		if( smoothedTrueRange <= 1.0093 )
			if( smoothedDirectionalMovementMinus <= 0.034334 )
				if( directionalMovementPlus <= 1.0073 )
					if( trueRange <= 0.395 )
						if( diMinus <= 1.68653 )
							ret := 0.333333
						if( diMinus > 1.68653 )
							ret := 0.000000
					if( trueRange > 0.395 )
						if( diMinus <= 3.44286 )
							ret := 0.500000
						if( diMinus > 3.44286 )
							ret := 1.000000 // buy
				if( directionalMovementPlus > 1.0073 )
					ret := -0.857143 // sell
			if( smoothedDirectionalMovementMinus > 0.034334 )
				if( diPlus <= 48.683 )
					if( diPlus <= 39.1672 )
						if( smoothedDirectionalMovementPlus <= 0.263231 )
							ret := -0.015048
						if( smoothedDirectionalMovementPlus > 0.263231 )
							ret := 0.250454
					if( diPlus > 39.1672 )
						if( adx <= 41.1002 )
							ret := -0.394286
						if( adx > 41.1002 )
							ret := 0.006211
				if( diPlus > 48.683 )
					if( adx <= 39.2397 )
						if( directionalMovementPlus <= 2.67139 )
							ret := 0.111111
						if( directionalMovementPlus > 2.67139 )
							ret := -1.000000 // sell
					if( adx > 39.2397 )
						if( trueRange <= 0.950151 )
							ret := 0.187500
						if( trueRange > 0.950151 )
							ret := 0.861111 // buy
		if( smoothedTrueRange > 1.0093 )
			if( smoothedDirectionalMovementPlus <= 0.833925 )
				if( directionalMovementPlus <= 3.38915 )
					if( directionalMovementPlus <= 1.15998 )
						if( diMinus <= 58.5059 )
							ret := -0.065939
						if( diMinus > 58.5059 )
							ret := 1.000000 // buy
					if( directionalMovementPlus > 1.15998 )

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
