//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: Ichimoku_Cloud
// ID_model: ADSK_1Hour_1ICH_722fb258 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_ADSK_1Hour_1ICH_722fb258", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_ADSK_1Hour_722fb258(basis_max, tenkan_sen, senkou_span_b, senkou_span_b_displaced, kinjun_sen, senkou_span_a, chinkou_span, basis_minus, cross_dn_tenkan_kinjunInt, senkou_span_a_displaced, cross_up_tenkan_kinjunInt)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=6, max_features=0.7,max_leaf_nodes=30, min_samples_leaf=7,random_state=843828734)
	if( senkou_span_b_displaced <= 303.518 )
		if( chinkou_span <= 289.864 )
			if( tenkan_sen <= 202.812 )
				if( chinkou_span <= 194.978 )
					if( tenkan_sen <= 145.287 )
						if( chinkou_span <= 134.985 )
							ret := -0.147448
						if( chinkou_span > 134.985 )
							ret := 0.436478
					if( tenkan_sen > 145.287 )
						if( chinkou_span <= 148.465 )
							ret := -0.540193
						if( chinkou_span > 148.465 )
							ret := -0.013702
				if( chinkou_span > 194.978 )
					if( kinjun_sen <= 187.625 )
						ret := 0.912037 // buy
					if( kinjun_sen > 187.625 )
						if( chinkou_span <= 210.687 )
							ret := 0.224706
						if( chinkou_span > 210.687 )
							ret := 0.591892
			if( tenkan_sen > 202.812 )
				if( senkou_span_a <= 282.506 )
					if( chinkou_span <= 205.147 )
						if( basis_max <= 0.116244 )
							ret := -0.705882 // sell
						if( basis_max > 0.116244 )
							ret := -0.499069
					if( chinkou_span > 205.147 )
						if( tenkan_sen <= 212.283 )
							ret := 0.329637
						if( tenkan_sen > 212.283 )
							ret := -0.029531
				if( senkou_span_a > 282.506 )
					if( basis_max <= 2.11721 )
						if( senkou_span_b_displaced <= 286.067 )
							ret := -0.188406
						if( senkou_span_b_displaced > 286.067 )
							ret := -0.613559
					if( basis_max > 2.11721 )
						ret := 1.000000 // buy
		if( chinkou_span > 289.864 )
			if( kinjun_sen <= 293.134 )
				if( basis_max <= -1.22924 )
					if( senkou_span_a_displaced <= 295.292 )
						ret := 0.196581
					if( senkou_span_a_displaced > 295.292 )

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
