//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: Blai5_Koncorde_v10
// ID_model: ADSK_15Min_1KON_cff94932 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_ADSK_15Min_1KON_cff94932", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_ADSK_15Min_cff94932(oscp, media, media_azul, verde_media, azul, tprice, azul_mean, verde, nvim, marron, pvimin, pvi, nvimax, verde_mean, xmf, source, stoc, pvimax, nvi_ema, nvi, xrsi, pvim, marron_mean, nvimin, BollOsc, verde_azul, pvi_ema)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=8,max_features=sqrt, min_samples_leaf=7,random_state=843828734)
	if( nvi_ema <= 1.44028 )
		if( pvimin <= 0.446821 )
			if( pvi_ema <= 0.03093 )
				if( media_azul <= 116.576 )
					if( tprice <= 179.071 )
						if( marron_mean <= 26.6034 )
							if( stoc <= 19.1686 )
								if( verde_media <= -18.3731 )
									ret := 0.177215
								if( verde_media > -18.3731 )
									ret := -0.822222 // sell
							if( stoc > 19.1686 )
								if( nvimax <= 0.003899 )
									ret := 0.941176 // buy
								if( nvimax > 0.003899 )
									ret := 0.241379
						if( marron_mean > 26.6034 )
							if( nvimax <= 0.643142 )
								if( source <= 73.0329 )
									ret := 0.409091
								if( source > 73.0329 )
									ret := 0.760181 // buy
							if( nvimax > 0.643142 )
								if( nvimin <= 1.18201 )
									ret := -0.071429
								if( nvimin > 1.18201 )
									ret := 0.526316
					if( tprice > 179.071 )
						if( verde_media <= -31.9221 )
							if( source <= 184.432 )
								ret := -0.272727
							if( source > 184.432 )
								if( BollOsc <= -58.621 )
									ret := 0.333333
								if( BollOsc > -58.621 )
									ret := 1.000000 // buy
						if( verde_media > -31.9221 )
							if( azul <= -21.5912 )
								ret := 1.000000 // buy
							if( azul > -21.5912 )
								if( xmf <= 85.0875 )
									ret := -0.196262
								if( xmf > 85.0875 )
									ret := 0.739130 // buy
				if( media_azul > 116.576 )
					if( verde_azul <= 119.118 )
						ret := -1.000000 // sell
					if( verde_azul > 119.118 )

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
