//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: L_Bull_Bear_Power, L_Triple_EMA
// ID_model: AFRM_30Min_2BT0_9a9ed6e8 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_AFRM_30Min_2BT0_9a9ed6e8", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_AFRM_30Min_9a9ed6e8(bullPower, bbp, bearPower, bbm, BBPower_Color, ema3, tema, ema2, ema12, ema13, ema1)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=6, max_features=0.9,min_samples_leaf=7, random_state=843828734)
	if( ema2 <= 158.694 )
		if( ema3 <= 18.1017 )
			if( bearPower <= 0.64524 )
				if( ema3 <= 9.43455 )
					if( bbp <= 0.043273 )
						if( ema12 <= -0.014835 )
							ret := 0.414141
						if( ema12 > -0.014835 )
							ret := -0.518519
					if( bbp > 0.043273 )
						if( tema <= 9.57273 )
							ret := 0.663507
						if( tema > 9.57273 )
							ret := -0.030303
				if( ema3 > 9.43455 )
					if( ema3 <= 10.2154 )
						if( ema1 <= 10.12 )
							ret := -0.015152
						if( ema1 > 10.12 )
							ret := -0.664474
					if( ema3 > 10.2154 )
						if( ema13 <= -0.647116 )
							ret := 0.458904
						if( ema13 > -0.647116 )
							ret := 0.054731
			if( bearPower > 0.64524 )
				if( ema2 <= 15.1072 )
					if( ema12 <= 0.634299 )
						ret := 0.636364
					if( ema12 > 0.634299 )
						ret := -0.875000 // sell
				if( ema2 > 15.1072 )
					if( ema12 <= 0.777641 )
						if( bullPower <= 1.23456 )
							ret := 0.600000
						if( bullPower > 1.23456 )
							ret := 0.979167 // buy
					if( ema12 > 0.777641 )
						ret := 0.500000
		if( ema3 > 18.1017 )
			if( ema12 <= -1.67437 )
				if( ema12 <= -5.09094 )
					ret := -0.933333 // sell
				if( ema12 > -5.09094 )
					if( ema13 <= -6.28094 )
						if( ema3 <= 91.1665 )
							ret := -0.100000
						if( ema3 > 91.1665 )

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
