//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: ADX_and_DI
// ID_model: ASAN_5Min_1ADX_c9f5f18e Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_ASAN_5Min_1ADX_c9f5f18e", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_ASAN_5Min_c9f5f18e(smoothedDirectionalMovementMinus, directionalMovementMinus, diMinus, dx, directionalMovementPlus, smoothedDirectionalMovementPlus, adx, trueRange, smoothedTrueRange, diPlus)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=6, max_features=0.9,min_samples_leaf=7, random_state=843828734)
	if( directionalMovementMinus <= 0.063566 )
		if( smoothedDirectionalMovementPlus <= 0.021101 )
			if( adx <= 17.6846 )
				if( dx <= 4.61191 )
					if( directionalMovementMinus <= 0.032563 )
						if( trueRange <= 0.046505 )
							ret := 0.044944
						if( trueRange > 0.046505 )
							ret := -0.294393
					if( directionalMovementMinus > 0.032563 )
						if( diPlus <= 28.8326 )
							ret := 0.625000
						if( diPlus > 28.8326 )
							ret := -0.357143
				if( dx > 4.61191 )
					if( diMinus <= 13.5224 )
						if( directionalMovementPlus <= 0.050749 )
							ret := -0.239726
						if( directionalMovementPlus > 0.050749 )
							ret := 0.666667
					if( diMinus > 13.5224 )
						if( diMinus <= 58.0178 )
							ret := 0.179586
						if( diMinus > 58.0178 )
							ret := 0.950000 // buy
			if( adx > 17.6846 )
				if( diMinus <= 35.7075 )
					if( adx <= 68.6807 )
						if( diMinus <= 20.3906 )
							ret := -0.077423
						if( diMinus > 20.3906 )
							ret := 0.006797
					if( adx > 68.6807 )
						if( diPlus <= 23.5449 )
							ret := -0.504808
						if( diPlus > 23.5449 )
							ret := 0.080000
				if( diMinus > 35.7075 )
					if( diMinus <= 63.1327 )
						if( diMinus <= 61.5405 )
							ret := 0.070580
						if( diMinus > 61.5405 )
							ret := -0.769231 // sell
					if( diMinus > 63.1327 )
						if( dx <= 82.9579 )
							ret := 0.720000 // buy
						if( dx > 82.9579 )
							ret := -0.800000 // sell

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
