//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: L_Stochastic_RSI, L_Triple_EMA
// ID_model: DOTUSDT_1Day_2ST0_d4659853 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_DOTUSDT_1Day_2ST0_d4659853", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_DOTUSDT_1Day_d4659853(d, d_k, smoothK_k, k, rsi1, smoothD_d, ema12, ema3, ema13, tema, ema1, ema2)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=5, max_features=0.9,max_leaf_nodes=12, min_samples_split=5,random_state=843828734)
	if( d <= 9.79153 )
		if( tema <= 22.866 )
			ret := 0.269388
		if( tema > 22.866 )
			ret := 0.796875 // buy
	if( d > 9.79153 )
		if( tema <= 6.71859 )
			if( smoothD_d <= 92.2057 )
				ret := 0.163399
			if( smoothD_d > 92.2057 )
				ret := 0.653846
		if( tema > 6.71859 )
			if( ema13 <= 1.06027 )
				if( k <= 56.8616 )
					if( ema3 <= 7.73518 )
						ret := 0.084211
					if( ema3 > 7.73518 )
						ret := -0.650838
				if( k > 56.8616 )
					if( k <= 63.9811 )
						ret := 0.648148
					if( k > 63.9811 )
						ret := -0.296399
			if( ema13 > 1.06027 )
				if( tema <= 35.6552 )
					if( smoothD_d <= 83.1395 )
						ret := 0.164948
					if( smoothD_d > 83.1395 )
						ret := 0.826667 // buy
				if( tema > 35.6552 )
					if( smoothD_d <= 14.6903 )
						ret := 0.944444 // buy
					if( smoothD_d > 14.6903 )
						ret := -0.500000
	
    ret //return
// Define expected timeframe based on the selected interval: 1Day pine_value: D   Trigger an alert and show a label if the timeframe is incorrect
alert_message_time_wrong = "The current candle TIMEframe is WRONG: "+ str.tostring(timeframe.period) + ", CHANGE it to the CORRECT one:  1DAY !!"
if (str.tostring(timeframe.period) != "D")
    alert(alert_message_time_wrong, alert.freq_once_per_bar_close)
    label.new(bar_index -300, high+30, text = alert_message_time_wrong, style = label.style_label_down,size = size.large, color = color.red, textcolor = color.white)
    log.error(alert_message_time_wrong)

//CODE associated with the technical indicator L_Stochastic_RSI 
//@version=5
//indicator title="Stochastic RSI", shorttitle="Stoch RSI", format=format.price, precision=2, timeframe="", timeframe_gaps=true)
smoothK = input.int(3, "K", minval=1)
smoothD = input.int(3, "D", minval=1)

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
