//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: ADX_and_DI
// ID_model: DOTUSDT_1Day_1ADX_c4a34fc1 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_DOTUSDT_1Day_1ADX_c4a34fc1", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_DOTUSDT_1Day_c4a34fc1(dx, directionalMovementMinus, diPlus, smoothedDirectionalMovementMinus, trueRange, smoothedDirectionalMovementPlus, smoothedTrueRange, directionalMovementPlus, diMinus, adx)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=5, max_features=0.65,min_samples_leaf=4, min_samples_split=5,random_state=843828734)
	if( dx <= 63.28 )
		if( smoothedTrueRange <= 4.16746 )
			if( diMinus <= 29.4582 )
				if( adx <= 59.8253 )
					if( dx <= 14.3998 )
						ret := 0.136038
					if( dx > 14.3998 )
						ret := -0.245436
				if( adx > 59.8253 )
					if( smoothedDirectionalMovementMinus <= 0.403697 )
						ret := 0.689320
					if( smoothedDirectionalMovementMinus > 0.403697 )
						ret := -1.000000 // sell
			if( diMinus > 29.4582 )
				if( dx <= 49.5489 )
					if( adx <= 41.1768 )
						ret := 0.627451
					if( adx > 41.1768 )
						ret := 0.000000
				if( dx > 49.5489 )
					if( trueRange <= 2.27466 )
						ret := 0.134328
					if( trueRange > 2.27466 )
						ret := -0.653846
		if( smoothedTrueRange > 4.16746 )
			if( smoothedDirectionalMovementMinus <= 1.32942 )
				if( diMinus <= 21.1127 )
					if( dx <= 8.54672 )
						ret := -0.375000
					if( dx > 8.54672 )
						ret := -0.972222 // sell
				if( diMinus > 21.1127 )
					if( smoothedTrueRange <= 4.21383 )
						ret := -1.000000 // sell
					if( smoothedTrueRange > 4.21383 )
						ret := -0.200000
			if( smoothedDirectionalMovementMinus > 1.32942 )
				if( smoothedDirectionalMovementMinus <= 1.60774 )
					if( smoothedDirectionalMovementPlus <= 0.700982 )
						ret := 1.000000 // buy
					if( smoothedDirectionalMovementPlus > 0.700982 )
						ret := 0.250000
				if( smoothedDirectionalMovementMinus > 1.60774 )
					if( directionalMovementMinus <= 1.22267 )
						ret := -1.000000 // sell
					if( directionalMovementMinus > 1.22267 )
						ret := 0.200000
	if( dx > 63.28 )

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
