//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: L_Vortex_Indicator
// ID_model: DOTUSDT_1Day_1V00_cbf55c39 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_DOTUSDT_1Day_1V00_cbf55c39", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_DOTUSDT_1Day_cbf55c39(VIP, VIP_VIM, VIM)=>
	var float ret = 0  // # DecisionTreeRegressor(max_depth=5, max_features=0.6, max_leaf_nodes=12,min_samples_split=5, random_state=843828734)
	if( VIP <= 1.24267 )
		if( VIP_VIM <= 0.038964 )
			if( VIP <= 0.842532 )
				if( VIP_VIM <= -0.348299 )
					if( VIM <= 1.30903 )
						ret := -0.131488
					if( VIM > 1.30903 )
						ret := 0.739130 // buy
				if( VIP_VIM > -0.348299 )
					ret := 0.648148
			if( VIP > 0.842532 )
				if( VIP <= 0.843521 )
					ret := -1.000000 // sell
				if( VIP > 0.843521 )
					ret := -0.213225
		if( VIP_VIM > 0.038964 )
			if( VIM <= 0.975681 )
				if( VIP <= 1.03609 )
					ret := 0.550562
				if( VIP > 1.03609 )
					if( VIP <= 1.12121 )
						ret := 0.090336
					if( VIP > 1.12121 )
						ret := -0.167095
			if( VIM > 0.975681 )
				if( VIP <= 1.08327 )
					ret := 0.729730 // buy
				if( VIP > 1.08327 )
					ret := -0.272727
	if( VIP > 1.24267 )
		if( VIM <= 0.759645 )
			ret := 0.740000 // buy
		if( VIM > 0.759645 )
			ret := -1.000000 // sell
	
    ret //return
// Define expected timeframe based on the selected interval: 1Day pine_value: D   Trigger an alert and show a label if the timeframe is incorrect
alert_message_time_wrong = "The current candle TIMEframe is WRONG: "+ str.tostring(timeframe.period) + ", CHANGE it to the CORRECT one:  1DAY !!"
if (str.tostring(timeframe.period) != "D")
    alert(alert_message_time_wrong, alert.freq_once_per_bar_close)
    label.new(bar_index -300, high+30, text = alert_message_time_wrong, style = label.style_label_down,size = size.large, color = color.red, textcolor = color.white)
    log.error(alert_message_time_wrong)

//CODE associated with the technical indicator L_Vortex_Indicator 
//@version=5
//indicator title = "Vortex Indicator", shorttitle="VI", format=format.price, precision=4, timeframe="", timeframe_gaps=true)
period_ = input.int(14, title="Length", minval=2)
VMP = math.sum( math.abs( high - low[1]), period_ )

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
