//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: Ichimoku_Cloud
// ID_model: DOTUSDT_1Day_1ICH_5b418830 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_DOTUSDT_1Day_1ICH_5b418830", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_DOTUSDT_1Day_5b418830(senkou_span_a, basis_minus, chinkou_span, senkou_span_a_displaced, kinjun_sen, senkou_span_b_displaced, cross_up_tenkan_kinjunInt, senkou_span_b, cross_dn_tenkan_kinjunInt, tenkan_sen, basis_max)=>
	var float ret = 0  // # DecisionTreeRegressor(max_depth=5, max_features=0.65, max_leaf_nodes=30,random_state=843828734)
	if( senkou_span_a_displaced <= 20.2501 )
		if( senkou_span_b_displaced <= 4.97418 )
			if( chinkou_span <= 7.54134 )
				if( senkou_span_b <= 4.68605 )
					if( chinkou_span <= 4.99104 )
						ret := 0.133333
					if( chinkou_span > 4.99104 )
						ret := 0.777778 // buy
				if( senkou_span_b > 4.68605 )
					if( senkou_span_a <= 5.12156 )
						ret := -0.750000 // sell
					if( senkou_span_a > 5.12156 )
						ret := -0.086207
			if( chinkou_span > 7.54134 )
				if( senkou_span_a <= 7.46985 )
					if( cross_up_tenkan_kinjunInt <= 0.5 )
						ret := 0.892157 // buy
					if( cross_up_tenkan_kinjunInt > 0.5 )
						ret := 0.000000
				if( senkou_span_a > 7.46985 )
					if( chinkou_span <= 17.7371 )
						ret := -0.571429
					if( chinkou_span > 17.7371 )
						ret := 1.000000 // buy
		if( senkou_span_b_displaced > 4.97418 )
			if( chinkou_span <= 18.445 )
				if( tenkan_sen <= 8.17204 )
					if( chinkou_span <= 6.33734 )
						ret := -0.156951
					if( chinkou_span > 6.33734 )
						ret := 0.392617
				if( tenkan_sen > 8.17204 )
					if( senkou_span_b_displaced <= 7.78909 )
						ret := 0.258065
					if( senkou_span_b_displaced > 7.78909 )
						ret := -0.541667
			if( chinkou_span > 18.445 )
				if( senkou_span_b <= 20.1322 )
					if( kinjun_sen <= 13.244 )
						ret := 0.200000
					if( kinjun_sen > 13.244 )
						ret := 0.849315 // buy
				if( senkou_span_b > 20.1322 )
					if( basis_max <= -0.686677 )
						ret := -0.161290
					if( basis_max > -0.686677 )
						ret := 0.846154 // buy
	if( senkou_span_a_displaced > 20.2501 )

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
