//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: L_Bull_Bear_Power, L_Triple_EMA
// ID_model: FFIV_1Day_2BT0_0b798d4a Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_FFIV_1Day_2BT0_0b798d4a", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_FFIV_1Day_0b798d4a(bearPower, bbm, bbp, bullPower, BBPower_Color, ema12, ema3, ema13, tema, ema1, ema2)=>
	var float ret = 0  // # DecisionTreeRegressor(max_depth=5, max_features=0.4, max_leaf_nodes=12,min_samples_split=10, random_state=843828734)
	if( ema3 <= 206.582 )
		if( bbm <= 3.53116 )
			if( tema <= 119.436 )
				if( tema <= 94.8214 )
					if( ema3 <= 93.0328 )
						ret := 1.000000 // buy
					if( ema3 > 93.0328 )
						ret := -0.878049 // sell
				if( tema > 94.8214 )
					ret := 0.427136
			if( tema > 119.436 )
				ret := -0.060950
		if( bbm > 3.53116 )
			if( ema2 <= 119.922 )
				ret := 0.884058 // buy
			if( ema2 > 119.922 )
				if( tema <= 123.118 )
					ret := -0.653846
				if( tema > 123.118 )
					if( bullPower <= 13.6127 )
						ret := 0.229870
					if( bullPower > 13.6127 )
						ret := -0.444444
	if( ema3 > 206.582 )
		if( ema3 <= 231.485 )
			if( ema2 <= 210.156 )
				ret := -0.777778 // sell
			if( ema2 > 210.156 )
				if( ema12 <= 5.55098 )
					ret := 0.288889
				if( ema12 > 5.55098 )
					ret := -0.900000 // sell
		if( ema3 > 231.485 )
			ret := -0.911765 // sell
	
    ret //return
// Define expected timeframe based on the selected interval: 1Day pine_value: D   Trigger an alert and show a label if the timeframe is incorrect
alert_message_time_wrong = "The current candle TIMEframe is WRONG: "+ str.tostring(timeframe.period) + ", CHANGE it to the CORRECT one:  1DAY !!"
if (str.tostring(timeframe.period) != "D")
    alert(alert_message_time_wrong, alert.freq_once_per_bar_close)
    label.new(bar_index -300, high+30, text = alert_message_time_wrong, style = label.style_label_down,size = size.large, color = color.red, textcolor = color.white)
    log.error(alert_message_time_wrong)

//CODE associated with the technical indicator L_Bull_Bear_Power 
//@version=5
//indicator "Bull Bear Power", shorttitle="BBP")
lengthInput = input.int(13, title="Length")
bullPower = high - ta.ema(close, lengthInput)

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
