//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: ADX_and_DI
// ID_model: FFIV_30Min_1ADX_7d375b4b Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_FFIV_30Min_1ADX_7d375b4b", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_FFIV_30Min_7d375b4b(dx, directionalMovementMinus, diPlus, smoothedDirectionalMovementMinus, trueRange, smoothedDirectionalMovementPlus, smoothedTrueRange, directionalMovementPlus, diMinus, adx)=>
	var float ret = 0  // # DecisionTreeRegressor(max_depth=6, max_features=0.7, min_samples_split=10,random_state=843828734)
	if( smoothedDirectionalMovementPlus <= 0.115151 )
		if( smoothedDirectionalMovementMinus <= 0.441298 )
			if( adx <= 78.0193 )
				if( adx <= 12.5321 )
					if( smoothedDirectionalMovementMinus <= 0.146095 )
						if( smoothedTrueRange <= 0.628082 )
							ret := -0.172185
						if( smoothedTrueRange > 0.628082 )
							ret := 0.727273 // buy
					if( smoothedDirectionalMovementMinus > 0.146095 )
						if( smoothedDirectionalMovementMinus <= 0.193934 )
							ret := -0.825397 // sell
						if( smoothedDirectionalMovementMinus > 0.193934 )
							ret := -0.125000
				if( adx > 12.5321 )
					if( adx <= 13.5107 )
						if( dx <= 5.8072 )
							ret := 0.000000
						if( dx > 5.8072 )
							ret := 0.662921
					if( adx > 13.5107 )
						if( trueRange <= 2.08173 )
							ret := 0.063341
						if( trueRange > 2.08173 )
							ret := 0.457317
			if( adx > 78.0193 )
				if( diMinus <= 22.6052 )
					if( smoothedTrueRange <= 0.614318 )
						if( smoothedTrueRange <= 0.349925 )
							ret := -0.181818
						if( smoothedTrueRange > 0.349925 )
							ret := 0.533333
					if( smoothedTrueRange > 0.614318 )
						ret := -1.000000 // sell
				if( diMinus > 22.6052 )
					if( smoothedTrueRange <= 1.0261 )
						if( diMinus <= 50.558 )
							ret := 0.850467 // buy
						if( diMinus > 50.558 )
							ret := -0.071429
					if( smoothedTrueRange > 1.0261 )
						ret := 0.000000
		if( smoothedDirectionalMovementMinus > 0.441298 )
			if( smoothedDirectionalMovementPlus <= 0.082093 )
				if( directionalMovementPlus <= 0.410248 )
					if( diPlus <= 6.83516 )
						if( adx <= 54.4383 )
							ret := -0.349081

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
