//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: Bollinger_RSI_Double_Strategy
// ID_model: FFIV_1Day_1BOL_4b5f4fea Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_FFIV_1Day_1BOL_4b5f4fea", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_FFIV_1Day_4b5f4fea(crossunder_rsi_bbupperInt, BBlower, dif_source_BBupper, crossover_rsi_bblowerInt, vrsi, BBupper, dif_source_BBlower)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=5, max_features=0.82,max_leaf_nodes=30, min_samples_leaf=4,random_state=843828734)
	if( BBlower <= 107.485 )
		if( dif_source_BBlower <= 97.1689 )
			if( BBlower <= 103.564 )
				if( BBlower <= 87.3818 )
					if( dif_source_BBupper <= 0.593092 )
						ret := 0.962963 // buy
					if( dif_source_BBupper > 0.593092 )
						ret := 0.333333
				if( BBlower > 87.3818 )
					if( dif_source_BBupper <= -25.3538 )
						ret := -0.777778 // sell
					if( dif_source_BBupper > -25.3538 )
						ret := 0.151832
			if( BBlower > 103.564 )
				if( vrsi <= 99.3131 )
					if( dif_source_BBupper <= -0.666167 )
						ret := 0.419355
					if( dif_source_BBupper > -0.666167 )
						ret := 0.833333 // buy
				if( vrsi > 99.3131 )
					ret := -0.363636
		if( dif_source_BBlower > 97.1689 )
			if( dif_source_BBupper <= -11.2035 )
				if( BBlower <= 101.937 )
					if( BBlower <= 101.288 )
						ret := 1.000000 // buy
					if( BBlower > 101.288 )
						ret := 0.000000
				if( BBlower > 101.937 )
					ret := -1.000000 // sell
			if( dif_source_BBupper > -11.2035 )
				if( vrsi <= 66.7638 )
					ret := -1.000000 // sell
				if( vrsi > 66.7638 )
					if( dif_source_BBupper <= 11.7253 )
						ret := -0.571429
					if( dif_source_BBupper > 11.7253 )
						ret := -1.000000 // sell
	if( BBlower > 107.485 )
		if( dif_source_BBupper <= -100.132 )
			if( dif_source_BBupper <= -104.526 )
				if( vrsi <= 20.0148 )
					ret := 1.000000 // buy
				if( vrsi > 20.0148 )
					ret := 0.833333 // buy
			if( dif_source_BBupper > -104.526 )
				ret := 1.000000 // buy
		if( dif_source_BBupper > -100.132 )

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
