//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: Bollinger_RSI_Double_Strategy
// ID_model: EPAM_1Day_1BOL_c67f036b Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_EPAM_1Day_1BOL_c67f036b", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_EPAM_1Day_c67f036b(crossunder_rsi_bbupperInt, BBlower, dif_source_BBupper, crossover_rsi_bblowerInt, vrsi, BBupper, dif_source_BBlower)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=5, max_features=0.82,max_leaf_nodes=30, random_state=843828734)
	if( BBlower <= 342.395 )
		if( dif_source_BBlower <= 19.3581 )
			if( vrsi <= 83.7007 )
				if( vrsi <= 17.079 )
					if( dif_source_BBupper <= -23.2354 )
						ret := 0.482759
					if( dif_source_BBupper > -23.2354 )
						ret := -0.608696
				if( vrsi > 17.079 )
					if( BBupper <= 336.71 )
						ret := 0.423237
					if( BBupper > 336.71 )
						ret := 0.742574 // buy
			if( vrsi > 83.7007 )
				if( vrsi <= 84.4193 )
					if( dif_source_BBlower <= 6.83605 )
						ret := -0.900000 // sell
					if( dif_source_BBlower > 6.83605 )
						ret := 0.000000
				if( vrsi > 84.4193 )
					if( BBupper <= 142.62 )
						ret := -0.200000
					if( BBupper > 142.62 )
						ret := 0.400000
		if( dif_source_BBlower > 19.3581 )
			if( BBlower <= 209.504 )
				if( dif_source_BBupper <= -495.398 )
					if( dif_source_BBupper <= -510.343 )
						ret := 1.000000 // buy
					if( dif_source_BBupper > -510.343 )
						ret := 0.625000
				if( dif_source_BBupper > -495.398 )
					if( BBupper <= 804.857 )
						ret := 0.034604
					if( BBupper > 804.857 )
						ret := -0.852941 // sell
			if( BBlower > 209.504 )
				if( dif_source_BBlower <= 60.7911 )
					if( dif_source_BBlower <= 26.9936 )
						ret := -0.425000
					if( dif_source_BBlower > 26.9936 )
						ret := -0.789855 // sell
				if( dif_source_BBlower > 60.7911 )
					if( dif_source_BBupper <= -92.1582 )
						ret := 0.597826
					if( dif_source_BBupper > -92.1582 )
						ret := -0.151235
	if( BBlower > 342.395 )

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
