//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: L_Bull_Bear_Power, L_Stochastic_RSI
// ID_model: ETSY_1Day_2BS0_46ff1abf Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_ETSY_1Day_2BS0_46ff1abf", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_ETSY_1Day_46ff1abf(bearPower, bbm, bbp, bullPower, BBPower_Color, d, d_k, smoothK_k, k, rsi1, smoothD_d)=>
	var float ret = 0  // # DecisionTreeRegressor(max_depth=5, max_features=0.75, max_leaf_nodes=12,min_samples_leaf=4, min_samples_split=10,random_state=843828734)
	if( bullPower <= 17.1878 )
		if( bearPower <= 4.3439 )
			if( bbm <= 1.99569 )
				if( rsi1 <= 23.4341 )
					ret := -0.372093
				if( rsi1 > 23.4341 )
					if( smoothD_d <= 76.3009 )
						ret := 0.207627
					if( smoothD_d > 76.3009 )
						ret := 0.032362
			if( bbm > 1.99569 )
				if( rsi1 <= 69.8316 )
					if( bullPower <= 6.08159 )
						ret := -0.095647
					if( bullPower > 6.08159 )
						ret := 0.236842
				if( rsi1 > 69.8316 )
					if( bbm <= 6.8564 )
						ret := -0.644860
					if( bbm > 6.8564 )
						ret := 0.333333
		if( bearPower > 4.3439 )
			if( k <= 86.4874 )
				if( d <= 81.5426 )
					ret := 0.028571
				if( d > 81.5426 )
					ret := -0.666667
			if( k > 86.4874 )
				ret := 0.728682 // buy
	if( bullPower > 17.1878 )
		if( k <= 27.9701 )
			ret := 0.285714
		if( k > 27.9701 )
			ret := -0.666667
	
    ret //return
// Define expected timeframe based on the selected interval: 1Day pine_value: D   Trigger an alert and show a label if the timeframe is incorrect
alert_message_time_wrong = "The current candle TIMEframe is WRONG: "+ str.tostring(timeframe.period) + ", CHANGE it to the CORRECT one:  1DAY !!"
if (str.tostring(timeframe.period) != "D")
    alert(alert_message_time_wrong, alert.freq_once_per_bar_close)
    label.new(bar_index -300, high+30, text = alert_message_time_wrong, style = label.style_label_down,size = size.large, color = color.red, textcolor = color.white)
    log.error(alert_message_time_wrong)

//CODE associated with the technical indicator L_Bull_Bear_Power 
//@version=5
//indicator "Bull Bear Power", shorttitle="BBP")
lengthInput = input.int(13, title="Length")
bullPower = high - ta.ema(close, lengthInput)

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
