//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: SuperTrend
// ID_model: MDB_1Hour_1SUP_83d07ba5 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_MDB_1Hour_1SUP_83d07ba5", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_MDB_1Hour_83d07ba5(dn1, trend, atr, atr2, buySignalInt, sellSignalInt, up1, up, dn)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=6, max_features=0.82,max_leaf_nodes=30, random_state=843828734)
	if( dn1 <= 83.9074 )
		if( up <= 72.1858 )
			if( up <= 67.6871 )
				if( dn <= 78.6183 )
					if( atr2 <= 1.5398 )
						if( dn1 <= 74.197 )
							ret := 0.735849 // buy
						if( dn1 > 74.197 )
							ret := -0.684211
					if( atr2 > 1.5398 )
						ret := 0.881818 // buy
				if( dn > 78.6183 )
					ret := -0.562500
			if( up > 67.6871 )
				if( atr2 <= 1.66972 )
					if( up <= 71.8647 )
						ret := -0.693182
					if( up > 71.8647 )
						ret := 0.437500
				if( atr2 > 1.66972 )
					if( atr2 <= 2.03066 )
						if( atr <= 1.52354 )
							ret := -0.538462
						if( atr > 1.52354 )
							ret := 0.543210
					if( atr2 > 2.03066 )
						if( up <= 69.8598 )
							ret := -0.684211
						if( up > 69.8598 )
							ret := 1.000000 // buy
		if( up > 72.1858 )
			if( up1 <= 74.4238 )
				ret := 0.843137 // buy
			if( up1 > 74.4238 )
				if( up1 <= 76.2045 )
					ret := -0.350000
				if( up1 > 76.2045 )
					ret := 0.812500 // buy
	if( dn1 > 83.9074 )
		if( dn1 <= 418.675 )
			if( dn <= 415.995 )
				if( up <= 401.648 )
					if( dn1 <= 86.5543 )
						if( atr2 <= 1.18083 )
							ret := 0.566667
						if( atr2 > 1.18083 )
							ret := -0.515528
					if( dn1 > 86.5543 )

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
