//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: ADX_and_DI
// ID_model: MELI_1Hour_1ADX_254409c2 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_MELI_1Hour_1ADX_254409c2", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_MELI_1Hour_254409c2(dx, directionalMovementMinus, diPlus, smoothedDirectionalMovementMinus, trueRange, smoothedDirectionalMovementPlus, smoothedTrueRange, directionalMovementPlus, diMinus, adx)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=6, max_features=0.5,max_leaf_nodes=30, min_samples_leaf=4,min_samples_split=10, random_state=843828734)
	if( smoothedDirectionalMovementMinus <= 8.41013 )
		if( diPlus <= 6.24992 )
			if( smoothedDirectionalMovementMinus <= 7.66607 )
				if( adx <= 68.6629 )
					if( dx <= 90.1183 )
						if( directionalMovementPlus <= 0.283383 )
							ret := -0.426523
						if( directionalMovementPlus > 0.283383 )
							ret := 0.228070
					if( dx > 90.1183 )
						ret := 0.183333
				if( adx > 68.6629 )
					ret := -0.710000 // sell
			if( smoothedDirectionalMovementMinus > 7.66607 )
				ret := 0.414286
		if( diPlus > 6.24992 )
			if( diMinus <= 46.4431 )
				if( directionalMovementPlus <= 14.2883 )
					if( diPlus <= 53.044 )
						if( diPlus <= 15.152 )
							ret := -0.079630
						if( diPlus > 15.152 )
							ret := 0.044418
					if( diPlus > 53.044 )
						if( trueRange <= 9.13495 )
							ret := 0.734463 // buy
						if( trueRange > 9.13495 )
							ret := 0.054054
				if( directionalMovementPlus > 14.2883 )
					if( diMinus <= 8.34172 )
						if( smoothedDirectionalMovementPlus <= 8.0245 )
							ret := -0.697248
						if( smoothedDirectionalMovementPlus > 8.0245 )
							ret := -0.285714
					if( diMinus > 8.34172 )
						if( directionalMovementPlus <= 97.3377 )
							ret := -0.110526
						if( directionalMovementPlus > 97.3377 )
							ret := 1.000000 // buy
			if( diMinus > 46.4431 )
				if( adx <= 61.1177 )
					if( diPlus <= 18.5923 )
						if( trueRange <= 32.0131 )
							ret := 0.461972
						if( trueRange > 32.0131 )
							ret := -0.240000
					if( diPlus > 18.5923 )
						ret := -0.268293

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
