//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: Blai5_Koncorde_v10
// ID_model: MELI_30Min_1KON_8d471520 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_MELI_30Min_1KON_8d471520", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_MELI_30Min_8d471520(verde_mean, verde, marron, media_azul, verde_media, nvi_ema, stoc, azul, verde_azul, pvi_ema, tprice, pvi, marron_mean, pvimax, azul_mean, xrsi, nvimin, media, source, oscp, nvim, xmf, pvimin, BollOsc, nvi, pvim, nvimax)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=6, max_features=0.82,max_leaf_nodes=30, random_state=843828734)
	if( nvimin <= 1.74538 )
		if( pvi <= 1.59201 )
			if( nvi_ema <= 1.8119 )
				if( nvimin <= 0.021266 )
					if( azul_mean <= 3.73419 )
						ret := 0.697917
					if( azul_mean > 3.73419 )
						if( pvim <= -0.118951 )
							ret := 0.395683
						if( pvim > -0.118951 )
							ret := -0.420690
				if( nvimin > 0.021266 )
					if( pvimax <= -0.087434 )
						ret := -0.405109
					if( pvimax > -0.087434 )
						if( verde_mean <= 202.278 )
							ret := 0.034233
						if( verde_mean > 202.278 )
							ret := 0.663934
			if( nvi_ema > 1.8119 )
				if( nvim <= 1.84214 )
					ret := 0.879630 // buy
				if( nvim > 1.84214 )
					if( nvimin <= 1.73043 )
						ret := 0.451613
					if( nvimin > 1.73043 )
						ret := -0.457143
		if( pvi > 1.59201 )
			if( nvi_ema <= 1.25069 )
				ret := 0.096774
			if( nvi_ema > 1.25069 )
				ret := -0.869048 // sell
	if( nvimin > 1.74538 )
		if( nvimax <= 2.46397 )
			if( pvim <= 1.00074 )
				if( pvi <= 0.860599 )
					if( pvim <= 0.751847 )
						ret := 0.024390
					if( pvim > 0.751847 )
						ret := -0.900000 // sell
				if( pvi > 0.860599 )
					if( stoc <= 92.0124 )
						if( tprice <= 790.294 )
							ret := 0.869565 // buy
						if( tprice > 790.294 )
							ret := 0.100066
					if( stoc > 92.0124 )
						if( verde_mean <= 100.349 )

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
