//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: Candlestick_Patterns
// ID_model: MELI_1Day_1CAN_aa78cd6e Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_MELI_1Day_1CAN_aa78cd6e", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_MELI_1Day_aa78cd6e(Bullish_EngulfingInt, HammerInt, Evening_StarInt, Dark_Cloud_CoverInt, DojiInt, Morning_StarInt, Bearish_HaramiInt, Bullish_HaramiInt, Bullish_BeltInt, Hanging_ManInt, Bearish_EngulfingInt, Bearish_KickerInt, Piercing_LineInt, Bullish_KickerInt, Shooting_StarInt, Inverted_HammerInt)=>
	var float ret = 0  // # DecisionTreeRegressor(max_depth=5, max_features=0.7, random_state=843828734)
	if( Bullish_KickerInt <= 0.5 )
		if( Inverted_HammerInt <= 0.5 )
			if( Morning_StarInt <= 0.5 )
				if( Evening_StarInt <= 0.5 )
					if( Bearish_EngulfingInt <= 0.5 )
						ret := -0.001432
					if( Bearish_EngulfingInt > 0.5 )
						ret := 0.194915
				if( Evening_StarInt > 0.5 )
					if( HammerInt <= 0.5 )
						ret := 0.440000
					if( HammerInt > 0.5 )
						ret := 0.750000 // buy
			if( Morning_StarInt > 0.5 )
				ret := 0.642857
		if( Inverted_HammerInt > 0.5 )
			if( Bearish_EngulfingInt <= 0.5 )
				if( Shooting_StarInt <= 0.5 )
					if( Bullish_HaramiInt <= 0.5 )
						ret := -0.205128
					if( Bullish_HaramiInt > 0.5 )
						ret := -0.647059
				if( Shooting_StarInt > 0.5 )
					ret := 0.384615
			if( Bearish_EngulfingInt > 0.5 )
				ret := 1.000000 // buy
	if( Bullish_KickerInt > 0.5 )
		if( Inverted_HammerInt <= 0.5 )
			if( DojiInt <= 0.5 )
				if( HammerInt <= 0.5 )
					if( Morning_StarInt <= 0.5 )
						ret := 0.333333
					if( Morning_StarInt > 0.5 )
						ret := 0.352941
				if( HammerInt > 0.5 )
					ret := 0.777778 // buy
			if( DojiInt > 0.5 )
				if( HammerInt <= 0.5 )
					ret := 1.000000 // buy
				if( HammerInt > 0.5 )
					ret := 0.000000
		if( Inverted_HammerInt > 0.5 )
			ret := 0.000000
	
    ret //return
// Define expected timeframe based on the selected interval: 1Day pine_value: D   Trigger an alert and show a label if the timeframe is incorrect
alert_message_time_wrong = "The current candle TIMEframe is WRONG: "+ str.tostring(timeframe.period) + ", CHANGE it to the CORRECT one:  1DAY !!"
if (str.tostring(timeframe.period) != "D")

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
