//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: L_Bull_Bear_Power, L_Stochastic_RSI
// ID_model: MELI_1Hour_2BS0_7c9c12a7 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_MELI_1Hour_2BS0_7c9c12a7", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_MELI_1Hour_7c9c12a7(bearPower, bbm, bbp, bullPower, BBPower_Color, d, d_k, smoothK_k, k, rsi1, smoothD_d)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=6, max_features=0.5,max_leaf_nodes=30, min_samples_split=10,random_state=843828734)
	if( bearPower <= 37.8057 )
		if( smoothD_d <= 40.0827 )
			if( smoothD_d <= 22.0627 )
				if( smoothK_k <= 34.3353 )
					if( k <= 2.16623 )
						if( bbp <= -14.7725 )
							ret := 0.014960
						if( bbp > -14.7725 )
							ret := -0.322862
					if( k > 2.16623 )
						if( rsi1 <= 16.5053 )
							ret := -0.333333
						if( rsi1 > 16.5053 )
							ret := 0.018933
				if( smoothK_k > 34.3353 )
					if( bearPower <= -8.80879 )
						if( smoothK_k <= 40.1295 )
							ret := 0.160000
						if( smoothK_k > 40.1295 )
							ret := -1.000000 // sell
					if( bearPower > -8.80879 )
						ret := 0.680412
			if( smoothD_d > 22.0627 )
				if( bearPower <= -7.97506 )
					if( d_k <= -12.1065 )
						if( bullPower <= 18.8975 )
							ret := 0.083916
						if( bullPower > 18.8975 )
							ret := -0.650000
					if( d_k > -12.1065 )
						if( bbm <= 34.8472 )
							ret := -0.267788
						if( bbm > 34.8472 )
							ret := -0.682243
				if( bearPower > -7.97506 )
					if( rsi1 <= 38.5205 )
						if( d_k <= 8.65887 )
							ret := 0.386207
						if( d_k > 8.65887 )
							ret := -0.633333
					if( rsi1 > 38.5205 )
						if( bbp <= 22.0203 )
							ret := -0.172594
						if( bbp > 22.0203 )
							ret := 0.103976
		if( smoothD_d > 40.0827 )
			if( bbm <= 41.0992 )
				if( d_k <= 22.3918 )

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
