//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: ADX_and_DI
// ID_model: META_1Day_1ADX_125fd688 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_META_1Day_1ADX_125fd688", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_META_1Day_125fd688(dx, directionalMovementMinus, diPlus, smoothedDirectionalMovementMinus, trueRange, smoothedDirectionalMovementPlus, smoothedTrueRange, directionalMovementPlus, diMinus, adx)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=5, max_features=0.9,min_samples_split=5, random_state=843828734)
	if( smoothedDirectionalMovementMinus <= 4.11071 )
		if( adx <= 33.4786 )
			if( diPlus <= 11.2507 )
				if( diMinus <= 43.2202 )
					if( directionalMovementPlus <= 0.54429 )
						ret := 0.876289 // buy
					if( directionalMovementPlus > 0.54429 )
						ret := 0.120000
				if( diMinus > 43.2202 )
					if( smoothedTrueRange <= 6.09987 )
						ret := 0.000000
					if( smoothedTrueRange > 6.09987 )
						ret := -1.000000 // sell
			if( diPlus > 11.2507 )
				if( diMinus <= 38.2552 )
					if( diMinus <= 31.4994 )
						ret := -0.153425
					if( diMinus > 31.4994 )
						ret := 0.528205
				if( diMinus > 38.2552 )
					if( dx <= 57.6693 )
						ret := -0.900000 // sell
					if( dx > 57.6693 )
						ret := 1.000000 // buy
		if( adx > 33.4786 )
			if( trueRange <= 13.3422 )
				if( dx <= 71.4901 )
					if( smoothedTrueRange <= 7.11904 )
						ret := 0.154150
					if( smoothedTrueRange > 7.11904 )
						ret := 0.410367
				if( dx > 71.4901 )
					if( smoothedDirectionalMovementMinus <= 0.216918 )
						ret := 0.137931
					if( smoothedDirectionalMovementMinus > 0.216918 )
						ret := -0.692308
			if( trueRange > 13.3422 )
				if( diPlus <= 40.7189 )
					if( smoothedTrueRange <= 8.0228 )
						ret := 0.000000
					if( smoothedTrueRange > 8.0228 )
						ret := -0.666667
				if( diPlus > 40.7189 )
					if( directionalMovementPlus <= 2.2 )
						ret := 1.000000 // buy
					if( directionalMovementPlus > 2.2 )
						ret := 0.000000
	if( smoothedDirectionalMovementMinus > 4.11071 )

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
