//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: Ichimoku_Cloud
// ID_model: SOLUSDT_1Day_1ICH_5c7476e4 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_SOLUSDT_1Day_1ICH_5c7476e4", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_SOLUSDT_1Day_5c7476e4(tenkan_sen, basis_minus, cross_up_tenkan_kinjunInt, senkou_span_a, cross_dn_tenkan_kinjunInt, senkou_span_b, chinkou_span, senkou_span_a_displaced, senkou_span_b_displaced, kinjun_sen, basis_max)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=5, max_features=0.65,min_samples_leaf=4, min_samples_split=5,random_state=843828734)
	if( senkou_span_a_displaced <= 30.9995 )
		if( basis_max <= -0.195859 )
			if( chinkou_span <= 46.081 )
				if( senkou_span_a <= 19.7989 )
					if( senkou_span_b <= 7.46515 )
						ret := 0.876712 // buy
					if( senkou_span_b > 7.46515 )
						ret := 0.576271
				if( senkou_span_a > 19.7989 )
					if( senkou_span_b_displaced <= 12.645 )
						ret := 0.388889
					if( senkou_span_b_displaced > 12.645 )
						ret := 0.000000
			if( chinkou_span > 46.081 )
				if( kinjun_sen <= 47.833 )
					if( senkou_span_a_displaced <= 22.3046 )
						ret := 0.870000 // buy
					if( senkou_span_a_displaced > 22.3046 )
						ret := 0.982143 // buy
				if( kinjun_sen > 47.833 )
					if( tenkan_sen <= 61.757 )
						ret := 0.214286
					if( tenkan_sen > 61.757 )
						ret := 1.000000 // buy
		if( basis_max > -0.195859 )
			if( tenkan_sen <= 1.61932 )
				ret := 1.000000 // buy
			if( tenkan_sen > 1.61932 )
				if( chinkou_span <= 20.5158 )
					if( senkou_span_b_displaced <= 1.94131 )
						ret := 0.866667 // buy
					if( senkou_span_b_displaced > 1.94131 )
						ret := -0.524590
				if( chinkou_span > 20.5158 )
					if( senkou_span_a_displaced <= 16.9683 )
						ret := 0.744186 // buy
					if( senkou_span_a_displaced > 16.9683 )
						ret := 0.126214
	if( senkou_span_a_displaced > 30.9995 )
		if( basis_minus <= -19.2311 )
			if( chinkou_span <= 98.6043 )
				if( chinkou_span <= 38.8233 )
					if( basis_max <= 8.1968 )
						ret := -0.952381 // sell
					if( basis_max > 8.1968 )
						ret := -0.285714
				if( chinkou_span > 38.8233 )
					if( chinkou_span <= 39.3384 )

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
