//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: ADX_and_DI
// ID_model: SHOP_1Day_1ADX_75ac5f4d Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_SHOP_1Day_1ADX_75ac5f4d", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_SHOP_1Day_75ac5f4d(dx, diMinus, directionalMovementMinus, adx, diPlus, directionalMovementPlus, smoothedTrueRange, smoothedDirectionalMovementPlus, smoothedDirectionalMovementMinus, trueRange)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=5, max_features=0.5,max_leaf_nodes=30, min_samples_split=10,random_state=843828734)
	if( adx <= 28.0959 )
		if( directionalMovementMinus <= 0.009327 )
			if( directionalMovementPlus <= 0.855 )
				if( dx <= 15.0728 )
					if( trueRange <= 1.9011 )
						ret := 0.194444
					if( trueRange > 1.9011 )
						ret := -0.363636
				if( dx > 15.0728 )
					if( smoothedDirectionalMovementPlus <= 0.345357 )
						ret := 0.850000 // buy
					if( smoothedDirectionalMovementPlus > 0.345357 )
						ret := 0.213793
			if( directionalMovementPlus > 0.855 )
				if( smoothedDirectionalMovementPlus <= 8.33168 )
					if( dx <= 44.9299 )
						ret := -0.322807
					if( dx > 44.9299 )
						ret := 0.472222
				if( smoothedDirectionalMovementPlus > 8.33168 )
					if( diMinus <= 24.8988 )
						ret := 0.231343
					if( diMinus > 24.8988 )
						ret := -0.766667 // sell
		if( directionalMovementMinus > 0.009327 )
			if( directionalMovementMinus <= 32.8355 )
				if( smoothedTrueRange <= 70.545 )
					if( diPlus <= 18.0884 )
						ret := 0.723270 // buy
					if( diPlus > 18.0884 )
						ret := 0.348442
				if( smoothedTrueRange > 70.545 )
					if( diPlus <= 17.5452 )
						ret := 0.666667
					if( diPlus > 17.5452 )
						ret := -1.000000 // sell
			if( directionalMovementMinus > 32.8355 )
				if( diPlus <= 28.2618 )
					if( smoothedDirectionalMovementPlus <= 16.2161 )
						ret := -0.500000
					if( smoothedDirectionalMovementPlus > 16.2161 )
						ret := 0.714286 // buy
				if( diPlus > 28.2618 )
					ret := 0.666667
	if( adx > 28.0959 )
		if( smoothedDirectionalMovementPlus <= 1.32255 )
			if( trueRange <= 6.59075 )
				if( diMinus <= 32.339 )

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
