//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: L_Vortex_Indicator
// ID_model: SHOP_1Day_1V00_fed01444 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_SHOP_1Day_1V00_fed01444", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_SHOP_1Day_fed01444(VIP_VIM, VIM, VIP)=>
	var float ret = 0  // # DecisionTreeRegressor(max_depth=5, max_features=sqrt, max_leaf_nodes=12,min_samples_leaf=4, min_samples_split=5,random_state=843828734)
	if( VIP_VIM <= 0.248874 )
		if( VIM <= 1.40932 )
			if( VIP_VIM <= -0.568643 )
				ret := -0.395683
			if( VIP_VIM > -0.568643 )
				if( VIP_VIM <= -0.433934 )
					if( VIP <= 0.795791 )
						ret := 0.602941
					if( VIP > 0.795791 )
						ret := 0.117647
				if( VIP_VIM > -0.433934 )
					if( VIP_VIM <= -0.217824 )
						ret := -0.176000
					if( VIP_VIM > -0.217824 )
						ret := 0.113032
		if( VIM > 1.40932 )
			ret := 0.686567
	if( VIP_VIM > 0.248874 )
		if( VIP <= 1.24489 )
			if( VIP_VIM <= 0.280852 )
				ret := -0.663866
			if( VIP_VIM > 0.280852 )
				ret := -0.096838
		if( VIP > 1.24489 )
			if( VIP_VIM <= 0.520114 )
				if( VIM <= 0.792953 )
					ret := 0.283019
				if( VIM > 0.792953 )
					if( VIM <= 0.896754 )
						ret := -0.568421
					if( VIM > 0.896754 )
						ret := 0.020408
			if( VIP_VIM > 0.520114 )
				ret := 0.161290
	
    ret //return
// Define expected timeframe based on the selected interval: 1Day pine_value: D   Trigger an alert and show a label if the timeframe is incorrect
alert_message_time_wrong = "The current candle TIMEframe is WRONG: "+ str.tostring(timeframe.period) + ", CHANGE it to the CORRECT one:  1DAY !!"
if (str.tostring(timeframe.period) != "D")
    alert(alert_message_time_wrong, alert.freq_once_per_bar_close)
    label.new(bar_index -300, high+30, text = alert_message_time_wrong, style = label.style_label_down,size = size.large, color = color.red, textcolor = color.white)
    log.error(alert_message_time_wrong)

//CODE associated with the technical indicator L_Vortex_Indicator 
//@version=5
//indicator title = "Vortex Indicator", shorttitle="VI", format=format.price, precision=4, timeframe="", timeframe_gaps=true)
period_ = input.int(14, title="Length", minval=2)
VMP = math.sum( math.abs( high - low[1]), period_ )

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
