//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: ADX_and_DI
// ID_model: SPOT_1Day_1ADX_166eb640 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_SPOT_1Day_1ADX_166eb640", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_SPOT_1Day_166eb640(dx, diMinus, directionalMovementMinus, adx, diPlus, directionalMovementPlus, smoothedTrueRange, smoothedDirectionalMovementPlus, smoothedDirectionalMovementMinus, trueRange)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=5, max_features=0.82,max_leaf_nodes=30, min_samples_leaf=4,random_state=843828734)
	if( trueRange <= 17.8657 )
		if( smoothedTrueRange <= 4.38133 )
			if( adx <= 16.3856 )
				if( dx <= 9.22636 )
					if( directionalMovementMinus <= 0.636488 )
						ret := 0.833333 // buy
					if( directionalMovementMinus > 0.636488 )
						ret := 1.000000 // buy
				if( dx > 9.22636 )
					if( diMinus <= 23.875 )
						ret := 1.000000 // buy
					if( diMinus > 23.875 )
						ret := 0.000000
			if( adx > 16.3856 )
				if( adx <= 25.8652 )
					if( directionalMovementPlus <= 1.03192 )
						ret := -0.107143
					if( directionalMovementPlus > 1.03192 )
						ret := -0.750000 // sell
				if( adx > 25.8652 )
					if( dx <= 43.046 )
						ret := 0.147727
					if( dx > 43.046 )
						ret := 0.611650
		if( smoothedTrueRange > 4.38133 )
			if( adx <= 45.2437 )
				if( diPlus <= 38.5618 )
					if( diMinus <= 38.1909 )
						ret := -0.019985
					if( diMinus > 38.1909 )
						ret := 0.546667
				if( diPlus > 38.5618 )
					if( trueRange <= 11.6845 )
						ret := 0.565217
					if( trueRange > 11.6845 )
						ret := 1.000000 // buy
			if( adx > 45.2437 )
				if( diMinus <= 11.8035 )
					if( diPlus <= 38.1877 )
						ret := -0.883721 // sell
					if( diPlus > 38.1877 )
						ret := -0.188679
				if( diMinus > 11.8035 )
					if( diMinus <= 34.1018 )
						ret := 0.110294
					if( diMinus > 34.1018 )
						ret := -0.575758
	if( trueRange > 17.8657 )

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
