//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: Bollinger_RSI_Double_Strategy
// ID_model: PINS_1Day_1BOL_3ed8a217 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_PINS_1Day_1BOL_3ed8a217", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_PINS_1Day_3ed8a217(crossunder_rsi_bbupperInt, BBlower, dif_source_BBupper, crossover_rsi_bblowerInt, vrsi, BBupper, dif_source_BBlower)=>
	var float ret = 0  // # DecisionTreeRegressor(max_depth=5, max_features=0.65, random_state=843828734)
	if( BBlower <= 14.4626 )
		if( vrsi <= 42.8156 )
			if( dif_source_BBupper <= -51.1611 )
				if( BBupper <= 72.3623 )
					ret := 1.000000 // buy
				if( BBupper > 72.3623 )
					if( dif_source_BBlower <= 9.08727 )
						ret := 0.500000
					if( dif_source_BBlower > 9.08727 )
						ret := -0.727273 // sell
			if( dif_source_BBupper > -51.1611 )
				if( dif_source_BBlower <= 67.891 )
					if( dif_source_BBupper <= 2.31056 )
						ret := 0.863874 // buy
					if( dif_source_BBupper > 2.31056 )
						ret := 0.000000
				if( dif_source_BBlower > 67.891 )
					if( BBlower <= 5.01798 )
						ret := 0.000000
					if( BBlower > 5.01798 )
						ret := -1.000000 // sell
		if( vrsi > 42.8156 )
			if( BBupper <= 46.0333 )
				if( dif_source_BBlower <= 9.47599 )
					if( BBupper <= 35.1541 )
						ret := 0.842857 // buy
					if( BBupper > 35.1541 )
						ret := -0.142857
				if( dif_source_BBlower > 9.47599 )
					if( dif_source_BBlower <= 26.8416 )
						ret := -0.098592
					if( dif_source_BBlower > 26.8416 )
						ret := 0.755556 // buy
			if( BBupper > 46.0333 )
				if( vrsi <= 78.3732 )
					if( BBlower <= 8.849 )
						ret := -0.222222
					if( BBlower > 8.849 )
						ret := -0.719298 // sell
				if( vrsi > 78.3732 )
					if( BBupper <= 66.6897 )
						ret := -0.588235
					if( BBupper > 66.6897 )
						ret := 0.812500 // buy
	if( BBlower > 14.4626 )
		if( BBlower <= 15.6906 )
			if( vrsi <= 4.43634 )
				ret := 1.000000 // buy

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
