//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: Blai5_Koncorde_v10
// ID_model: PINS_15Min_1KON_b0f4678e Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_PINS_15Min_1KON_b0f4678e", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_PINS_15Min_b0f4678e(verde_mean, verde, marron, media_azul, verde_media, nvi_ema, stoc, azul, verde_azul, pvi_ema, tprice, pvi, marron_mean, pvimax, azul_mean, xrsi, nvimin, media, source, oscp, nvim, xmf, pvimin, BollOsc, nvi, pvim, nvimax)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=8,max_features=sqrt, min_samples_leaf=7,random_state=843828734)
	if( stoc <= 27.5695 )
		if( xrsi <= 26.201 )
			if( nvimax <= 1.91542 )
				if( pvim <= -0.651561 )
					if( verde_media <= -85.2993 )
						if( verde_media <= -132.144 )
							if( media <= 37.2132 )
								ret := -0.312500
							if( media > 37.2132 )
								ret := 0.833333 // buy
						if( verde_media > -132.144 )
							if( stoc <= 22.268 )
								if( azul_mean <= -13.4025 )
									ret := 0.333333
								if( azul_mean > -13.4025 )
									ret := 0.964912 // buy
							if( stoc > 22.268 )
								ret := 0.363636
					if( verde_media > -85.2993 )
						if( media_azul <= 66.0626 )
							if( media_azul <= 15.4338 )
								if( BollOsc <= -61.491 )
									ret := -0.888889 // sell
								if( BollOsc > -61.491 )
									ret := -0.057851
							if( media_azul > 15.4338 )
								if( marron_mean <= -2.02684 )
									ret := -0.011111
								if( marron_mean > -2.02684 )
									ret := 0.334375
						if( media_azul > 66.0626 )
							if( nvim <= 1.78985 )
								if( nvi <= 1.63453 )
									ret := -1.000000 // sell
								if( nvi > 1.63453 )
									ret := -0.500000
							if( nvim > 1.78985 )
								ret := 0.277778
				if( pvim > -0.651561 )
					if( verde_media <= -59.3553 )
						if( pvi <= -0.269131 )
							if( oscp <= -21.1016 )
								if( source <= 17.9596 )
									ret := 0.076923
								if( source > 17.9596 )
									ret := 0.783333 // buy
							if( oscp > -21.1016 )
								ret := -0.066667

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
