//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: Ichimoku_Cloud
// ID_model: RUN_1Day_1ICH_6cae8f8c Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_RUN_1Day_1ICH_6cae8f8c", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_RUN_1Day_6cae8f8c(tenkan_sen, basis_minus, cross_up_tenkan_kinjunInt, senkou_span_a, cross_dn_tenkan_kinjunInt, senkou_span_b, chinkou_span, senkou_span_a_displaced, senkou_span_b_displaced, kinjun_sen, basis_max)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=5, max_features=0.82,max_leaf_nodes=30, min_samples_leaf=4,random_state=843828734)
	if( tenkan_sen <= 24.3321 )
		if( chinkou_span <= 21.6683 )
			if( tenkan_sen <= 18.8176 )
				if( chinkou_span <= 7.18731 )
					if( tenkan_sen <= 5.98 )
						ret := 0.159533
					if( tenkan_sen > 5.98 )
						ret := -0.570248
				if( chinkou_span > 7.18731 )
					if( senkou_span_a <= 13.0407 )
						ret := 0.582117
					if( senkou_span_a > 13.0407 )
						ret := -0.022034
			if( tenkan_sen > 18.8176 )
				if( basis_minus <= -1.77625 )
					if( basis_max <= 1.01569 )
						ret := 0.533333
					if( basis_max > 1.01569 )
						ret := 0.000000
				if( basis_minus > -1.77625 )
					if( kinjun_sen <= 19.5095 )
						ret := -0.581818
					if( kinjun_sen > 19.5095 )
						ret := -0.931298 // sell
		if( chinkou_span > 21.6683 )
			if( senkou_span_a <= 24.8087 )
				if( senkou_span_a_displaced <= 13.5103 )
					if( chinkou_span <= 27.22 )
						ret := 1.000000 // buy
					if( chinkou_span > 27.22 )
						ret := 0.352941
				if( senkou_span_a_displaced > 13.5103 )
					if( basis_max <= 0.650282 )
						ret := 0.972477 // buy
					if( basis_max > 0.650282 )
						ret := 0.811594 // buy
			if( senkou_span_a > 24.8087 )
				if( chinkou_span <= 23.516 )
					ret := -1.000000 // sell
				if( chinkou_span > 23.516 )
					if( chinkou_span <= 28.05 )
						ret := 1.000000 // buy
					if( chinkou_span > 28.05 )
						ret := 0.333333
	if( tenkan_sen > 24.3321 )
		if( chinkou_span <= 43.7408 )
			if( senkou_span_b_displaced <= 26.435 )
				if( kinjun_sen <= 29.9582 )

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
