//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: Bollinger_RSI_Double_Strategy
// ID_model: RUN_1Hour_1BOL_c24267ec Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_RUN_1Hour_1BOL_c24267ec", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_RUN_1Hour_c24267ec(crossunder_rsi_bbupperInt, BBlower, dif_source_BBlower, dif_source_BBupper, vrsi, BBupper, crossover_rsi_bblowerInt)=>
	var float ret = 0  // # DecisionTreeRegressor(max_depth=6, max_features=0.7, min_samples_split=10,random_state=843828734)
	if( BBlower <= 9.41146 )
		if( dif_source_BBlower <= 3.75322 )
			if( BBlower <= 8.29644 )
				if( dif_source_BBupper <= -0.813705 )
					if( vrsi <= 53.7839 )
						if( vrsi <= 26.606 )
							ret := 0.840000 // buy
						if( vrsi > 26.606 )
							ret := 0.181818
					if( vrsi > 53.7839 )
						if( vrsi <= 64.9241 )
							ret := 0.923077 // buy
						if( vrsi > 64.9241 )
							ret := 0.551020
				if( dif_source_BBupper > -0.813705 )
					ret := -0.400000
			if( BBlower > 8.29644 )
				if( BBupper <= 13.358 )
					if( vrsi <= 83.9726 )
						if( vrsi <= 59.5275 )
							ret := 0.042618
						if( vrsi > 59.5275 )
							ret := 0.494505
					if( vrsi > 83.9726 )
						if( vrsi <= 90.3394 )
							ret := -0.714286 // sell
						if( vrsi > 90.3394 )
							ret := 0.112676
				if( BBupper > 13.358 )
					if( dif_source_BBlower <= 2.93971 )
						if( vrsi <= 89.2657 )
							ret := 0.624454
						if( vrsi > 89.2657 )
							ret := -0.391304
					if( dif_source_BBlower > 2.93971 )
						if( BBlower <= 9.23901 )
							ret := -0.866667 // sell
						if( BBlower > 9.23901 )
							ret := 0.000000
		if( dif_source_BBlower > 3.75322 )
			if( BBupper <= 13.3754 )
				if( vrsi <= 37.7365 )
					ret := 0.800000 // buy
				if( vrsi > 37.7365 )
					if( dif_source_BBupper <= 0.083135 )
						if( BBlower <= 9.19776 )
							ret := -0.864198 // sell
						if( BBlower > 9.19776 )

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
