//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: Candlestick_Patterns
// ID_model: RUN_1Day_1CAN_e879c989 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_RUN_1Day_1CAN_e879c989", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_RUN_1Day_e879c989(Inverted_HammerInt, Hanging_ManInt, Bearish_KickerInt, Bullish_EngulfingInt, Bearish_HaramiInt, Bullish_HaramiInt, Dark_Cloud_CoverInt, Bearish_EngulfingInt, Bullish_KickerInt, DojiInt, Evening_StarInt, Piercing_LineInt, Morning_StarInt, Bullish_BeltInt, HammerInt, Shooting_StarInt)=>
	var float ret = 0  // # DecisionTreeRegressor(max_depth=5, max_features=0.7, max_leaf_nodes=12,random_state=843828734)
	if( HammerInt <= 0.5 )
		if( Dark_Cloud_CoverInt <= 0.5 )
			if( Bearish_KickerInt <= 0.5 )
				if( Evening_StarInt <= 0.5 )
					if( Bullish_EngulfingInt <= 0.5 )
						ret := -0.056071
					if( Bullish_EngulfingInt > 0.5 )
						ret := 0.210843
				if( Evening_StarInt > 0.5 )
					if( Inverted_HammerInt <= 0.5 )
						ret := -0.710526 // sell
					if( Inverted_HammerInt > 0.5 )
						ret := 0.000000
			if( Bearish_KickerInt > 0.5 )
				if( Evening_StarInt <= 0.5 )
					ret := 0.527778
				if( Evening_StarInt > 0.5 )
					ret := 0.733333 // buy
		if( Dark_Cloud_CoverInt > 0.5 )
			ret := 0.625000
	if( HammerInt > 0.5 )
		if( Bullish_KickerInt <= 0.5 )
			if( Bullish_HaramiInt <= 0.5 )
				if( Bearish_HaramiInt <= 0.5 )
					ret := 0.270936
				if( Bearish_HaramiInt > 0.5 )
					if( DojiInt <= 0.5 )
						ret := 0.625000
					if( DojiInt > 0.5 )
						ret := 0.000000
			if( Bullish_HaramiInt > 0.5 )
				ret := -0.111111
		if( Bullish_KickerInt > 0.5 )
			ret := 0.625000
	
    ret //return
// Define expected timeframe based on the selected interval: 1Day pine_value: D   Trigger an alert and show a label if the timeframe is incorrect
alert_message_time_wrong = "The current candle TIMEframe is WRONG: "+ str.tostring(timeframe.period) + ", CHANGE it to the CORRECT one:  1DAY !!"
if (str.tostring(timeframe.period) != "D")
    alert(alert_message_time_wrong, alert.freq_once_per_bar_close)
    label.new(bar_index -300, high+30, text = alert_message_time_wrong, style = label.style_label_down,size = size.large, color = color.red, textcolor = color.white)
    log.error(alert_message_time_wrong)

//CODE associated with the technical indicator Candlestick_Patterns 
//@version=5
//indicator title="Candles", overlay=true)

DojiSize = input.float(0.05, minval=0.01, title="Doji size")

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
