//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: ADX_and_DI
// ID_model: QCOM_1Hour_1ADX_84ad0b21 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_QCOM_1Hour_1ADX_84ad0b21", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_QCOM_1Hour_84ad0b21(directionalMovementPlus, directionalMovementMinus, trueRange, smoothedDirectionalMovementPlus, smoothedDirectionalMovementMinus, diPlus, diMinus, smoothedTrueRange, adx, dx)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=5, max_features=0.65,max_leaf_nodes=30, random_state=843828734)
	if( diPlus <= 16.0256 )
		if( adx <= 64.1456 )
			if( diPlus <= 3.36392 )
				if( diMinus <= 42.2285 )
					if( directionalMovementPlus <= 0.231709 )
						ret := 0.629371
					if( directionalMovementPlus > 0.231709 )
						ret := -0.857143 // sell
				if( diMinus > 42.2285 )
					if( directionalMovementMinus <= 0.15794 )
						ret := -0.400000
					if( directionalMovementMinus > 0.15794 )
						ret := 0.307692
			if( diPlus > 3.36392 )
				if( smoothedDirectionalMovementPlus <= 0.284464 )
					if( diMinus <= 25.0989 )
						ret := 0.012733
					if( diMinus > 25.0989 )
						ret := -0.137332
				if( smoothedDirectionalMovementPlus > 0.284464 )
					if( smoothedDirectionalMovementMinus <= 0.650266 )
						ret := -0.555556
					if( smoothedDirectionalMovementMinus > 0.650266 )
						ret := 0.676471
		if( adx > 64.1456 )
			if( diPlus <= 11.9352 )
				if( directionalMovementMinus <= 0.297405 )
					if( smoothedTrueRange <= 1.64667 )
						ret := 0.121528
					if( smoothedTrueRange > 1.64667 )
						ret := -0.505618
				if( directionalMovementMinus > 0.297405 )
					if( dx <= 56.9246 )
						ret := -0.600000
					if( dx > 56.9246 )
						ret := 0.537572
			if( diPlus > 11.9352 )
				if( diPlus <= 15.3424 )
					if( trueRange <= 1.34328 )
						ret := 0.388889
					if( trueRange > 1.34328 )
						ret := 0.893939 // buy
				if( diPlus > 15.3424 )
					ret := -0.454545
	if( diPlus > 16.0256 )
		if( adx <= 53.4286 )
			if( diMinus <= 29.805 )
				if( smoothedDirectionalMovementMinus <= 0.18331 )

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
