//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: L_Triple_EMA, L_Vortex_Indicator
// ID_model: UBER_30Min_2TV0_308f0475 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_UBER_30Min_2TV0_308f0475", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_UBER_30Min_308f0475(ema2, ema1, ema12, ema3, ema13, tema, VIP, VIP_VIM, VIM)=>
	var float ret = 0  // # DecisionTreeRegressor(max_depth=6, max_features=0.7, min_samples_split=10,random_state=843828734)
	if( VIP <= 0.682444 )
		if( ema12 <= -0.476311 )
			if( ema1 <= 30.9184 )
				if( VIP_VIM <= -0.89985 )
					ret := 0.000000
				if( VIP_VIM > -0.89985 )
					if( ema3 <= 23.2403 )
						ret := 0.846154 // buy
					if( ema3 > 23.2403 )
						ret := 1.000000 // buy
			if( ema1 > 30.9184 )
				if( ema13 <= -1.077 )
					if( ema12 <= -0.748924 )
						if( ema12 <= -1.08792 )
							ret := -0.777778 // sell
						if( ema12 > -1.08792 )
							ret := 0.445545
					if( ema12 > -0.748924 )
						if( ema1 <= 33.4438 )
							ret := 0.769231 // buy
						if( ema1 > 33.4438 )
							ret := -0.322917
				if( ema13 > -1.077 )
					if( tema <= 34.8204 )
						if( ema13 <= -0.891565 )
							ret := 0.448980
						if( ema13 > -0.891565 )
							ret := -0.714286 // sell
					if( tema > 34.8204 )
						if( VIP <= 0.530514 )
							ret := -0.307692
						if( VIP > 0.530514 )
							ret := 0.714286 // buy
		if( ema12 > -0.476311 )
			if( ema1 <= 37.8696 )
				if( tema <= 32.1524 )
					if( tema <= 21.305 )
						if( VIP_VIM <= -0.746986 )
							ret := 0.800000 // buy
						if( VIP_VIM > -0.746986 )
							ret := -0.909091 // sell
					if( tema > 21.305 )
						if( ema2 <= 27.6516 )
							ret := 0.525253
						if( ema2 > 27.6516 )
							ret := 0.102564
				if( tema > 32.1524 )
					if( VIP_VIM <= -0.520706 )

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
