//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: ADX_and_DI
// ID_model: UBER_1Hour_1ADX_3e052357 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_UBER_1Hour_1ADX_3e052357", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_UBER_1Hour_3e052357(directionalMovementPlus, directionalMovementMinus, trueRange, smoothedDirectionalMovementPlus, smoothedDirectionalMovementMinus, diPlus, diMinus, smoothedTrueRange, adx, dx)=>
	var float ret = 0  // # DecisionTreeRegressor(max_depth=6, max_features=0.7, min_samples_split=10,random_state=843828734)
	if( smoothedDirectionalMovementMinus <= 0.067973 )
		if( smoothedTrueRange <= 0.692593 )
			if( trueRange <= 1.17803 )
				if( adx <= 55.8142 )
					if( diPlus <= 20.0266 )
						if( adx <= 14.904 )
							ret := 0.187192
						if( adx > 14.904 )
							ret := -0.124836
					if( diPlus > 20.0266 )
						if( dx <= 46.8844 )
							ret := 0.155720
						if( dx > 46.8844 )
							ret := 0.060285
				if( adx > 55.8142 )
					if( diPlus <= 13.1805 )
						if( smoothedTrueRange <= 0.282213 )
							ret := 0.765957 // buy
						if( smoothedTrueRange > 0.282213 )
							ret := 0.200000
					if( diPlus > 13.1805 )
						if( diMinus <= 2.94217 )
							ret := 0.281588
						if( diMinus > 2.94217 )
							ret := -0.149515
			if( trueRange > 1.17803 )
				if( adx <= 26.548 )
					if( adx <= 17.8642 )
						ret := 0.000000
					if( adx > 17.8642 )
						if( trueRange <= 1.2313 )
							ret := -0.250000
						if( trueRange > 1.2313 )
							ret := -0.974359 // sell
				if( adx > 26.548 )
					if( dx <= 67.7436 )
						if( smoothedDirectionalMovementPlus <= 0.221078 )
							ret := -0.025000
						if( smoothedDirectionalMovementPlus > 0.221078 )
							ret := 0.833333 // buy
					if( dx > 67.7436 )
						if( diPlus <= 41.4421 )
							ret := 0.300000
						if( diPlus > 41.4421 )
							ret := -0.537313
		if( smoothedTrueRange > 0.692593 )
			if( adx <= 41.2111 )
				if( smoothedDirectionalMovementPlus <= 0.306898 )

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
