//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: ADX_and_DI
// ID_model: UBER_1Day_1ADX_c3f76ae8 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_UBER_1Day_1ADX_c3f76ae8", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_UBER_1Day_c3f76ae8(directionalMovementPlus, directionalMovementMinus, trueRange, smoothedDirectionalMovementPlus, smoothedDirectionalMovementMinus, diPlus, diMinus, smoothedTrueRange, adx, dx)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=5, max_features=0.9,min_samples_leaf=7, random_state=843828734)
	if( smoothedDirectionalMovementPlus <= 0.223067 )
		if( diMinus <= 41.1917 )
			if( smoothedDirectionalMovementMinus <= 0.650575 )
				if( adx <= 19.1059 )
					ret := 0.000000
				if( adx > 19.1059 )
					if( smoothedDirectionalMovementMinus <= 0.58191 )
						ret := 0.515924
					if( smoothedDirectionalMovementMinus > 0.58191 )
						ret := 0.954545 // buy
			if( smoothedDirectionalMovementMinus > 0.650575 )
				if( adx <= 66.9543 )
					if( trueRange <= 2.37781 )
						ret := -0.051282
					if( trueRange > 2.37781 )
						ret := -0.862069 // sell
				if( adx > 66.9543 )
					ret := 1.000000 // buy
		if( diMinus > 41.1917 )
			if( trueRange <= 3.2091 )
				if( diPlus <= 12.0489 )
					if( adx <= 34.4871 )
						ret := 0.750000 // buy
					if( adx > 34.4871 )
						ret := 0.944444 // buy
				if( diPlus > 12.0489 )
					ret := 0.428571
			if( trueRange > 3.2091 )
				if( dx <= 85.9373 )
					ret := -0.125000
				if( dx > 85.9373 )
					ret := 1.000000 // buy
	if( smoothedDirectionalMovementPlus > 0.223067 )
		if( smoothedDirectionalMovementMinus <= 0.811366 )
			if( smoothedTrueRange <= 1.65023 )
				if( adx <= 14.7573 )
					if( trueRange <= 1.95355 )
						ret := 0.617647
					if( trueRange > 1.95355 )
						ret := -0.416667
				if( adx > 14.7573 )
					if( adx <= 28.6833 )
						ret := -0.255263
					if( adx > 28.6833 )
						ret := 0.115068
			if( smoothedTrueRange > 1.65023 )
				if( adx <= 20.3009 )
					if( adx <= 12.4934 )

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
