//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: Blai5_Koncorde_v10
// ID_model: UPST_30Min_1KON_24885cd9 Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_UPST_30Min_1KON_24885cd9", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_UPST_30Min_24885cd9(nvi, nvi_ema, marron_mean, source, azul, verde_azul, verde_mean, xmf, pvimin, stoc, media, tprice, marron, pvim, pvimax, xrsi, oscp, pvi, nvimax, nvimin, verde, verde_media, azul_mean, nvim, BollOsc, pvi_ema, media_azul)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=6, max_features=0.82,max_leaf_nodes=30, random_state=843828734)
	if( media <= 47.4942 )
		if( tprice <= 123.329 )
			if( pvimin <= 3.12054 )
				if( xrsi <= 27.6088 )
					ret := 0.431579
				if( xrsi > 27.6088 )
					if( media <= 8.39365 )
						ret := -0.647059
					if( media > 8.39365 )
						ret := 0.079254
			if( pvimin > 3.12054 )
				if( BollOsc <= -13.6474 )
					if( azul_mean <= -12.2687 )
						if( xrsi <= 14.1808 )
							ret := -0.609467
						if( xrsi > 14.1808 )
							ret := -0.140378
					if( azul_mean > -12.2687 )
						if( pvim <= 3.19151 )
							ret := -0.862069 // sell
						if( pvim > 3.19151 )
							ret := 0.032497
				if( BollOsc > -13.6474 )
					if( verde_mean <= 24.8536 )
						ret := -0.428309
					if( verde_mean > 24.8536 )
						if( azul <= 17.5871 )
							ret := -0.223847
						if( azul > 17.5871 )
							ret := 0.181548
		if( tprice > 123.329 )
			if( source <= 189.628 )
				if( xmf <= 5.28165 )
					if( xrsi <= 14.4826 )
						ret := 0.714286 // buy
					if( xrsi > 14.4826 )
						ret := -0.821293 // sell
				if( xmf > 5.28165 )
					if( azul_mean <= -12.8944 )
						ret := 0.101307
					if( azul_mean > -12.8944 )
						if( xmf <= 47.6918 )
							ret := -0.230000
						if( xmf > 47.6918 )
							ret := -0.676157
			if( source > 189.628 )
				if( pvi <= 3.42342 )
					ret := 0.494118

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
