//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: L_Bull_Bear_Power, L_Chaikin_Money_Flow
// ID_model: ZI_1Day_2BC0_5f550fac Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_ZI_1Day_2BC0_5f550fac", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_ZI_1Day_5f550fac(bbp, bullPower, BBPower_Color, bearPower, bbm, ad, ad_mf, mf)=>
	var float ret = 0  // # DecisionTreeRegressor(criterion=friedman_mse, max_depth=5, max_features=0.9,max_leaf_nodes=12, min_samples_split=5,random_state=843828734)
	if( bbp <= -3.40608 )
		if( mf <= 0.091769 )
			if( ad <= -2.50075e+06 )
				ret := 0.706522 // buy
			if( ad > -2.50075e+06 )
				if( ad <= -413090 )
					ret := -0.289474
				if( ad > -413090 )
					ret := 0.441667
		if( mf > 0.091769 )
			if( bbm <= 2.11957 )
				ret := 0.750000 // buy
			if( bbm > 2.11957 )
				ret := -0.826087 // sell
	if( bbp > -3.40608 )
		if( ad_mf <= -3.03199e+06 )
			if( bbm <= 0.715187 )
				ret := 0.065574
			if( bbm > 0.715187 )
				ret := -0.636364
		if( ad_mf > -3.03199e+06 )
			if( bbm <= 3.51062 )
				if( ad <= 975473 )
					if( bullPower <= -0.396063 )
						ret := -0.320000
					if( bullPower > -0.396063 )
						ret := 0.250485
				if( ad > 975473 )
					ret := -0.127072
			if( bbm > 3.51062 )
				if( mf <= 0.001257 )
					ret := 0.185185
				if( mf > 0.001257 )
					ret := -0.644737
	
    ret //return
// Define expected timeframe based on the selected interval: 1Day pine_value: D   Trigger an alert and show a label if the timeframe is incorrect
alert_message_time_wrong = "The current candle TIMEframe is WRONG: "+ str.tostring(timeframe.period) + ", CHANGE it to the CORRECT one:  1DAY !!"
if (str.tostring(timeframe.period) != "D")
    alert(alert_message_time_wrong, alert.freq_once_per_bar_close)
    label.new(bar_index -300, high+30, text = alert_message_time_wrong, style = label.style_label_down,size = size.large, color = color.red, textcolor = color.white)
    log.error(alert_message_time_wrong)

//CODE associated with the technical indicator L_Bull_Bear_Power 
//@version=5
//indicator "Bull Bear Power", shorttitle="BBP")
lengthInput = input.int(13, title="Length")
bullPower = high - ta.ema(close, lengthInput)

	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
