//Welcome to © Tuisku Trading Strategy, a sophisticated and optimised solution created by the experienced team at Tuisku.eu. Our team of experts specialise in random forest AI, harnessing its powerful capabilities to improve trading performance.
//Tuisku's commitment to quality and innovation shines through in every aspect of this strategy.


// Technical base pattern: Madrid_Moving_Average_Ribbon
// ID_model: ZI_1Day_1MAD_3ff0936e Date Creation: 2024/10/18 Recommended expiry date : 2025/06/18
//@version=5
strategy("Tuisku_ZI_1Day_1MAD_3ff0936e", overlay=true, margin_long=1000, margin_short=1000, pyramiding=1)
//RANDOM FOREST AI 
decision_tree_0_ZI_1Day_3ff0936e(ma25, ma40, ma85, ma05, ma45_colorInt, ma80_colorInt, ma55, ma20, ma65_colorInt, ma05_colorInt, ma10, ma40_colorInt, ma50_colorInt, ma60_colorInt, ma15, ma65, ma85_colorInt, ma45, ma35, ma10_colorInt, ma60, ma100, ma20_colorInt, ma55_colorInt, ma75_colorInt, ma90, ma30, ma15_colorInt, ma25_colorInt, ma80, ma90_colorInt, ma50, ma70_colorInt, ma30_colorInt, ma35_colorInt, ma75, ma70)=>
	var float ret = 0  // # DecisionTreeRegressor(max_depth=5, max_features=sqrt, max_leaf_nodes=12,min_samples_leaf=4, min_samples_split=5,random_state=843828734)
	if( ma90_colorInt <= 3.5 )
		if( ma40 <= 16.0743 )
			if( ma90 <= 16.3953 )
				if( ma85 <= 12.9034 )
					ret := 0.517857
				if( ma85 > 12.9034 )
					if( ma50 <= 13.1117 )
						ret := -1.000000 // sell
					if( ma50 > 13.1117 )
						ret := 0.105263
			if( ma90 > 16.3953 )
				ret := 0.880000 // buy
		if( ma40 > 16.0743 )
			if( ma65 <= 21.0684 )
				if( ma100 <= 17.2711 )
					ret := -0.232558
				if( ma100 > 17.2711 )
					ret := -0.721519 // sell
			if( ma65 > 21.0684 )
				if( ma45 <= 39.1253 )
					if( ma30 <= 31.2073 )
						ret := 0.124224
					if( ma30 > 31.2073 )
						ret := 0.756303 // buy
				if( ma45 > 39.1253 )
					if( ma60 <= 42.149 )
						ret := -0.259067
					if( ma60 > 42.149 )
						ret := 0.078671
	if( ma90_colorInt > 3.5 )
		if( ma35_colorInt <= 3.5 )
			ret := -0.972973 // sell
		if( ma35_colorInt > 3.5 )
			ret := -0.266055
	
    ret //return
// Define expected timeframe based on the selected interval: 1Day pine_value: D   Trigger an alert and show a label if the timeframe is incorrect
alert_message_time_wrong = "The current candle TIMEframe is WRONG: "+ str.tostring(timeframe.period) + ", CHANGE it to the CORRECT one:  1DAY !!"
if (str.tostring(timeframe.period) != "D")
    alert(alert_message_time_wrong, alert.freq_once_per_bar_close)
    label.new(bar_index -300, high+30, text = alert_message_time_wrong, style = label.style_label_down,size = size.large, color = color.red, textcolor = color.white)
    log.error(alert_message_time_wrong)

//CODE associated with the technical indicator Madrid_Moving_Average_Ribbon 
//@version=5
//indicator "Madrid Moving Average Ribbon", shorttitle="Madrid Ribbon", overlay=true)



	...
The rest of this Pine script is part of the paid version. Visit the website for more info.
